import { format } from "./utils";

type TextKey = keyof typeof texts;

export const t = (key: TextKey | (string & {}), ...params: string[]) =>
	format(key in texts ? texts[key as TextKey] : `${key} 🐧`, ...params);

const texts = {
	"{0} Appointments created": "{0} Termine erstellt",
	"{0} players": "{0} Spieler:innen",
	"1st place": "1. Platz",
	"2nd place": "2. Platz",
	"3rd place": "3. Platz",
	Accept: "Annehmen",
	Accepted: "Angenommen",
	"Active players": "Aktive Spieler:innen",
	"Active Subscriptions": "Geräte mit aktivierten Benachrichtigungen",
	Adult: "Erwachsen",
	"Age Group": "Altersklasse",
	"An Error occurred": "Ein Fehler ist aufgetreten",
	Apply: "Anwenden",
	Appointment: "Termin",
	"Appointment created": "Termin erstellt",
	"Appointment deleted": "Termin gelöscht",
	"Appointment found": "Termin gefunden",
	"Appointment is still in draft.": "Termin ist noch in der Entwurfsphase.",
	"Appointment not found": "Termin nicht gefunden",
	"Appointment not found.": "Termin nicht gefunden.",
	"Appointment published": "Termin veröffentlicht",
	"Appointment restored": "Termin wiederhergestellt",
	"Appointment Types": "Terminarten",
	"Appointment type": "Termintyp",
	"Appointment updated": "Termin aktualisiert",
	"Appointment was deleted.": "Termin wurde gelöscht.",
	Appointments: "Termine",
	"Are you sure you want to delete this appointment?":
		"Bist du sicher, dass du diesen Termin löschen möchtest?",
	"Are you sure you want to delete this player?":
		"Bist du sicher, dass du diese Spieler:in löschen möchtest?",
	"Are you sure you want to delete this team?":
		"Bist du sicher, dass du dieses Team löschen möchtest?",
	Bavaria: "Bayern",
	Calendar: "Kalender",
	"Calendar Feed": "Kalender-Feed",
	"Calendar Feed Settings": "Kalender-Feed Einstellungen",
	"Categories found": "Kategorien gefunden",
	Category: "Kategorie",
	"Choose a player": "Wähle eine Spieler:in",
	"Choose a team": "Wähle ein Team",
	"Choose a type": "Wähle einen Typ",
	"Choose an appointment": "Wähle einen Termin",
	"Choose an area": "Wähle eine Region",
	Clear: "Löschen",
	Close: "Schließen",
	"Compared to {0}": "Verglichen mit {0}",
	Configuration: "Konfiguration",
	"Confirm Password": "Passwort bestätigen",
	Copy: "Kopieren",
	"Copy Invitation Link": "Einladungslink kopieren",
	"Copy Links": "Links kopieren",
	"Copy link": "Link kopieren",
	"Copy Password Reset Link": "Zurücksetzungslink kopieren",
	Country: "Land",
	Create: "Erstellen",
	"Create Account": "Account erstellen",
	"Create appointment": "Termin erstellen",
	"Create new Invitation": "Neue Einladung erstellen",
	"Create new link": "Erstelle neuen Link",
	"Create new user": "Neuen Benutzer erstellen",
	"Create season": "Saison erstellen",
	"Current season": "Aktuelle Saison",
	Dashboard: "Dashboard",
	Date: "Datum",
	Decline: "Ablehnen",
	Declined: "Abgelehnt",
	Delete: "Löschen",
	"Delete appointment": "Termin löschen",
	"Delete player": "Spieler:in löschen",
	"Delete team": "Team löschen",
	"Download iCal": "Termin speichern",
	Edit: "Bearbeiten",
	"Edit appointment": "Termin bearbeiten",
	End: "Ende",
	"End date must be after start date":
		"Enddatum muss nach dem Startdatum liegen",
	EndDate: "Ende",
	Expired: "Abgelaufen",
	"Feed config loaded": "Feed-Konfiguration geladen",
	"Feed Settings updated": "Feed-Einstellungen aktualisiert",
	"Feed settings updated": "Feed-Einstellungen aktualisiert",
	"Feed URL copied to clipboard": "Feed-URL kopiert",
	Filters: "Filter",
	Germany: "Deutschland",
	"Get a notification when a new appointment is created":
		"Erhalte eine Benachrichtigung, wenn ein neuer Termin erstellt wird",
	"Get a notification when an accepted appointment was changed":
		"Erhalte eine Benachrichtigung, wenn ein akzeptierter Termin geändert wurde",
	"Grant Permission": "Benachrichtigunen erlauben",
	Holiday: "Ferien",
	Import: "Importieren",
	"Import Holidays": "Ferien/Feiertage importieren",
	Imports: "Importe",
	"Include draft appointments": "Entwurfs-Termine hinzufügen",
	"Incorrect user name or password":
		"Falscher Benutzername oder falsches Passwort",
	"Invitation Active": "Einladung aktiv",
	"Invitation expired": "Einladung abgelaufen",
	"Invitation link copied to clipboard":
		"Einladungslink in die Zwischenablage kopiert",
	"Invitation not found": "Einladung nicht gefunden",
	League: "Liga",
	"Leave all unchecked to include all appointments regardless of response":
		"Alle deaktiviert lassen, um alle Termine unabhängig von der Antwort einzuschließen",
	Link: "Link",
	"Linked tournament trend": "Teilnehmerentwicklung Turniereserien",
	"Linked tournaments": "Verknüpfte Turniere",
	List: "Liste",
	Location: "Ort",
	Login: "Anmelden",
	Logout: "Abmelden",
	Maybe: "Vielleicht",
	Name: "Name",
	"Name must be at least 2 characters long":
		"Name muss mindestens 2 Zeichen lang sein",
	"New Appointment": "Neuer Termin",
	"Next Appointment": "Nächster Termin",
	"Next month": "Nächster Monat",
	"No appointment set": "Kein Termin gesetzt",
	"No appointments found": "Keine Termine gefunden",
	"No appointments in the next 4 weeks":
		"Keine Termine in den nächsten 4 Wochen",
	"No items found": "Keine Einträge gefunden",
	"No link set": "Kein Link gesetzt",
	"No linked tournament series found":
		"Keine verknüpften Turnierserien gefunden",
	"No location set": "Kein Ort gesetzt",
	"No players found": "Keine Spieler:innen gefunden",
	"No previous season data": "Keine Daten aus der Vorsaison",
	"No seasons found": "Keine Saisons gefunden",
	"No statistics available": "Keine Statistikdaten verfügbar",
	"No team set": "Gehört keinem Team an",
	"No teams found": "Keine Teams gefunden",
	"Not authenticated": "Nicht authentifiziert",
	Notifications: "Benachrichtigungen",
	"Notifications are not supported in this browser":
		"Benachrichtigungen werden in diesem Browser nicht unterstützt",
	"On iOS devices, you must add the website to the home screen before notifications will work.":
		"Auf iOS-Geräten muss die Website zur Startseite hinzufügt werden, bevor Benachrichtigungen funktionieren.",
	"Other placements": "Weitere Platzierungen",
	"open sidebar": "Sidebar öffnen",
	"Participant already exists in this category":
		"Teilnehmer:in existiert bereits in dieser Kategorie",
	Participants: "Teilnehmer:innen",
	"Participation entries": "Teilnahme-Einträge",
	Participations: "Teilnahmen",
	"Participations by season": "Teilnahmen nach Saison",
	Password: "Passwort",
	"Password reset created": "Passwort-Zurücksetzung erstellt",
	"Password reset link copied to clipboard":
		"Zurücksetzungslink in die Zwischenablage kopiert",
	"Password reset request not found":
		"Anfrage zum Zurücksetzen des Passworts nicht gefunden",
	"Pending appointments": "Offene Termine",
	Placement: "Platzierung",
	"Placement created": "Platzierung erstellt",
	"Placement deleted": "Platzierung gelöscht",
	"Placement results": "Platzierungsergebnisse",
	"Placement updated": "Platzierung aktualisiert",
	Placements: "Platzierungen",
	Player: "Spieler:in",
	"Player counts are generated automatically from current players":
		"Die Spielerzahlen werden automatisch aus den aktuellen Spieler:innen erzeugt",
	"Player counts by age group": "Spielerzahlen nach Altersklasse",
	"Player created": "Spieler:in erstellt",
	"Player deleted": "Spieler:in gelöscht",
	"Player found": "Spieler:in gefunden",
	"Player not found": "Spieler:in nicht gefunden",
	"Player updated": "Spieler:in aktualisiert",
	Players: "Spieler:innen",
	"Players by age group": "Spieler:innen nach Altersklasse",
	"Players found": "Spieler:innen gefunden",
	"Previous month": "Vorheriger Monat",
	Profile: "Profil",
	Publish: "Veröffentlichen",
	"Publish?": "Veröffentlichen?",
	QTTR: "QTTR",
	"QTTR must be set (0 is allowed)": "QTTR muss gesetzt sein (0 ist erlaubt)",
	"Reset Password": "Passwort zurücksetzen",
	Response: "Antwort",
	"Response created": "Antwort erstellt",
	"Response Types": "Antworttypen",
	"Restore?": "Wiederherstellen?",
	Role: "Rolle",
	Search: "Suche",
	"Search Appointments": "Termine suchen",
	"Search Players": "Spieler:innen suchen",
	"Search Teams": "Teams suchen",
	Season: "Saison",
	"Season created": "Saison erstellt",
	"Season dates are invalid": "Saisondaten sind ungültig",
	"Season deleted": "Saison gelöscht",
	"Season end date": "Saisonende",
	"Season end date must be after start date":
		"Das Saisonende muss nach dem Saisonstart liegen",
	"Season overlaps with an existing season":
		"Die Saison überschneidet sich mit einer bestehenden Saison",
	"Season range": "Saisonzeitraum",
	"Season start date": "Saisonstart",
	Seasons: "Saisons",
	"Select a search type or use shortcuts":
		"Wähle einen Suchtyp oder benutze Shortcuts",
	"Set a password to create your Account":
		"Passwort festlegen, um Account zu erstellen",
	Settings: "Einstellungen",
	"Settings updated": "Einstellungen aktualisiert",
	ShortTitle: "Kurztitel",
	Show: "Zeige",
	"Show all": "Anzeigen",
	"Show deleted?": "Gelöschte anzeigen?",
	ShowAll: "Zeige alle",
	Start: "Start",
	StartDate: "Start",
	Statistics: "Statistiken",
	"Statistics loaded": "Statistiken geladen",
	Subdivision: "Region",
	"Subscribe to your personalized calendar feed to receive appointment updates in your calendar app":
		"Abonniere deinen personalisierten Kalender-Feed, um Terminaktualisierungen in deiner Kalender-App zu erhalten",
	"Subscription created": "Benachrichtigung erstellt",
	"Subscription deleted": "Benachrichtigung abgemeldet",
	"Switch Theme": "Theme wechseln",
	Team: "Team",
	"Team created": "Team erstellt",
	"Team deleted": "Team gelöscht",
	"Team found": "Team gefunden",
	"Team updated": "Team aktualisiert",
	Teams: "Teams",
	"Teams found": "Teams gefunden",
	"The passwords entered do not match":
		"Die eingegebenen Passwörter stimmen nicht überein",
	Time: "Zeit",
	Title: "Titel",
	Today: "Heute",
	"Top 8": "Top 8",
	Tournament: "Turnier",
	"Tournament (Germany)": "Turnier (Deutschland)",
	"Tournament types distribution": "Turnierarten-Verteilung",
	Tournaments: "Turniere",
	"Type to search...": "Tippe zum Suchen...",
	Unauthorized: "Nicht autorisiert",
	Unplaced: "Ohne Platzierung",
	"Upcoming appointments": "Anstehende Termine",
	Update: "Aktualisieren",
	"Update password": "Passwort aktualisieren",
	"Update player": "Spieler:in aktualisieren",
	"Update Role": "Rolle aktualisieren",
	"Update team": "Team aktualisieren",
	"Update your password": "Aktualisiere dein Passwort",
	"Use this URL in your calendar application to subscribe to your personal calendar feed.":
		"Verwende diese URL in deiner Kalenderanwendung, um deinen persönlichen Kalender-Feed zu abonnieren.",
	"User created": "Benutzer:in erstellt",
	"User deleted": "Benutzer:in gelöscht",
	"User Management": "Benutzerverwaltung",
	"User Name": "Benutzername",
	"User updated": "Benutzer aktualisiert",
	"Year of birth": "Geburtsjahr",
	"Year of birth must be set": "Geburtsjahr muss gesetzt sein",
	"You do not have permission to access import settings":
		"Du hast keine Berechtigung, um auf die Importeinstellungen zuzugreifen",
	"You do not have permission to access seasons":
		"Du hast keine Berechtigung, um auf die Saisons zuzugreifen",
	"You do not have permission to access user management":
		"Du hast keine Berechtigung, um auf die Benutzerverwaltung zuzugreifen",
	"You do not have permission to create appointments":
		"Du hast keine Berechtigung, um Termine zu erstellen",
	"You have no appointments": "Du hast keine Termine",
	"You responded to all appointments": "Du hast auf alle Termine reagiert",
	"Your appointments": "Deine Termine",
	"Your Feed URL": "Deine Feed-URL",
};
