import { format } from "./utils";

type TextKey = keyof typeof texts;

export const t = (key: TextKey | (string & {}), ...params: string[]) =>
	format(key in texts ? texts[key as TextKey] : `${key} 🐧`, ...params);

const texts = {
	"{0} Appointments created": "{0} Termine erstellt",
	"{0} appointments answered": "{0} Termine beantwortet",
	"{0} appointments deleted": "{0} Termine gelöscht",
	"{0} appointments duplicated": "{0} Termine dupliziert",
	"{0} appointments published": "{0} Termine veröffentlicht",
	"{0} appointments restored": "{0} Termine wiederhergestellt",
	"{0} appointments selected": "{0} Termine ausgewählt",
	"{0} appointments unpublished": "{0} Termine zurückgezogen",
	"{0} changed": "{0} geändert",
	"{0} fields changed": "{0} Felder geändert",
	"{0} invited": "{0} eingeladen",
	"{0} more": "{0} weitere",
	"{0} of {1} answered": "{0} von {1} beantwortet",
	"{0} of {1} events": "{0} von {1} Ereignissen",
	"{0} players": "{0} Spieler:innen",
	"1 appointment answered": "1 Termin beantwortet",
	"1 appointment created": "1 Termin erstellt",
	"1 appointment deleted": "1 Termin gelöscht",
	"1 appointment duplicated": "1 Termin dupliziert",
	"1 appointment published": "1 Termin veröffentlicht",
	"1 appointment restored": "1 Termin wiederhergestellt",
	"1 appointment selected": "1 Termin ausgewählt",
	"1 appointment unpublished": "1 Termin zurückgezogen",
	"1 field changed": "1 Feld geändert",
	"A closed period without training or events":
		"Ein geschlossener Zeitraum ohne Training oder Termine",
	"A competitive event players sign up for":
		"Eine Wettkampfveranstaltung, für die sich Spieler:innen anmelden",
	Accept: "Annehmen",
	Accepted: "Angenommen",
	Action: "Aktion",
	"Active Subscriptions": "Geräte mit aktivierten Benachrichtigungen",
	"Add a new event to the club calendar":
		"Neues Ereignis zum Vereinskalender hinzufügen",
	"Add participant": "Teilnehmer:in hinzufügen",
	Administrator: "Administrator:in",
	Adult: "Erwachsen",
	"Age Group": "Altersklasse",
	"All actions": "Alle Aktionen",
	"All age groups": "Alle Altersklassen",
	"All responses": "Alle Antworten",
	"All teams": "Alle Teams",
	"All types": "Alle Typen",
	"An Error occurred": "Ein Fehler ist aufgetreten",
	"An unexpected error occurred. Try again or go back to the overview.":
		"Ein unerwarteter Fehler ist aufgetreten. Versuche es erneut oder kehre zur Übersicht zurück.",
	Apply: "Anwenden",
	Appointment: "Termin",
	"Appointment created": "Termin erstellt",
	"Appointment deleted": "Termin gelöscht",
	"Appointment found": "Termin gefunden",
	"Appointment is still in draft.": "Termin ist noch in der Entwurfsphase.",
	"Appointment not found": "Termin nicht gefunden",
	"Appointment not found.": "Termin nicht gefunden.",
	"Appointment published": "Termin veröffentlicht",
	"Appointment restored": "Termin wiederhergestellt",
	"Appointment Types": "Terminarten",
	"Appointment type": "Termintyp",
	"Appointment unpublished": "Termin zurückgezogen",
	"Appointment updated": "Termin aktualisiert",
	"Appointment was deleted.": "Termin wurde gelöscht.",
	Appointments: "Termine",
	"Appointments could not be loaded": "Termine konnten nicht geladen werden",
	"Are you sure you want to delete {0} appointments?":
		"Bist du sicher, dass du {0} Termine löschen möchtest?",
	"Are you sure you want to delete this appointment?":
		"Bist du sicher, dass du diesen Termin löschen möchtest?",
	"Are you sure you want to delete this player?":
		"Bist du sicher, dass du diese Spieler:in löschen möchtest?",
	"Are you sure you want to delete this team?":
		"Bist du sicher, dass du dieses Team löschen möchtest?",
	Back: "Zurück",
	"Back to dashboard": "Zum Dashboard",
	Bavaria: "Bayern",
	Calendar: "Kalender",
	"Calendar Feed": "Kalender-Feed",
	"Calendar Feed Settings": "Kalender-Feed Einstellungen",
	Cancel: "Abbrechen",
	"Categories found": "Kategorien gefunden",
	Category: "Kategorie",
	"Category already exists": "Kategorie existiert bereits",
	Changed: "Geändert",
	"Choose a player": "Wähle eine Spieler:in",
	"Choose a team": "Wähle ein Team",
	"Choose a type": "Wähle einen Typ",
	"Choose an appointment": "Wähle einen Termin",
	"Choose an area": "Wähle eine Region",
	Clear: "Zurücksetzen",
	"Clear selection": "Auswahl aufheben",
	Close: "Schließen",
	"Club at a glance": "Verein auf einen Blick",
	Configuration: "Konfiguration",
	"Confirm Password": "Passwort bestätigen",
	Continue: "Weiter",
	Copy: "Kopieren",
	"Copy Invitation Link": "Einladungslink kopieren",
	"Copy Links": "Links kopieren",
	"Copy link": "Link kopieren",
	"Copy Password Reset Link": "Zurücksetzungslink kopieren",
	Country: "Land",
	Create: "Erstellen",
	"Create Account": "Account erstellen",
	"Create appointment": "Termin erstellen",
	"Create new Invitation": "Neue Einladung erstellen",
	"Create new link": "Erstelle neuen Link",
	"Create new user": "Neuen Benutzer erstellen",
	Created: "Erstellt",
	Dashboard: "Dashboard",
	Date: "Datum",
	"Date & Time": "Datum & Zeit",
	"Decide when TTHub notifies you on this device.":
		"Entscheide, wann dich TTHub auf diesem Gerät benachrichtigt.",
	Decline: "Ablehnen",
	Declined: "Abgelehnt",
	Delete: "Löschen",
	"Delete appointment": "Termin löschen",
	"Delete player": "Spieler:in löschen",
	"Delete team": "Team löschen",
	Deleted: "Gelöscht",
	"Deleted user": "Gelöschte:r Nutzer:in",
	Details: "Details",
	Dialog: "Dialog",
	"Download iCal": "Termin speichern",
	Draft: "Entwurf",
	Duplicate: "Duplizieren",
	Edit: "Bearbeiten",
	"Edit appointment": "Termin bearbeiten",
	Editor: "Editor:in",
	End: "Ende",
	EndDate: "Ende",
	Expired: "Abgelaufen",
	"Feed config loaded": "Feed-Konfiguration geladen",
	"Feed Settings updated": "Feed-Einstellungen aktualisiert",
	"Feed settings updated": "Feed-Einstellungen aktualisiert",
	"Feed URL copied to clipboard": "Feed-URL kopiert",
	Filters: "Filter",
	From: "Von",
	Germany: "Deutschland",
	"Get a notification when a new appointment is created":
		"Erhalte eine Benachrichtigung, wenn ein neuer Termin erstellt wird",
	"Get a notification when an accepted appointment was changed":
		"Erhalte eine Benachrichtigung, wenn ein akzeptierter Termin geändert wurde",
	"Grant Permission": "Benachrichtigunen erlauben",
	History: "Verlauf",
	Holiday: "Ferien",
	"Holidays and myTischtennis data": "Feiertage und myTischtennis-Daten",
	Import: "Importieren",
	"Import Holidays": "Ferien/Feiertage importieren",
	"Importer not found": "Importer nicht gefunden",
	Imports: "Importe",
	"Include draft appointments": "Entwurfs-Termine hinzufügen",
	"Incorrect user name or password":
		"Falscher Benutzername oder falsches Passwort",
	"Invitation Active": "Einladung aktiv",
	"Invitation expired": "Einladung abgelaufen",
	"Invitation link copied to clipboard":
		"Einladungslink in die Zwischenablage kopiert",
	"Invitation not found": "Einladung nicht gefunden",
	Join: "Beitreten",
	Journal: "Journal",
	"Last updated": "Zuletzt aktualisiert",
	League: "Liga",
	"League table": "Tabelle",
	"League table and fixtures are not available yet.":
		"Tabelle und Spielplan sind noch nicht verfügbar.",
	"Leave all unchecked to include all appointments regardless of response":
		"Alle deaktiviert lassen, um alle Termine unabhängig von der Antwort einzuschließen",
	Link: "Link",
	List: "Liste",
	"Load {0} more ({1} remaining)": "{0} weitere laden ({1} verbleibend)",
	"Loading…": "Lädt…",
	Location: "Ort",
	Login: "Anmelden",
	Logout: "Abmelden",
	"Manage club members and invitations":
		"Vereinsmitglieder und Einladungen verwalten",
	Max: "Max",
	Maybe: "Vielleicht",
	Min: "Min",
	"More details": "Weitere Details",
	Name: "Name",
	"Name must be at least 2 characters long":
		"Name muss mindestens 2 Zeichen lang sein",
	"Name, password and push notifications":
		"Name, Passwort und Push-Benachrichtigungen",
	"Needs your response": "Braucht deine Antwort",
	"New Appointment": "Neuer Termin",
	"New category": "Neue Kategorie",
	"Next Appointment": "Nächster Termin",
	"Next month": "Nächster Monat",
	"Next up": "Als Nächstes",
	"No appointment set": "Kein Termin gesetzt",
	"No appointments found": "Keine Termine gefunden",
	"No appointments in the next 4 weeks":
		"Keine Termine in den nächsten 4 Wochen",
	"No items found": "Keine Einträge gefunden",
	"No link set": "Kein Link gesetzt",
	"No location set": "Kein Ort gesetzt",
	"No participants yet": "Noch keine Teilnehmer:innen",
	"No players found": "Keine Spieler:innen gefunden",
	"No response": "Keine Antwort",
	"No team": "Ohne Team",
	"No team set": "Gehört keinem Team an",
	"No teams found": "Keine Teams gefunden",
	"Not authenticated": "Nicht authentifiziert",
	"Not available yet": "Noch nicht verfügbar",
	"Not yet enabled for this device.": "Noch nicht aktiviert für dieses Gerät.",
	Notifications: "Benachrichtigungen",
	"Notifications are not supported in this browser":
		"Benachrichtigungen werden in diesem Browser nicht unterstützt",
	"On iOS devices, you must add the website to the home screen before notifications will work.":
		"Auf iOS-Geräten muss die Website zur Startseite hinzufügt werden, bevor Benachrichtigungen funktionieren.",
	"Open appointment": "Termin öffnen",
	"Open team": "Team öffnen",
	Overview: "Übersicht",
	"open sidebar": "Sidebar öffnen",
	"Page not found": "Seite nicht gefunden",
	"Participant already exists in this category":
		"Teilnehmer:in existiert bereits in dieser Kategorie",
	Participants: "Teilnehmer:innen",
	Password: "Passwort",
	"Password reset created": "Passwort-Zurücksetzung erstellt",
	"Password reset link copied to clipboard":
		"Zurücksetzungslink in die Zwischenablage kopiert",
	"Password reset request not found":
		"Anfrage zum Zurücksetzen des Passworts nicht gefunden",
	Pending: "Ausstehend",
	"Pending appointments": "Offene Termine",
	Person: "Person",
	Placement: "Platzierung",
	"Placement created": "Platzierung erstellt",
	"Placement deleted": "Platzierung gelöscht",
	"Placement updated": "Platzierung aktualisiert",
	Player: "Spieler:in",
	"Player created": "Spieler:in erstellt",
	"Player deleted": "Spieler:in gelöscht",
	"Player found": "Spieler:in gefunden",
	"Player not found": "Spieler:in nicht gefunden",
	"Player updated": "Spieler:in aktualisiert",
	Players: "Spieler:innen",
	"Players found": "Spieler:innen gefunden",
	Preview: "Vorschau",
	"Previous month": "Vorheriger Monat",
	Profile: "Profil",
	"Profile & Security": "Profil & Sicherheit",
	Publish: "Veröffentlichen",
	"Publish appointment": "Termin veröffentlichen",
	"Publish?": "Veröffentlichen?",
	Published: "Veröffentlicht",
	QTTR: "QTTR",
	"QTTR must be set (0 is allowed)": "QTTR muss gesetzt sein (0 ist erlaubt)",
	"Reset Password": "Passwort zurücksetzen",
	Response: "Antwort",
	"Response created": "Antwort erstellt",
	"Response Types": "Antworttypen",
	Responses: "Antworten",
	Restore: "Wiederherstellen",
	"Restore?": "Wiederherstellen?",
	Restored: "Wiederhergestellt",
	Results: "Ergebnisse",
	Review: "Überprüfung",
	Role: "Rolle",
	Save: "Speichern",
	Search: "Suche",
	"Search Appointments": "Termine suchen",
	"Search appointment or person...": "Termin oder Person suchen…",
	"Search Players": "Spieler:innen suchen",
	"Search Teams": "Teams suchen",
	"Select a row to see details": "Zeile auswählen, um Details zu sehen",
	"Select a search type or use shortcuts":
		"Wähle einen Suchtyp oder benutze Shortcuts",
	Selected: "Ausgewählt",
	"Set a password to create your Account":
		"Passwort festlegen, um Account zu erstellen",
	Settings: "Einstellungen",
	"Settings updated": "Einstellungen aktualisiert",
	ShortTitle: "Kurztitel",
	Show: "Zeige",
	"Show all": "Anzeigen",
	"Show deleted?": "Gelöschte anzeigen?",
	ShowAll: "Zeige alle",
	Start: "Start",
	StartDate: "Start",
	Status: "Status",
	Subdivision: "Region",
	"Subscribe to your personal calendar": "Kalender abonnieren",
	"Subscribe to your personalized calendar feed to receive appointment updates in your calendar app":
		"Abonniere deinen personalisierten Kalender-Feed, um Terminaktualisierungen in deiner Kalender-App zu erhalten",
	"Subscription created": "Benachrichtigung erstellt",
	"Subscription deleted": "Benachrichtigung abgemeldet",
	"Swipe to respond": "Wischen zum Antworten",
	"Switch Theme": "Theme wechseln",
	Team: "Team",
	"Team could not be loaded": "Team konnte nicht geladen werden",
	"Team created": "Team erstellt",
	"Team deleted": "Team gelöscht",
	"Team found": "Team gefunden",
	"Team updated": "Team aktualisiert",
	Teams: "Teams",
	"Teams found": "Teams gefunden",
	"The passwords entered do not match":
		"Die eingegebenen Passwörter stimmen nicht überein",
	"This address doesn't exist or has been moved.":
		"Diese Adresse existiert nicht oder wurde verschoben.",
	Time: "Zeit",
	Title: "Titel",
	To: "Bis",
	Today: "Heute",
	Tomorrow: "Morgen",
	Tournament: "Turnier",
	"Tournament (Germany)": "Turnier (Deutschland)",
	Tournaments: "Turniere",
	Trainer: "Trainer:in",
	"Transaction Journal": "Transaktionsjournal",
	"Transactions found": "Transaktionen gefunden",
	"Try again": "Erneut versuchen",
	Type: "Typ",
	"Type to search...": "Tippe zum Suchen...",
	Unauthorized: "Nicht autorisiert",
	Unpublish: "Zurückziehen",
	"Unpublish appointment": "Termin zurückziehen",
	Untitled: "Unbenannt",
	"Upcoming appointments": "Nächste Termine",
	Update: "Aktualisieren",
	"Update password": "Passwort aktualisieren",
	"Update player": "Spieler:in aktualisieren",
	"Update Role": "Rolle aktualisieren",
	"Update team": "Team aktualisieren",
	"Update your name or set a new password.":
		"Aktualisiere deinen Namen oder setze ein neues Passwort.",
	"Update your password": "Aktualisiere dein Passwort",
	"Use this URL in your calendar application to subscribe to your personal calendar feed.":
		"Verwende diese URL in deiner Kalenderanwendung, um deinen persönlichen Kalender-Feed zu abonnieren.",
	User: "User:in",
	"User created": "Benutzer:in erstellt",
	"User deleted": "Benutzer:in gelöscht",
	"User Management": "Benutzerverwaltung",
	"User Name": "Benutzername",
	"User updated": "Benutzer aktualisiert",
	"Year of birth": "Geburtsjahr",
	"Year of birth must be set": "Geburtsjahr muss gesetzt sein",
	"You cannot change your own role":
		"Du kannst deine eigene Rolle nicht ändern",
	"You do not have permission to access import settings":
		"Du hast keine Berechtigung, um auf die Importeinstellungen zuzugreifen",
	"You do not have permission to access user management":
		"Du hast keine Berechtigung, um auf die Benutzerverwaltung zuzugreifen",
	"You do not have permission to create appointments":
		"Du hast keine Berechtigung, um Termine zu erstellen",
	"You have no appointments": "Du hast keine Termine",
	"You responded to all appointments": "Du hast auf alle Termine reagiert",
	"You've reached the end — {0} events": "Das war's — {0} Ereignisse",
	"Your appointments": "Deine Termine",
	"Your Feed URL": "Deine Feed-URL",
};
