import { format } from "./utils";

type TextKey = keyof typeof texts;

export const t = (key: TextKey | (string & {}), ...params: string[]) =>
	format(key in texts ? texts[key as TextKey] : `${key} 🐧`, ...params);

const texts = {
	"{0} Appointments created": "{0} Termine erstellt",
	Accept: "Annehmen",
	Accepted: "Angenommen",
	"Active Subscriptions": "Geräte mit aktivierten Benachrichtigungen",
	"An Error occurred": "Ein Fehler ist aufgetreten",
	Apply: "Anwenden",
	"Appointment created": "Termin erstellt",
	"Appointment deleted": "Termin gelöscht",
	"Appointment found": "Termin gefunden",
	"Appointment is still in draft.": "Termin ist noch in der Entwurfsphase.",
	"Appointment not found": "Termin nicht gefunden",
	"Appointment not found.": "Termin nicht gefunden.",
	"Appointment published": "Termin veröffentlicht",
	"Appointment restored": "Termin wiederhergestellt",
	"Appointment type": "Termintyp",
	"Appointment updated": "Termin aktualisiert",
	"Appointment was deleted.": "Termin wurde gelöscht.",
	Appointments: "Termine",
	"Are you sure you want to delete this appointment?":
		"Bist du sicher, dass du diesen Termin löschen möchtest?",
	"Are you sure you want to delete this player?":
		"Bist du sicher, dass du diese Spieler:in löschen möchtest?",
	Bavaria: "Bayern",
	Calendar: "Kalender",
	"Categories found": "Kategorien gefunden",
	Category: "Kategorie",
	"Choose a player": "Wähle eine Spieler:in",
	"Choose a type": "Wähle einen Typ",
	"Choose an area": "Wähle eine Region",
	Clear: "Löschen",
	Close: "Schließen",
	"Confirm Password": "Passwort bestätigen",
	"Copy link": "Link kopieren",
	Country: "Land",
	Create: "Erstellen",
	"Create appointment": "Termin erstellen",
	"Create new link": "Erstelle neuen Link",
	"Create new user": "Neuen Benutzer erstellen",
	Dashboard: "Dashboard",
	Date: "Datum",
	Declined: "Abgelehnt",
	Delete: "Löschen",
	"Delete appointment": "Termin löschen",
	"Delete player": "Spieler:in löschen",
	"Download iCal": "Termin speichern",
	Edit: "Bearbeiten",
	"Edit appointment": "Termin bearbeiten",
	End: "Ende",
	EndDate: "Ende",
	Expired: "Abgelaufen",
	Filters: "Filter",
	Germany: "Deutschland",
	"Get a notification when a new appointment is created":
		"Erhalte eine Benachrichtigung, wenn ein neuer Termin erstellt wird",
	"Get a notification when an accepted appointment was changed":
		"Erhalte eine Benachrichtigung, wenn ein akzeptierter Termin geändert wurde",
	Holiday: "Ferien",
	Import: "Importieren",
	"Import Holidays": "Ferien/Feiertage importieren",
	Imports: "Importe",
	"Incorrect user name or password":
		"Falscher Benutzername oder falsches Passwort",
	"Invitation expired": "Einladung abgelaufen",
	"Invitation not found": "Einladung nicht gefunden",
	Link: "Link",
	List: "Liste",
	Location: "Ort",
	Login: "Anmelden",
	Logout: "Abmelden",
	Maybe: "Vielleicht",
	Name: "Name",
	"Name must be at least 2 characters long":
		"Name muss mindestens 2 Zeichen lang sein",
	"New Appointment": "Neuer Termin",
	"Next month": "Nächster Monat",
	"No appointments found": "Keine Termine gefunden",
	"No appointments in the next 4 weeks":
		"Keine Termine in den nächsten 4 Wochen",
	"No link set": "Kein Link gesetzt",
	"No location set": "Kein Ort gesetzt",
	"No players found": "Keine Spieler:innen gefunden",
	"No team set": "Gehört keinem Team an",
	"Not authenticated": "Nicht authentifiziert",
	Notifications: "Benachrichtigungen",
	"Notifications are not supported in this browser":
		"Benachrichtigungen werden in diesem Browser nicht unterstützt",
	"On iOS devices, you must add the website to the home screen before notifications will work.":
		"Auf iOS-Geräten muss die Website zur Startseite hinzufügt werden, bevor Benachrichtigungen funktionieren.",
	"open sidebar": "Sidebar öffnen",
	"Participant already exists in this category":
		"Teilnehmer:in existiert bereits in dieser Kategorie",
	Participants: "Teilnehmer:innen",
	Password: "Passwort",
	"Pending appointments": "Offene Termine",
	Placement: "Platzierung",
	"Placement created": "Platzierung erstellt",
	"Placement deleted": "Platzierung gelöscht",
	"Placement updated": "Platzierung aktualisiert",
	Player: "Spieler:in",
	"Player created": "Spieler:in erstellt",
	"Player deleted": "Spieler:in gelöscht",
	"Player found": "Spieler:in gefunden",
	"Player not found": "Spieler:in nicht gefunden",
	"Player updated": "Spieler:in aktualisiert",
	Players: "Spieler:innen",
	"Players found": "Spieler:innen gefunden",
	"Previous month": "Vorheriger Monat",
	Profile: "Profil",
	Publish: "Veröffentlichen",
	"Publish?": "Veröffentlichen?",
	QTTR: "QTTR",
	"QTTR must be set (0 is allowed)": "QTTR muss gesetzt sein (0 ist erlaubt)",
	Response: "Antwort",
	"Response created": "Antwort erstellt",
	"Restore?": "Wiederherstellen?",
	Role: "Rolle",
	"Set a password to create your Account":
		"Passwort festlegen, um Account zu erstellen",
	Settings: "Einstellungen",
	"Settings updated": "Einstellungen aktualisiert",
	ShortTitle: "Kurztitel",
	Show: "Zeige",
	"Show all": "Anzeigen",
	"Show deleted?": "Gelöschte anzeigen?",
	ShowAll: "Zeige alle",
	Start: "Start",
	StartDate: "Start",
	Subdivision: "Region",
	"Switch Theme": "Theme wechseln",
	Team: "Team",
	"The passwords entered do not match":
		"Die eingegebenen Passwörter stimmen nicht überein",
	Time: "Zeit",
	Title: "Titel",
	Today: "Heute",
	Tournament: "Turnier",
	Unauthorized: "Nicht autorisiert",
	"Upcoming appointments": "Anstehende Termine",
	Update: "Aktualisieren",
	"Update player": "Spieler:in aktualisieren",
	"User created": "Benutzer:in erstellt",
	"User deleted": "Benutzer:in gelöscht",
	"User Management": "Benutzerverwaltung",
	"User Name": "Benutzername",
	"User updated": "Benutzer aktualisiert",
	"Year of birth": "Geburtsjahr",
	"Year of birth must be set": "Geburtsjahr muss gesetzt sein",
	"You have no appointments": "Du hast keine Termine",
	"You responded to all appointments": "Du hast auf alle Termine reagiert",
	"Your appointments": "Deine Termine",
};
