
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  USER: 'USER',
  EDITOR: 'EDITOR',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const AppointmentStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED'
} as const

export type AppointmentStatus = (typeof AppointmentStatus)[keyof typeof AppointmentStatus]


export const AppointmentType = {
  TOURNAMENT_BY: 'TOURNAMENT_BY',
  TOURNAMENT_DE: 'TOURNAMENT_DE',
  HOLIDAY: 'HOLIDAY'
} as const

export type AppointmentType = (typeof AppointmentType)[keyof typeof AppointmentType]


export const ResponseType = {
  ACCEPT: 'ACCEPT',
  MAYBE: 'MAYBE',
  DECLINE: 'DECLINE'
} as const

export type ResponseType = (typeof ResponseType)[keyof typeof ResponseType]
