
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  FeedConfig: 'FeedConfig',
  UserInvitation: 'UserInvitation',
  PasswordReset: 'PasswordReset',
  Appointment: 'Appointment',
  Response: 'Response',
  Player: 'Player',
  Team: 'Team',
  Placement: 'Placement',
  Subscription: 'Subscription',
  NotificationSettings: 'NotificationSettings'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  userName: 'userName',
  password: 'password',
  name: 'name',
  role: 'role',
  feedId: 'feedId'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const FeedConfigScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  includeResponseTypes: 'includeResponseTypes',
  includeDraftStatus: 'includeDraftStatus',
  includeAppointmentTypes: 'includeAppointmentTypes'
} as const

export type FeedConfigScalarFieldEnum = (typeof FeedConfigScalarFieldEnum)[keyof typeof FeedConfigScalarFieldEnum]


export const UserInvitationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  userId: 'userId'
} as const

export type UserInvitationScalarFieldEnum = (typeof UserInvitationScalarFieldEnum)[keyof typeof UserInvitationScalarFieldEnum]


export const PasswordResetScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  userId: 'userId'
} as const

export type PasswordResetScalarFieldEnum = (typeof PasswordResetScalarFieldEnum)[keyof typeof PasswordResetScalarFieldEnum]


export const AppointmentScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  deletedAt: 'deletedAt',
  startDate: 'startDate',
  endDate: 'endDate',
  title: 'title',
  shortTitle: 'shortTitle',
  location: 'location',
  link: 'link',
  type: 'type',
  status: 'status',
  nextAppointmentId: 'nextAppointmentId'
} as const

export type AppointmentScalarFieldEnum = (typeof AppointmentScalarFieldEnum)[keyof typeof AppointmentScalarFieldEnum]


export const ResponseScalarFieldEnum = {
  userId: 'userId',
  appointmentId: 'appointmentId',
  responseType: 'responseType'
} as const

export type ResponseScalarFieldEnum = (typeof ResponseScalarFieldEnum)[keyof typeof ResponseScalarFieldEnum]


export const PlayerScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  year: 'year',
  qttr: 'qttr',
  teamId: 'teamId'
} as const

export type PlayerScalarFieldEnum = (typeof PlayerScalarFieldEnum)[keyof typeof PlayerScalarFieldEnum]


export const TeamScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  title: 'title',
  league: 'league',
  placement: 'placement'
} as const

export type TeamScalarFieldEnum = (typeof TeamScalarFieldEnum)[keyof typeof TeamScalarFieldEnum]


export const PlacementScalarFieldEnum = {
  createdAt: 'createdAt',
  playerId: 'playerId',
  appointmentId: 'appointmentId',
  category: 'category',
  placement: 'placement'
} as const

export type PlacementScalarFieldEnum = (typeof PlacementScalarFieldEnum)[keyof typeof PlacementScalarFieldEnum]


export const SubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  device: 'device',
  endpoint: 'endpoint',
  p256dh: 'p256dh',
  auth: 'auth'
} as const

export type SubscriptionScalarFieldEnum = (typeof SubscriptionScalarFieldEnum)[keyof typeof SubscriptionScalarFieldEnum]


export const NotificationSettingsScalarFieldEnum = {
  userId: 'userId',
  subscriptionId: 'subscriptionId',
  newAppointment: 'newAppointment',
  changedAppointment: 'changedAppointment'
} as const

export type NotificationSettingsScalarFieldEnum = (typeof NotificationSettingsScalarFieldEnum)[keyof typeof NotificationSettingsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

