
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FeedConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model FeedConfig
 * 
 */
export type FeedConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$FeedConfigPayload>

export type AggregateFeedConfig = {
  _count: FeedConfigCountAggregateOutputType | null
  _min: FeedConfigMinAggregateOutputType | null
  _max: FeedConfigMaxAggregateOutputType | null
}

export type FeedConfigMinAggregateOutputType = {
  id: string | null
  userId: string | null
  includeResponseTypes: string | null
  includeDraftStatus: boolean | null
  includeAppointmentTypes: string | null
}

export type FeedConfigMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  includeResponseTypes: string | null
  includeDraftStatus: boolean | null
  includeAppointmentTypes: string | null
}

export type FeedConfigCountAggregateOutputType = {
  id: number
  userId: number
  includeResponseTypes: number
  includeDraftStatus: number
  includeAppointmentTypes: number
  _all: number
}


export type FeedConfigMinAggregateInputType = {
  id?: true
  userId?: true
  includeResponseTypes?: true
  includeDraftStatus?: true
  includeAppointmentTypes?: true
}

export type FeedConfigMaxAggregateInputType = {
  id?: true
  userId?: true
  includeResponseTypes?: true
  includeDraftStatus?: true
  includeAppointmentTypes?: true
}

export type FeedConfigCountAggregateInputType = {
  id?: true
  userId?: true
  includeResponseTypes?: true
  includeDraftStatus?: true
  includeAppointmentTypes?: true
  _all?: true
}

export type FeedConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FeedConfig to aggregate.
   */
  where?: Prisma.FeedConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedConfigs to fetch.
   */
  orderBy?: Prisma.FeedConfigOrderByWithRelationInput | Prisma.FeedConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FeedConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FeedConfigs
  **/
  _count?: true | FeedConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FeedConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FeedConfigMaxAggregateInputType
}

export type GetFeedConfigAggregateType<T extends FeedConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateFeedConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFeedConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateFeedConfig[P]>
}




export type FeedConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FeedConfigWhereInput
  orderBy?: Prisma.FeedConfigOrderByWithAggregationInput | Prisma.FeedConfigOrderByWithAggregationInput[]
  by: Prisma.FeedConfigScalarFieldEnum[] | Prisma.FeedConfigScalarFieldEnum
  having?: Prisma.FeedConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FeedConfigCountAggregateInputType | true
  _min?: FeedConfigMinAggregateInputType
  _max?: FeedConfigMaxAggregateInputType
}

export type FeedConfigGroupByOutputType = {
  id: string
  userId: string
  includeResponseTypes: string | null
  includeDraftStatus: boolean
  includeAppointmentTypes: string | null
  _count: FeedConfigCountAggregateOutputType | null
  _min: FeedConfigMinAggregateOutputType | null
  _max: FeedConfigMaxAggregateOutputType | null
}

type GetFeedConfigGroupByPayload<T extends FeedConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FeedConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FeedConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FeedConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FeedConfigGroupByOutputType[P]>
      }
    >
  >



export type FeedConfigWhereInput = {
  AND?: Prisma.FeedConfigWhereInput | Prisma.FeedConfigWhereInput[]
  OR?: Prisma.FeedConfigWhereInput[]
  NOT?: Prisma.FeedConfigWhereInput | Prisma.FeedConfigWhereInput[]
  id?: Prisma.StringFilter<"FeedConfig"> | string
  userId?: Prisma.StringFilter<"FeedConfig"> | string
  includeResponseTypes?: Prisma.StringNullableFilter<"FeedConfig"> | string | null
  includeDraftStatus?: Prisma.BoolFilter<"FeedConfig"> | boolean
  includeAppointmentTypes?: Prisma.StringNullableFilter<"FeedConfig"> | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type FeedConfigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  includeResponseTypes?: Prisma.SortOrderInput | Prisma.SortOrder
  includeDraftStatus?: Prisma.SortOrder
  includeAppointmentTypes?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type FeedConfigWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.FeedConfigWhereInput | Prisma.FeedConfigWhereInput[]
  OR?: Prisma.FeedConfigWhereInput[]
  NOT?: Prisma.FeedConfigWhereInput | Prisma.FeedConfigWhereInput[]
  includeResponseTypes?: Prisma.StringNullableFilter<"FeedConfig"> | string | null
  includeDraftStatus?: Prisma.BoolFilter<"FeedConfig"> | boolean
  includeAppointmentTypes?: Prisma.StringNullableFilter<"FeedConfig"> | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId">

export type FeedConfigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  includeResponseTypes?: Prisma.SortOrderInput | Prisma.SortOrder
  includeDraftStatus?: Prisma.SortOrder
  includeAppointmentTypes?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.FeedConfigCountOrderByAggregateInput
  _max?: Prisma.FeedConfigMaxOrderByAggregateInput
  _min?: Prisma.FeedConfigMinOrderByAggregateInput
}

export type FeedConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.FeedConfigScalarWhereWithAggregatesInput | Prisma.FeedConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.FeedConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FeedConfigScalarWhereWithAggregatesInput | Prisma.FeedConfigScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FeedConfig"> | string
  userId?: Prisma.StringWithAggregatesFilter<"FeedConfig"> | string
  includeResponseTypes?: Prisma.StringNullableWithAggregatesFilter<"FeedConfig"> | string | null
  includeDraftStatus?: Prisma.BoolWithAggregatesFilter<"FeedConfig"> | boolean
  includeAppointmentTypes?: Prisma.StringNullableWithAggregatesFilter<"FeedConfig"> | string | null
}

export type FeedConfigCreateInput = {
  id?: string
  includeResponseTypes?: string | null
  includeDraftStatus?: boolean
  includeAppointmentTypes?: string | null
  user: Prisma.UserCreateNestedOneWithoutFeedConfigInput
}

export type FeedConfigUncheckedCreateInput = {
  id?: string
  userId: string
  includeResponseTypes?: string | null
  includeDraftStatus?: boolean
  includeAppointmentTypes?: string | null
}

export type FeedConfigUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  includeResponseTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  includeDraftStatus?: Prisma.BoolFieldUpdateOperationsInput | boolean
  includeAppointmentTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutFeedConfigNestedInput
}

export type FeedConfigUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  includeResponseTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  includeDraftStatus?: Prisma.BoolFieldUpdateOperationsInput | boolean
  includeAppointmentTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FeedConfigCreateManyInput = {
  id?: string
  userId: string
  includeResponseTypes?: string | null
  includeDraftStatus?: boolean
  includeAppointmentTypes?: string | null
}

export type FeedConfigUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  includeResponseTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  includeDraftStatus?: Prisma.BoolFieldUpdateOperationsInput | boolean
  includeAppointmentTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FeedConfigUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  includeResponseTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  includeDraftStatus?: Prisma.BoolFieldUpdateOperationsInput | boolean
  includeAppointmentTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FeedConfigNullableScalarRelationFilter = {
  is?: Prisma.FeedConfigWhereInput | null
  isNot?: Prisma.FeedConfigWhereInput | null
}

export type FeedConfigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  includeResponseTypes?: Prisma.SortOrder
  includeDraftStatus?: Prisma.SortOrder
  includeAppointmentTypes?: Prisma.SortOrder
}

export type FeedConfigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  includeResponseTypes?: Prisma.SortOrder
  includeDraftStatus?: Prisma.SortOrder
  includeAppointmentTypes?: Prisma.SortOrder
}

export type FeedConfigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  includeResponseTypes?: Prisma.SortOrder
  includeDraftStatus?: Prisma.SortOrder
  includeAppointmentTypes?: Prisma.SortOrder
}

export type FeedConfigCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FeedConfigCreateWithoutUserInput, Prisma.FeedConfigUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.FeedConfigCreateOrConnectWithoutUserInput
  connect?: Prisma.FeedConfigWhereUniqueInput
}

export type FeedConfigUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FeedConfigCreateWithoutUserInput, Prisma.FeedConfigUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.FeedConfigCreateOrConnectWithoutUserInput
  connect?: Prisma.FeedConfigWhereUniqueInput
}

export type FeedConfigUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FeedConfigCreateWithoutUserInput, Prisma.FeedConfigUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.FeedConfigCreateOrConnectWithoutUserInput
  upsert?: Prisma.FeedConfigUpsertWithoutUserInput
  disconnect?: Prisma.FeedConfigWhereInput | boolean
  delete?: Prisma.FeedConfigWhereInput | boolean
  connect?: Prisma.FeedConfigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FeedConfigUpdateToOneWithWhereWithoutUserInput, Prisma.FeedConfigUpdateWithoutUserInput>, Prisma.FeedConfigUncheckedUpdateWithoutUserInput>
}

export type FeedConfigUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FeedConfigCreateWithoutUserInput, Prisma.FeedConfigUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.FeedConfigCreateOrConnectWithoutUserInput
  upsert?: Prisma.FeedConfigUpsertWithoutUserInput
  disconnect?: Prisma.FeedConfigWhereInput | boolean
  delete?: Prisma.FeedConfigWhereInput | boolean
  connect?: Prisma.FeedConfigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FeedConfigUpdateToOneWithWhereWithoutUserInput, Prisma.FeedConfigUpdateWithoutUserInput>, Prisma.FeedConfigUncheckedUpdateWithoutUserInput>
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type FeedConfigCreateWithoutUserInput = {
  id?: string
  includeResponseTypes?: string | null
  includeDraftStatus?: boolean
  includeAppointmentTypes?: string | null
}

export type FeedConfigUncheckedCreateWithoutUserInput = {
  id?: string
  includeResponseTypes?: string | null
  includeDraftStatus?: boolean
  includeAppointmentTypes?: string | null
}

export type FeedConfigCreateOrConnectWithoutUserInput = {
  where: Prisma.FeedConfigWhereUniqueInput
  create: Prisma.XOR<Prisma.FeedConfigCreateWithoutUserInput, Prisma.FeedConfigUncheckedCreateWithoutUserInput>
}

export type FeedConfigUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.FeedConfigUpdateWithoutUserInput, Prisma.FeedConfigUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.FeedConfigCreateWithoutUserInput, Prisma.FeedConfigUncheckedCreateWithoutUserInput>
  where?: Prisma.FeedConfigWhereInput
}

export type FeedConfigUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.FeedConfigWhereInput
  data: Prisma.XOR<Prisma.FeedConfigUpdateWithoutUserInput, Prisma.FeedConfigUncheckedUpdateWithoutUserInput>
}

export type FeedConfigUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  includeResponseTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  includeDraftStatus?: Prisma.BoolFieldUpdateOperationsInput | boolean
  includeAppointmentTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FeedConfigUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  includeResponseTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  includeDraftStatus?: Prisma.BoolFieldUpdateOperationsInput | boolean
  includeAppointmentTypes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type FeedConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  includeResponseTypes?: boolean
  includeDraftStatus?: boolean
  includeAppointmentTypes?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["feedConfig"]>

export type FeedConfigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  includeResponseTypes?: boolean
  includeDraftStatus?: boolean
  includeAppointmentTypes?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["feedConfig"]>

export type FeedConfigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  includeResponseTypes?: boolean
  includeDraftStatus?: boolean
  includeAppointmentTypes?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["feedConfig"]>

export type FeedConfigSelectScalar = {
  id?: boolean
  userId?: boolean
  includeResponseTypes?: boolean
  includeDraftStatus?: boolean
  includeAppointmentTypes?: boolean
}

export type FeedConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "includeResponseTypes" | "includeDraftStatus" | "includeAppointmentTypes", ExtArgs["result"]["feedConfig"]>
export type FeedConfigInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FeedConfigIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FeedConfigIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $FeedConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FeedConfig"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    includeResponseTypes: string | null
    includeDraftStatus: boolean
    includeAppointmentTypes: string | null
  }, ExtArgs["result"]["feedConfig"]>
  composites: {}
}

export type FeedConfigGetPayload<S extends boolean | null | undefined | FeedConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload, S>

export type FeedConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FeedConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FeedConfigCountAggregateInputType | true
  }

export interface FeedConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FeedConfig'], meta: { name: 'FeedConfig' } }
  /**
   * Find zero or one FeedConfig that matches the filter.
   * @param {FeedConfigFindUniqueArgs} args - Arguments to find a FeedConfig
   * @example
   * // Get one FeedConfig
   * const feedConfig = await prisma.feedConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FeedConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, FeedConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FeedConfigClient<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FeedConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FeedConfigFindUniqueOrThrowArgs} args - Arguments to find a FeedConfig
   * @example
   * // Get one FeedConfig
   * const feedConfig = await prisma.feedConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FeedConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FeedConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FeedConfigClient<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FeedConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedConfigFindFirstArgs} args - Arguments to find a FeedConfig
   * @example
   * // Get one FeedConfig
   * const feedConfig = await prisma.feedConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FeedConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, FeedConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__FeedConfigClient<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FeedConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedConfigFindFirstOrThrowArgs} args - Arguments to find a FeedConfig
   * @example
   * // Get one FeedConfig
   * const feedConfig = await prisma.feedConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FeedConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FeedConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FeedConfigClient<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FeedConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FeedConfigs
   * const feedConfigs = await prisma.feedConfig.findMany()
   * 
   * // Get first 10 FeedConfigs
   * const feedConfigs = await prisma.feedConfig.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const feedConfigWithIdOnly = await prisma.feedConfig.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FeedConfigFindManyArgs>(args?: Prisma.SelectSubset<T, FeedConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FeedConfig.
   * @param {FeedConfigCreateArgs} args - Arguments to create a FeedConfig.
   * @example
   * // Create one FeedConfig
   * const FeedConfig = await prisma.feedConfig.create({
   *   data: {
   *     // ... data to create a FeedConfig
   *   }
   * })
   * 
   */
  create<T extends FeedConfigCreateArgs>(args: Prisma.SelectSubset<T, FeedConfigCreateArgs<ExtArgs>>): Prisma.Prisma__FeedConfigClient<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FeedConfigs.
   * @param {FeedConfigCreateManyArgs} args - Arguments to create many FeedConfigs.
   * @example
   * // Create many FeedConfigs
   * const feedConfig = await prisma.feedConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FeedConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, FeedConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FeedConfigs and returns the data saved in the database.
   * @param {FeedConfigCreateManyAndReturnArgs} args - Arguments to create many FeedConfigs.
   * @example
   * // Create many FeedConfigs
   * const feedConfig = await prisma.feedConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FeedConfigs and only return the `id`
   * const feedConfigWithIdOnly = await prisma.feedConfig.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FeedConfigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FeedConfigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FeedConfig.
   * @param {FeedConfigDeleteArgs} args - Arguments to delete one FeedConfig.
   * @example
   * // Delete one FeedConfig
   * const FeedConfig = await prisma.feedConfig.delete({
   *   where: {
   *     // ... filter to delete one FeedConfig
   *   }
   * })
   * 
   */
  delete<T extends FeedConfigDeleteArgs>(args: Prisma.SelectSubset<T, FeedConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__FeedConfigClient<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FeedConfig.
   * @param {FeedConfigUpdateArgs} args - Arguments to update one FeedConfig.
   * @example
   * // Update one FeedConfig
   * const feedConfig = await prisma.feedConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FeedConfigUpdateArgs>(args: Prisma.SelectSubset<T, FeedConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__FeedConfigClient<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FeedConfigs.
   * @param {FeedConfigDeleteManyArgs} args - Arguments to filter FeedConfigs to delete.
   * @example
   * // Delete a few FeedConfigs
   * const { count } = await prisma.feedConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FeedConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, FeedConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FeedConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FeedConfigs
   * const feedConfig = await prisma.feedConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FeedConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, FeedConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FeedConfigs and returns the data updated in the database.
   * @param {FeedConfigUpdateManyAndReturnArgs} args - Arguments to update many FeedConfigs.
   * @example
   * // Update many FeedConfigs
   * const feedConfig = await prisma.feedConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FeedConfigs and only return the `id`
   * const feedConfigWithIdOnly = await prisma.feedConfig.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FeedConfigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FeedConfigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FeedConfig.
   * @param {FeedConfigUpsertArgs} args - Arguments to update or create a FeedConfig.
   * @example
   * // Update or create a FeedConfig
   * const feedConfig = await prisma.feedConfig.upsert({
   *   create: {
   *     // ... data to create a FeedConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FeedConfig we want to update
   *   }
   * })
   */
  upsert<T extends FeedConfigUpsertArgs>(args: Prisma.SelectSubset<T, FeedConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__FeedConfigClient<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FeedConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedConfigCountArgs} args - Arguments to filter FeedConfigs to count.
   * @example
   * // Count the number of FeedConfigs
   * const count = await prisma.feedConfig.count({
   *   where: {
   *     // ... the filter for the FeedConfigs we want to count
   *   }
   * })
  **/
  count<T extends FeedConfigCountArgs>(
    args?: Prisma.Subset<T, FeedConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FeedConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FeedConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FeedConfigAggregateArgs>(args: Prisma.Subset<T, FeedConfigAggregateArgs>): Prisma.PrismaPromise<GetFeedConfigAggregateType<T>>

  /**
   * Group by FeedConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FeedConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FeedConfigGroupByArgs['orderBy'] }
      : { orderBy?: FeedConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FeedConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFeedConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FeedConfig model
 */
readonly fields: FeedConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FeedConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FeedConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FeedConfig model
 */
export interface FeedConfigFieldRefs {
  readonly id: Prisma.FieldRef<"FeedConfig", 'String'>
  readonly userId: Prisma.FieldRef<"FeedConfig", 'String'>
  readonly includeResponseTypes: Prisma.FieldRef<"FeedConfig", 'String'>
  readonly includeDraftStatus: Prisma.FieldRef<"FeedConfig", 'Boolean'>
  readonly includeAppointmentTypes: Prisma.FieldRef<"FeedConfig", 'String'>
}
    

// Custom InputTypes
/**
 * FeedConfig findUnique
 */
export type FeedConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
  /**
   * Filter, which FeedConfig to fetch.
   */
  where: Prisma.FeedConfigWhereUniqueInput
}

/**
 * FeedConfig findUniqueOrThrow
 */
export type FeedConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
  /**
   * Filter, which FeedConfig to fetch.
   */
  where: Prisma.FeedConfigWhereUniqueInput
}

/**
 * FeedConfig findFirst
 */
export type FeedConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
  /**
   * Filter, which FeedConfig to fetch.
   */
  where?: Prisma.FeedConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedConfigs to fetch.
   */
  orderBy?: Prisma.FeedConfigOrderByWithRelationInput | Prisma.FeedConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FeedConfigs.
   */
  cursor?: Prisma.FeedConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeedConfigs.
   */
  distinct?: Prisma.FeedConfigScalarFieldEnum | Prisma.FeedConfigScalarFieldEnum[]
}

/**
 * FeedConfig findFirstOrThrow
 */
export type FeedConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
  /**
   * Filter, which FeedConfig to fetch.
   */
  where?: Prisma.FeedConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedConfigs to fetch.
   */
  orderBy?: Prisma.FeedConfigOrderByWithRelationInput | Prisma.FeedConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FeedConfigs.
   */
  cursor?: Prisma.FeedConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeedConfigs.
   */
  distinct?: Prisma.FeedConfigScalarFieldEnum | Prisma.FeedConfigScalarFieldEnum[]
}

/**
 * FeedConfig findMany
 */
export type FeedConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
  /**
   * Filter, which FeedConfigs to fetch.
   */
  where?: Prisma.FeedConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedConfigs to fetch.
   */
  orderBy?: Prisma.FeedConfigOrderByWithRelationInput | Prisma.FeedConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FeedConfigs.
   */
  cursor?: Prisma.FeedConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedConfigs.
   */
  skip?: number
  distinct?: Prisma.FeedConfigScalarFieldEnum | Prisma.FeedConfigScalarFieldEnum[]
}

/**
 * FeedConfig create
 */
export type FeedConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
  /**
   * The data needed to create a FeedConfig.
   */
  data: Prisma.XOR<Prisma.FeedConfigCreateInput, Prisma.FeedConfigUncheckedCreateInput>
}

/**
 * FeedConfig createMany
 */
export type FeedConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FeedConfigs.
   */
  data: Prisma.FeedConfigCreateManyInput | Prisma.FeedConfigCreateManyInput[]
}

/**
 * FeedConfig createManyAndReturn
 */
export type FeedConfigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * The data used to create many FeedConfigs.
   */
  data: Prisma.FeedConfigCreateManyInput | Prisma.FeedConfigCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FeedConfig update
 */
export type FeedConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
  /**
   * The data needed to update a FeedConfig.
   */
  data: Prisma.XOR<Prisma.FeedConfigUpdateInput, Prisma.FeedConfigUncheckedUpdateInput>
  /**
   * Choose, which FeedConfig to update.
   */
  where: Prisma.FeedConfigWhereUniqueInput
}

/**
 * FeedConfig updateMany
 */
export type FeedConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FeedConfigs.
   */
  data: Prisma.XOR<Prisma.FeedConfigUpdateManyMutationInput, Prisma.FeedConfigUncheckedUpdateManyInput>
  /**
   * Filter which FeedConfigs to update
   */
  where?: Prisma.FeedConfigWhereInput
  /**
   * Limit how many FeedConfigs to update.
   */
  limit?: number
}

/**
 * FeedConfig updateManyAndReturn
 */
export type FeedConfigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * The data used to update FeedConfigs.
   */
  data: Prisma.XOR<Prisma.FeedConfigUpdateManyMutationInput, Prisma.FeedConfigUncheckedUpdateManyInput>
  /**
   * Filter which FeedConfigs to update
   */
  where?: Prisma.FeedConfigWhereInput
  /**
   * Limit how many FeedConfigs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FeedConfig upsert
 */
export type FeedConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
  /**
   * The filter to search for the FeedConfig to update in case it exists.
   */
  where: Prisma.FeedConfigWhereUniqueInput
  /**
   * In case the FeedConfig found by the `where` argument doesn't exist, create a new FeedConfig with this data.
   */
  create: Prisma.XOR<Prisma.FeedConfigCreateInput, Prisma.FeedConfigUncheckedCreateInput>
  /**
   * In case the FeedConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FeedConfigUpdateInput, Prisma.FeedConfigUncheckedUpdateInput>
}

/**
 * FeedConfig delete
 */
export type FeedConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
  /**
   * Filter which FeedConfig to delete.
   */
  where: Prisma.FeedConfigWhereUniqueInput
}

/**
 * FeedConfig deleteMany
 */
export type FeedConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FeedConfigs to delete
   */
  where?: Prisma.FeedConfigWhereInput
  /**
   * Limit how many FeedConfigs to delete.
   */
  limit?: number
}

/**
 * FeedConfig without action
 */
export type FeedConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
}
