
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ImporterSetting` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ImporterSetting
 * 
 */
export type ImporterSettingModel = runtime.Types.Result.DefaultSelection<Prisma.$ImporterSettingPayload>

export type AggregateImporterSetting = {
  _count: ImporterSettingCountAggregateOutputType | null
  _min: ImporterSettingMinAggregateOutputType | null
  _max: ImporterSettingMaxAggregateOutputType | null
}

export type ImporterSettingMinAggregateOutputType = {
  importerId: string | null
  enabled: boolean | null
}

export type ImporterSettingMaxAggregateOutputType = {
  importerId: string | null
  enabled: boolean | null
}

export type ImporterSettingCountAggregateOutputType = {
  importerId: number
  enabled: number
  _all: number
}


export type ImporterSettingMinAggregateInputType = {
  importerId?: true
  enabled?: true
}

export type ImporterSettingMaxAggregateInputType = {
  importerId?: true
  enabled?: true
}

export type ImporterSettingCountAggregateInputType = {
  importerId?: true
  enabled?: true
  _all?: true
}

export type ImporterSettingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ImporterSetting to aggregate.
   */
  where?: Prisma.ImporterSettingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImporterSettings to fetch.
   */
  orderBy?: Prisma.ImporterSettingOrderByWithRelationInput | Prisma.ImporterSettingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ImporterSettingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImporterSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImporterSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ImporterSettings
  **/
  _count?: true | ImporterSettingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ImporterSettingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ImporterSettingMaxAggregateInputType
}

export type GetImporterSettingAggregateType<T extends ImporterSettingAggregateArgs> = {
      [P in keyof T & keyof AggregateImporterSetting]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateImporterSetting[P]>
    : Prisma.GetScalarType<T[P], AggregateImporterSetting[P]>
}




export type ImporterSettingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ImporterSettingWhereInput
  orderBy?: Prisma.ImporterSettingOrderByWithAggregationInput | Prisma.ImporterSettingOrderByWithAggregationInput[]
  by: Prisma.ImporterSettingScalarFieldEnum[] | Prisma.ImporterSettingScalarFieldEnum
  having?: Prisma.ImporterSettingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ImporterSettingCountAggregateInputType | true
  _min?: ImporterSettingMinAggregateInputType
  _max?: ImporterSettingMaxAggregateInputType
}

export type ImporterSettingGroupByOutputType = {
  importerId: string
  enabled: boolean
  _count: ImporterSettingCountAggregateOutputType | null
  _min: ImporterSettingMinAggregateOutputType | null
  _max: ImporterSettingMaxAggregateOutputType | null
}

export type GetImporterSettingGroupByPayload<T extends ImporterSettingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ImporterSettingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ImporterSettingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ImporterSettingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ImporterSettingGroupByOutputType[P]>
      }
    >
  >



export type ImporterSettingWhereInput = {
  AND?: Prisma.ImporterSettingWhereInput | Prisma.ImporterSettingWhereInput[]
  OR?: Prisma.ImporterSettingWhereInput[]
  NOT?: Prisma.ImporterSettingWhereInput | Prisma.ImporterSettingWhereInput[]
  importerId?: Prisma.StringFilter<"ImporterSetting"> | string
  enabled?: Prisma.BoolFilter<"ImporterSetting"> | boolean
}

export type ImporterSettingOrderByWithRelationInput = {
  importerId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}

export type ImporterSettingWhereUniqueInput = Prisma.AtLeast<{
  importerId?: string
  AND?: Prisma.ImporterSettingWhereInput | Prisma.ImporterSettingWhereInput[]
  OR?: Prisma.ImporterSettingWhereInput[]
  NOT?: Prisma.ImporterSettingWhereInput | Prisma.ImporterSettingWhereInput[]
  enabled?: Prisma.BoolFilter<"ImporterSetting"> | boolean
}, "importerId">

export type ImporterSettingOrderByWithAggregationInput = {
  importerId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  _count?: Prisma.ImporterSettingCountOrderByAggregateInput
  _max?: Prisma.ImporterSettingMaxOrderByAggregateInput
  _min?: Prisma.ImporterSettingMinOrderByAggregateInput
}

export type ImporterSettingScalarWhereWithAggregatesInput = {
  AND?: Prisma.ImporterSettingScalarWhereWithAggregatesInput | Prisma.ImporterSettingScalarWhereWithAggregatesInput[]
  OR?: Prisma.ImporterSettingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ImporterSettingScalarWhereWithAggregatesInput | Prisma.ImporterSettingScalarWhereWithAggregatesInput[]
  importerId?: Prisma.StringWithAggregatesFilter<"ImporterSetting"> | string
  enabled?: Prisma.BoolWithAggregatesFilter<"ImporterSetting"> | boolean
}

export type ImporterSettingCreateInput = {
  importerId: string
  enabled?: boolean
}

export type ImporterSettingUncheckedCreateInput = {
  importerId: string
  enabled?: boolean
}

export type ImporterSettingUpdateInput = {
  importerId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ImporterSettingUncheckedUpdateInput = {
  importerId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ImporterSettingCreateManyInput = {
  importerId: string
  enabled?: boolean
}

export type ImporterSettingUpdateManyMutationInput = {
  importerId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ImporterSettingUncheckedUpdateManyInput = {
  importerId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ImporterSettingCountOrderByAggregateInput = {
  importerId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}

export type ImporterSettingMaxOrderByAggregateInput = {
  importerId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}

export type ImporterSettingMinOrderByAggregateInput = {
  importerId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}



export type ImporterSettingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  importerId?: boolean
  enabled?: boolean
}, ExtArgs["result"]["importerSetting"]>

export type ImporterSettingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  importerId?: boolean
  enabled?: boolean
}, ExtArgs["result"]["importerSetting"]>

export type ImporterSettingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  importerId?: boolean
  enabled?: boolean
}, ExtArgs["result"]["importerSetting"]>

export type ImporterSettingSelectScalar = {
  importerId?: boolean
  enabled?: boolean
}

export type ImporterSettingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"importerId" | "enabled", ExtArgs["result"]["importerSetting"]>

export type $ImporterSettingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ImporterSetting"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    importerId: string
    enabled: boolean
  }, ExtArgs["result"]["importerSetting"]>
  composites: {}
}

export type ImporterSettingGetPayload<S extends boolean | null | undefined | ImporterSettingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload, S>

export type ImporterSettingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ImporterSettingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ImporterSettingCountAggregateInputType | true
  }

export interface ImporterSettingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ImporterSetting'], meta: { name: 'ImporterSetting' } }
  /**
   * Find zero or one ImporterSetting that matches the filter.
   * @param {ImporterSettingFindUniqueArgs} args - Arguments to find a ImporterSetting
   * @example
   * // Get one ImporterSetting
   * const importerSetting = await prisma.importerSetting.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ImporterSettingFindUniqueArgs>(args: Prisma.SelectSubset<T, ImporterSettingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ImporterSettingClient<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ImporterSetting that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ImporterSettingFindUniqueOrThrowArgs} args - Arguments to find a ImporterSetting
   * @example
   * // Get one ImporterSetting
   * const importerSetting = await prisma.importerSetting.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ImporterSettingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ImporterSettingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ImporterSettingClient<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ImporterSetting that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImporterSettingFindFirstArgs} args - Arguments to find a ImporterSetting
   * @example
   * // Get one ImporterSetting
   * const importerSetting = await prisma.importerSetting.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ImporterSettingFindFirstArgs>(args?: Prisma.SelectSubset<T, ImporterSettingFindFirstArgs<ExtArgs>>): Prisma.Prisma__ImporterSettingClient<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ImporterSetting that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImporterSettingFindFirstOrThrowArgs} args - Arguments to find a ImporterSetting
   * @example
   * // Get one ImporterSetting
   * const importerSetting = await prisma.importerSetting.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ImporterSettingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ImporterSettingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ImporterSettingClient<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ImporterSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImporterSettingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ImporterSettings
   * const importerSettings = await prisma.importerSetting.findMany()
   * 
   * // Get first 10 ImporterSettings
   * const importerSettings = await prisma.importerSetting.findMany({ take: 10 })
   * 
   * // Only select the `importerId`
   * const importerSettingWithImporterIdOnly = await prisma.importerSetting.findMany({ select: { importerId: true } })
   * 
   */
  findMany<T extends ImporterSettingFindManyArgs>(args?: Prisma.SelectSubset<T, ImporterSettingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ImporterSetting.
   * @param {ImporterSettingCreateArgs} args - Arguments to create a ImporterSetting.
   * @example
   * // Create one ImporterSetting
   * const ImporterSetting = await prisma.importerSetting.create({
   *   data: {
   *     // ... data to create a ImporterSetting
   *   }
   * })
   * 
   */
  create<T extends ImporterSettingCreateArgs>(args: Prisma.SelectSubset<T, ImporterSettingCreateArgs<ExtArgs>>): Prisma.Prisma__ImporterSettingClient<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ImporterSettings.
   * @param {ImporterSettingCreateManyArgs} args - Arguments to create many ImporterSettings.
   * @example
   * // Create many ImporterSettings
   * const importerSetting = await prisma.importerSetting.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ImporterSettingCreateManyArgs>(args?: Prisma.SelectSubset<T, ImporterSettingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ImporterSettings and returns the data saved in the database.
   * @param {ImporterSettingCreateManyAndReturnArgs} args - Arguments to create many ImporterSettings.
   * @example
   * // Create many ImporterSettings
   * const importerSetting = await prisma.importerSetting.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ImporterSettings and only return the `importerId`
   * const importerSettingWithImporterIdOnly = await prisma.importerSetting.createManyAndReturn({
   *   select: { importerId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ImporterSettingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ImporterSettingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ImporterSetting.
   * @param {ImporterSettingDeleteArgs} args - Arguments to delete one ImporterSetting.
   * @example
   * // Delete one ImporterSetting
   * const ImporterSetting = await prisma.importerSetting.delete({
   *   where: {
   *     // ... filter to delete one ImporterSetting
   *   }
   * })
   * 
   */
  delete<T extends ImporterSettingDeleteArgs>(args: Prisma.SelectSubset<T, ImporterSettingDeleteArgs<ExtArgs>>): Prisma.Prisma__ImporterSettingClient<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ImporterSetting.
   * @param {ImporterSettingUpdateArgs} args - Arguments to update one ImporterSetting.
   * @example
   * // Update one ImporterSetting
   * const importerSetting = await prisma.importerSetting.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ImporterSettingUpdateArgs>(args: Prisma.SelectSubset<T, ImporterSettingUpdateArgs<ExtArgs>>): Prisma.Prisma__ImporterSettingClient<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ImporterSettings.
   * @param {ImporterSettingDeleteManyArgs} args - Arguments to filter ImporterSettings to delete.
   * @example
   * // Delete a few ImporterSettings
   * const { count } = await prisma.importerSetting.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ImporterSettingDeleteManyArgs>(args?: Prisma.SelectSubset<T, ImporterSettingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ImporterSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImporterSettingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ImporterSettings
   * const importerSetting = await prisma.importerSetting.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ImporterSettingUpdateManyArgs>(args: Prisma.SelectSubset<T, ImporterSettingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ImporterSettings and returns the data updated in the database.
   * @param {ImporterSettingUpdateManyAndReturnArgs} args - Arguments to update many ImporterSettings.
   * @example
   * // Update many ImporterSettings
   * const importerSetting = await prisma.importerSetting.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ImporterSettings and only return the `importerId`
   * const importerSettingWithImporterIdOnly = await prisma.importerSetting.updateManyAndReturn({
   *   select: { importerId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ImporterSettingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ImporterSettingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ImporterSetting.
   * @param {ImporterSettingUpsertArgs} args - Arguments to update or create a ImporterSetting.
   * @example
   * // Update or create a ImporterSetting
   * const importerSetting = await prisma.importerSetting.upsert({
   *   create: {
   *     // ... data to create a ImporterSetting
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ImporterSetting we want to update
   *   }
   * })
   */
  upsert<T extends ImporterSettingUpsertArgs>(args: Prisma.SelectSubset<T, ImporterSettingUpsertArgs<ExtArgs>>): Prisma.Prisma__ImporterSettingClient<runtime.Types.Result.GetResult<Prisma.$ImporterSettingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ImporterSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImporterSettingCountArgs} args - Arguments to filter ImporterSettings to count.
   * @example
   * // Count the number of ImporterSettings
   * const count = await prisma.importerSetting.count({
   *   where: {
   *     // ... the filter for the ImporterSettings we want to count
   *   }
   * })
  **/
  count<T extends ImporterSettingCountArgs>(
    args?: Prisma.Subset<T, ImporterSettingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ImporterSettingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ImporterSetting.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImporterSettingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ImporterSettingAggregateArgs>(args: Prisma.Subset<T, ImporterSettingAggregateArgs>): Prisma.PrismaPromise<GetImporterSettingAggregateType<T>>

  /**
   * Group by ImporterSetting.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImporterSettingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ImporterSettingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ImporterSettingGroupByArgs['orderBy'] }
      : { orderBy?: ImporterSettingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ImporterSettingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetImporterSettingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ImporterSetting model
 */
readonly fields: ImporterSettingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ImporterSetting.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ImporterSettingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ImporterSetting model
 */
export interface ImporterSettingFieldRefs {
  readonly importerId: Prisma.FieldRef<"ImporterSetting", 'String'>
  readonly enabled: Prisma.FieldRef<"ImporterSetting", 'Boolean'>
}
    

// Custom InputTypes
/**
 * ImporterSetting findUnique
 */
export type ImporterSettingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * Filter, which ImporterSetting to fetch.
   */
  where: Prisma.ImporterSettingWhereUniqueInput
}

/**
 * ImporterSetting findUniqueOrThrow
 */
export type ImporterSettingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * Filter, which ImporterSetting to fetch.
   */
  where: Prisma.ImporterSettingWhereUniqueInput
}

/**
 * ImporterSetting findFirst
 */
export type ImporterSettingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * Filter, which ImporterSetting to fetch.
   */
  where?: Prisma.ImporterSettingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImporterSettings to fetch.
   */
  orderBy?: Prisma.ImporterSettingOrderByWithRelationInput | Prisma.ImporterSettingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ImporterSettings.
   */
  cursor?: Prisma.ImporterSettingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImporterSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImporterSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ImporterSettings.
   */
  distinct?: Prisma.ImporterSettingScalarFieldEnum | Prisma.ImporterSettingScalarFieldEnum[]
}

/**
 * ImporterSetting findFirstOrThrow
 */
export type ImporterSettingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * Filter, which ImporterSetting to fetch.
   */
  where?: Prisma.ImporterSettingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImporterSettings to fetch.
   */
  orderBy?: Prisma.ImporterSettingOrderByWithRelationInput | Prisma.ImporterSettingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ImporterSettings.
   */
  cursor?: Prisma.ImporterSettingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImporterSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImporterSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ImporterSettings.
   */
  distinct?: Prisma.ImporterSettingScalarFieldEnum | Prisma.ImporterSettingScalarFieldEnum[]
}

/**
 * ImporterSetting findMany
 */
export type ImporterSettingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * Filter, which ImporterSettings to fetch.
   */
  where?: Prisma.ImporterSettingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImporterSettings to fetch.
   */
  orderBy?: Prisma.ImporterSettingOrderByWithRelationInput | Prisma.ImporterSettingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ImporterSettings.
   */
  cursor?: Prisma.ImporterSettingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImporterSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImporterSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ImporterSettings.
   */
  distinct?: Prisma.ImporterSettingScalarFieldEnum | Prisma.ImporterSettingScalarFieldEnum[]
}

/**
 * ImporterSetting create
 */
export type ImporterSettingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * The data needed to create a ImporterSetting.
   */
  data: Prisma.XOR<Prisma.ImporterSettingCreateInput, Prisma.ImporterSettingUncheckedCreateInput>
}

/**
 * ImporterSetting createMany
 */
export type ImporterSettingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ImporterSettings.
   */
  data: Prisma.ImporterSettingCreateManyInput | Prisma.ImporterSettingCreateManyInput[]
}

/**
 * ImporterSetting createManyAndReturn
 */
export type ImporterSettingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * The data used to create many ImporterSettings.
   */
  data: Prisma.ImporterSettingCreateManyInput | Prisma.ImporterSettingCreateManyInput[]
}

/**
 * ImporterSetting update
 */
export type ImporterSettingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * The data needed to update a ImporterSetting.
   */
  data: Prisma.XOR<Prisma.ImporterSettingUpdateInput, Prisma.ImporterSettingUncheckedUpdateInput>
  /**
   * Choose, which ImporterSetting to update.
   */
  where: Prisma.ImporterSettingWhereUniqueInput
}

/**
 * ImporterSetting updateMany
 */
export type ImporterSettingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ImporterSettings.
   */
  data: Prisma.XOR<Prisma.ImporterSettingUpdateManyMutationInput, Prisma.ImporterSettingUncheckedUpdateManyInput>
  /**
   * Filter which ImporterSettings to update
   */
  where?: Prisma.ImporterSettingWhereInput
  /**
   * Limit how many ImporterSettings to update.
   */
  limit?: number
}

/**
 * ImporterSetting updateManyAndReturn
 */
export type ImporterSettingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * The data used to update ImporterSettings.
   */
  data: Prisma.XOR<Prisma.ImporterSettingUpdateManyMutationInput, Prisma.ImporterSettingUncheckedUpdateManyInput>
  /**
   * Filter which ImporterSettings to update
   */
  where?: Prisma.ImporterSettingWhereInput
  /**
   * Limit how many ImporterSettings to update.
   */
  limit?: number
}

/**
 * ImporterSetting upsert
 */
export type ImporterSettingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * The filter to search for the ImporterSetting to update in case it exists.
   */
  where: Prisma.ImporterSettingWhereUniqueInput
  /**
   * In case the ImporterSetting found by the `where` argument doesn't exist, create a new ImporterSetting with this data.
   */
  create: Prisma.XOR<Prisma.ImporterSettingCreateInput, Prisma.ImporterSettingUncheckedCreateInput>
  /**
   * In case the ImporterSetting was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ImporterSettingUpdateInput, Prisma.ImporterSettingUncheckedUpdateInput>
}

/**
 * ImporterSetting delete
 */
export type ImporterSettingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
  /**
   * Filter which ImporterSetting to delete.
   */
  where: Prisma.ImporterSettingWhereUniqueInput
}

/**
 * ImporterSetting deleteMany
 */
export type ImporterSettingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ImporterSettings to delete
   */
  where?: Prisma.ImporterSettingWhereInput
  /**
   * Limit how many ImporterSettings to delete.
   */
  limit?: number
}

/**
 * ImporterSetting without action
 */
export type ImporterSettingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImporterSetting
   */
  select?: Prisma.ImporterSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImporterSetting
   */
  omit?: Prisma.ImporterSettingOmit<ExtArgs> | null
}
