
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Season` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Season
 * 
 */
export type SeasonModel = runtime.Types.Result.DefaultSelection<Prisma.$SeasonPayload>

export type AggregateSeason = {
  _count: SeasonCountAggregateOutputType | null
  _min: SeasonMinAggregateOutputType | null
  _max: SeasonMaxAggregateOutputType | null
}

export type SeasonMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  name: string | null
  isActive: boolean | null
}

export type SeasonMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  name: string | null
  isActive: boolean | null
}

export type SeasonCountAggregateOutputType = {
  id: number
  createdAt: number
  name: number
  isActive: number
  _all: number
}


export type SeasonMinAggregateInputType = {
  id?: true
  createdAt?: true
  name?: true
  isActive?: true
}

export type SeasonMaxAggregateInputType = {
  id?: true
  createdAt?: true
  name?: true
  isActive?: true
}

export type SeasonCountAggregateInputType = {
  id?: true
  createdAt?: true
  name?: true
  isActive?: true
  _all?: true
}

export type SeasonAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Season to aggregate.
   */
  where?: Prisma.SeasonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seasons to fetch.
   */
  orderBy?: Prisma.SeasonOrderByWithRelationInput | Prisma.SeasonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SeasonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seasons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seasons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Seasons
  **/
  _count?: true | SeasonCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SeasonMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SeasonMaxAggregateInputType
}

export type GetSeasonAggregateType<T extends SeasonAggregateArgs> = {
      [P in keyof T & keyof AggregateSeason]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSeason[P]>
    : Prisma.GetScalarType<T[P], AggregateSeason[P]>
}




export type SeasonGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SeasonWhereInput
  orderBy?: Prisma.SeasonOrderByWithAggregationInput | Prisma.SeasonOrderByWithAggregationInput[]
  by: Prisma.SeasonScalarFieldEnum[] | Prisma.SeasonScalarFieldEnum
  having?: Prisma.SeasonScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SeasonCountAggregateInputType | true
  _min?: SeasonMinAggregateInputType
  _max?: SeasonMaxAggregateInputType
}

export type SeasonGroupByOutputType = {
  id: string
  createdAt: Date
  name: string
  isActive: boolean
  _count: SeasonCountAggregateOutputType | null
  _min: SeasonMinAggregateOutputType | null
  _max: SeasonMaxAggregateOutputType | null
}

export type GetSeasonGroupByPayload<T extends SeasonGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SeasonGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SeasonGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SeasonGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SeasonGroupByOutputType[P]>
      }
    >
  >



export type SeasonWhereInput = {
  AND?: Prisma.SeasonWhereInput | Prisma.SeasonWhereInput[]
  OR?: Prisma.SeasonWhereInput[]
  NOT?: Prisma.SeasonWhereInput | Prisma.SeasonWhereInput[]
  id?: Prisma.StringFilter<"Season"> | string
  createdAt?: Prisma.DateTimeFilter<"Season"> | Date | string
  name?: Prisma.StringFilter<"Season"> | string
  isActive?: Prisma.BoolFilter<"Season"> | boolean
  teams?: Prisma.TeamListRelationFilter
  appointments?: Prisma.AppointmentListRelationFilter
}

export type SeasonOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  teams?: Prisma.TeamOrderByRelationAggregateInput
  appointments?: Prisma.AppointmentOrderByRelationAggregateInput
}

export type SeasonWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SeasonWhereInput | Prisma.SeasonWhereInput[]
  OR?: Prisma.SeasonWhereInput[]
  NOT?: Prisma.SeasonWhereInput | Prisma.SeasonWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Season"> | Date | string
  name?: Prisma.StringFilter<"Season"> | string
  isActive?: Prisma.BoolFilter<"Season"> | boolean
  teams?: Prisma.TeamListRelationFilter
  appointments?: Prisma.AppointmentListRelationFilter
}, "id">

export type SeasonOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  _count?: Prisma.SeasonCountOrderByAggregateInput
  _max?: Prisma.SeasonMaxOrderByAggregateInput
  _min?: Prisma.SeasonMinOrderByAggregateInput
}

export type SeasonScalarWhereWithAggregatesInput = {
  AND?: Prisma.SeasonScalarWhereWithAggregatesInput | Prisma.SeasonScalarWhereWithAggregatesInput[]
  OR?: Prisma.SeasonScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SeasonScalarWhereWithAggregatesInput | Prisma.SeasonScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Season"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Season"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"Season"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"Season"> | boolean
}

export type SeasonCreateInput = {
  id?: string
  createdAt?: Date | string
  name: string
  isActive?: boolean
  teams?: Prisma.TeamCreateNestedManyWithoutSeasonInput
  appointments?: Prisma.AppointmentCreateNestedManyWithoutSeasonInput
}

export type SeasonUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  name: string
  isActive?: boolean
  teams?: Prisma.TeamUncheckedCreateNestedManyWithoutSeasonInput
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutSeasonInput
}

export type SeasonUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  teams?: Prisma.TeamUpdateManyWithoutSeasonNestedInput
  appointments?: Prisma.AppointmentUpdateManyWithoutSeasonNestedInput
}

export type SeasonUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  teams?: Prisma.TeamUncheckedUpdateManyWithoutSeasonNestedInput
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutSeasonNestedInput
}

export type SeasonCreateManyInput = {
  id?: string
  createdAt?: Date | string
  name: string
  isActive?: boolean
}

export type SeasonUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SeasonUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SeasonNullableScalarRelationFilter = {
  is?: Prisma.SeasonWhereInput | null
  isNot?: Prisma.SeasonWhereInput | null
}

export type SeasonCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type SeasonMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type SeasonMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type SeasonCreateNestedOneWithoutAppointmentsInput = {
  create?: Prisma.XOR<Prisma.SeasonCreateWithoutAppointmentsInput, Prisma.SeasonUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.SeasonCreateOrConnectWithoutAppointmentsInput
  connect?: Prisma.SeasonWhereUniqueInput
}

export type SeasonUpdateOneWithoutAppointmentsNestedInput = {
  create?: Prisma.XOR<Prisma.SeasonCreateWithoutAppointmentsInput, Prisma.SeasonUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.SeasonCreateOrConnectWithoutAppointmentsInput
  upsert?: Prisma.SeasonUpsertWithoutAppointmentsInput
  disconnect?: Prisma.SeasonWhereInput | boolean
  delete?: Prisma.SeasonWhereInput | boolean
  connect?: Prisma.SeasonWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SeasonUpdateToOneWithWhereWithoutAppointmentsInput, Prisma.SeasonUpdateWithoutAppointmentsInput>, Prisma.SeasonUncheckedUpdateWithoutAppointmentsInput>
}

export type SeasonCreateNestedOneWithoutTeamsInput = {
  create?: Prisma.XOR<Prisma.SeasonCreateWithoutTeamsInput, Prisma.SeasonUncheckedCreateWithoutTeamsInput>
  connectOrCreate?: Prisma.SeasonCreateOrConnectWithoutTeamsInput
  connect?: Prisma.SeasonWhereUniqueInput
}

export type SeasonUpdateOneWithoutTeamsNestedInput = {
  create?: Prisma.XOR<Prisma.SeasonCreateWithoutTeamsInput, Prisma.SeasonUncheckedCreateWithoutTeamsInput>
  connectOrCreate?: Prisma.SeasonCreateOrConnectWithoutTeamsInput
  upsert?: Prisma.SeasonUpsertWithoutTeamsInput
  disconnect?: Prisma.SeasonWhereInput | boolean
  delete?: Prisma.SeasonWhereInput | boolean
  connect?: Prisma.SeasonWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SeasonUpdateToOneWithWhereWithoutTeamsInput, Prisma.SeasonUpdateWithoutTeamsInput>, Prisma.SeasonUncheckedUpdateWithoutTeamsInput>
}

export type SeasonCreateWithoutAppointmentsInput = {
  id?: string
  createdAt?: Date | string
  name: string
  isActive?: boolean
  teams?: Prisma.TeamCreateNestedManyWithoutSeasonInput
}

export type SeasonUncheckedCreateWithoutAppointmentsInput = {
  id?: string
  createdAt?: Date | string
  name: string
  isActive?: boolean
  teams?: Prisma.TeamUncheckedCreateNestedManyWithoutSeasonInput
}

export type SeasonCreateOrConnectWithoutAppointmentsInput = {
  where: Prisma.SeasonWhereUniqueInput
  create: Prisma.XOR<Prisma.SeasonCreateWithoutAppointmentsInput, Prisma.SeasonUncheckedCreateWithoutAppointmentsInput>
}

export type SeasonUpsertWithoutAppointmentsInput = {
  update: Prisma.XOR<Prisma.SeasonUpdateWithoutAppointmentsInput, Prisma.SeasonUncheckedUpdateWithoutAppointmentsInput>
  create: Prisma.XOR<Prisma.SeasonCreateWithoutAppointmentsInput, Prisma.SeasonUncheckedCreateWithoutAppointmentsInput>
  where?: Prisma.SeasonWhereInput
}

export type SeasonUpdateToOneWithWhereWithoutAppointmentsInput = {
  where?: Prisma.SeasonWhereInput
  data: Prisma.XOR<Prisma.SeasonUpdateWithoutAppointmentsInput, Prisma.SeasonUncheckedUpdateWithoutAppointmentsInput>
}

export type SeasonUpdateWithoutAppointmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  teams?: Prisma.TeamUpdateManyWithoutSeasonNestedInput
}

export type SeasonUncheckedUpdateWithoutAppointmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  teams?: Prisma.TeamUncheckedUpdateManyWithoutSeasonNestedInput
}

export type SeasonCreateWithoutTeamsInput = {
  id?: string
  createdAt?: Date | string
  name: string
  isActive?: boolean
  appointments?: Prisma.AppointmentCreateNestedManyWithoutSeasonInput
}

export type SeasonUncheckedCreateWithoutTeamsInput = {
  id?: string
  createdAt?: Date | string
  name: string
  isActive?: boolean
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutSeasonInput
}

export type SeasonCreateOrConnectWithoutTeamsInput = {
  where: Prisma.SeasonWhereUniqueInput
  create: Prisma.XOR<Prisma.SeasonCreateWithoutTeamsInput, Prisma.SeasonUncheckedCreateWithoutTeamsInput>
}

export type SeasonUpsertWithoutTeamsInput = {
  update: Prisma.XOR<Prisma.SeasonUpdateWithoutTeamsInput, Prisma.SeasonUncheckedUpdateWithoutTeamsInput>
  create: Prisma.XOR<Prisma.SeasonCreateWithoutTeamsInput, Prisma.SeasonUncheckedCreateWithoutTeamsInput>
  where?: Prisma.SeasonWhereInput
}

export type SeasonUpdateToOneWithWhereWithoutTeamsInput = {
  where?: Prisma.SeasonWhereInput
  data: Prisma.XOR<Prisma.SeasonUpdateWithoutTeamsInput, Prisma.SeasonUncheckedUpdateWithoutTeamsInput>
}

export type SeasonUpdateWithoutTeamsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  appointments?: Prisma.AppointmentUpdateManyWithoutSeasonNestedInput
}

export type SeasonUncheckedUpdateWithoutTeamsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutSeasonNestedInput
}


/**
 * Count Type SeasonCountOutputType
 */

export type SeasonCountOutputType = {
  teams: number
  appointments: number
}

export type SeasonCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  teams?: boolean | SeasonCountOutputTypeCountTeamsArgs
  appointments?: boolean | SeasonCountOutputTypeCountAppointmentsArgs
}

/**
 * SeasonCountOutputType without action
 */
export type SeasonCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonCountOutputType
   */
  select?: Prisma.SeasonCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SeasonCountOutputType without action
 */
export type SeasonCountOutputTypeCountTeamsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TeamWhereInput
}

/**
 * SeasonCountOutputType without action
 */
export type SeasonCountOutputTypeCountAppointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppointmentWhereInput
}


export type SeasonSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  name?: boolean
  isActive?: boolean
  teams?: boolean | Prisma.Season$teamsArgs<ExtArgs>
  appointments?: boolean | Prisma.Season$appointmentsArgs<ExtArgs>
  _count?: boolean | Prisma.SeasonCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["season"]>

export type SeasonSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  name?: boolean
  isActive?: boolean
}, ExtArgs["result"]["season"]>

export type SeasonSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  name?: boolean
  isActive?: boolean
}, ExtArgs["result"]["season"]>

export type SeasonSelectScalar = {
  id?: boolean
  createdAt?: boolean
  name?: boolean
  isActive?: boolean
}

export type SeasonOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "name" | "isActive", ExtArgs["result"]["season"]>
export type SeasonInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  teams?: boolean | Prisma.Season$teamsArgs<ExtArgs>
  appointments?: boolean | Prisma.Season$appointmentsArgs<ExtArgs>
  _count?: boolean | Prisma.SeasonCountOutputTypeDefaultArgs<ExtArgs>
}
export type SeasonIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SeasonIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SeasonPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Season"
  objects: {
    teams: Prisma.$TeamPayload<ExtArgs>[]
    appointments: Prisma.$AppointmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    name: string
    isActive: boolean
  }, ExtArgs["result"]["season"]>
  composites: {}
}

export type SeasonGetPayload<S extends boolean | null | undefined | SeasonDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SeasonPayload, S>

export type SeasonCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SeasonFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SeasonCountAggregateInputType | true
  }

export interface SeasonDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Season'], meta: { name: 'Season' } }
  /**
   * Find zero or one Season that matches the filter.
   * @param {SeasonFindUniqueArgs} args - Arguments to find a Season
   * @example
   * // Get one Season
   * const season = await prisma.season.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SeasonFindUniqueArgs>(args: Prisma.SelectSubset<T, SeasonFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SeasonClient<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Season that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SeasonFindUniqueOrThrowArgs} args - Arguments to find a Season
   * @example
   * // Get one Season
   * const season = await prisma.season.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SeasonFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SeasonFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeasonClient<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Season that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonFindFirstArgs} args - Arguments to find a Season
   * @example
   * // Get one Season
   * const season = await prisma.season.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SeasonFindFirstArgs>(args?: Prisma.SelectSubset<T, SeasonFindFirstArgs<ExtArgs>>): Prisma.Prisma__SeasonClient<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Season that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonFindFirstOrThrowArgs} args - Arguments to find a Season
   * @example
   * // Get one Season
   * const season = await prisma.season.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SeasonFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SeasonFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeasonClient<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Seasons that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Seasons
   * const seasons = await prisma.season.findMany()
   * 
   * // Get first 10 Seasons
   * const seasons = await prisma.season.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const seasonWithIdOnly = await prisma.season.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SeasonFindManyArgs>(args?: Prisma.SelectSubset<T, SeasonFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Season.
   * @param {SeasonCreateArgs} args - Arguments to create a Season.
   * @example
   * // Create one Season
   * const Season = await prisma.season.create({
   *   data: {
   *     // ... data to create a Season
   *   }
   * })
   * 
   */
  create<T extends SeasonCreateArgs>(args: Prisma.SelectSubset<T, SeasonCreateArgs<ExtArgs>>): Prisma.Prisma__SeasonClient<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Seasons.
   * @param {SeasonCreateManyArgs} args - Arguments to create many Seasons.
   * @example
   * // Create many Seasons
   * const season = await prisma.season.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SeasonCreateManyArgs>(args?: Prisma.SelectSubset<T, SeasonCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Seasons and returns the data saved in the database.
   * @param {SeasonCreateManyAndReturnArgs} args - Arguments to create many Seasons.
   * @example
   * // Create many Seasons
   * const season = await prisma.season.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Seasons and only return the `id`
   * const seasonWithIdOnly = await prisma.season.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SeasonCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SeasonCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Season.
   * @param {SeasonDeleteArgs} args - Arguments to delete one Season.
   * @example
   * // Delete one Season
   * const Season = await prisma.season.delete({
   *   where: {
   *     // ... filter to delete one Season
   *   }
   * })
   * 
   */
  delete<T extends SeasonDeleteArgs>(args: Prisma.SelectSubset<T, SeasonDeleteArgs<ExtArgs>>): Prisma.Prisma__SeasonClient<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Season.
   * @param {SeasonUpdateArgs} args - Arguments to update one Season.
   * @example
   * // Update one Season
   * const season = await prisma.season.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SeasonUpdateArgs>(args: Prisma.SelectSubset<T, SeasonUpdateArgs<ExtArgs>>): Prisma.Prisma__SeasonClient<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Seasons.
   * @param {SeasonDeleteManyArgs} args - Arguments to filter Seasons to delete.
   * @example
   * // Delete a few Seasons
   * const { count } = await prisma.season.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SeasonDeleteManyArgs>(args?: Prisma.SelectSubset<T, SeasonDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Seasons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Seasons
   * const season = await prisma.season.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SeasonUpdateManyArgs>(args: Prisma.SelectSubset<T, SeasonUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Seasons and returns the data updated in the database.
   * @param {SeasonUpdateManyAndReturnArgs} args - Arguments to update many Seasons.
   * @example
   * // Update many Seasons
   * const season = await prisma.season.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Seasons and only return the `id`
   * const seasonWithIdOnly = await prisma.season.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SeasonUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SeasonUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Season.
   * @param {SeasonUpsertArgs} args - Arguments to update or create a Season.
   * @example
   * // Update or create a Season
   * const season = await prisma.season.upsert({
   *   create: {
   *     // ... data to create a Season
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Season we want to update
   *   }
   * })
   */
  upsert<T extends SeasonUpsertArgs>(args: Prisma.SelectSubset<T, SeasonUpsertArgs<ExtArgs>>): Prisma.Prisma__SeasonClient<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Seasons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonCountArgs} args - Arguments to filter Seasons to count.
   * @example
   * // Count the number of Seasons
   * const count = await prisma.season.count({
   *   where: {
   *     // ... the filter for the Seasons we want to count
   *   }
   * })
  **/
  count<T extends SeasonCountArgs>(
    args?: Prisma.Subset<T, SeasonCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SeasonCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Season.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SeasonAggregateArgs>(args: Prisma.Subset<T, SeasonAggregateArgs>): Prisma.PrismaPromise<GetSeasonAggregateType<T>>

  /**
   * Group by Season.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SeasonGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SeasonGroupByArgs['orderBy'] }
      : { orderBy?: SeasonGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SeasonGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSeasonGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Season model
 */
readonly fields: SeasonFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Season.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SeasonClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  teams<T extends Prisma.Season$teamsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Season$teamsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  appointments<T extends Prisma.Season$appointmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Season$appointmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Season model
 */
export interface SeasonFieldRefs {
  readonly id: Prisma.FieldRef<"Season", 'String'>
  readonly createdAt: Prisma.FieldRef<"Season", 'DateTime'>
  readonly name: Prisma.FieldRef<"Season", 'String'>
  readonly isActive: Prisma.FieldRef<"Season", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Season findUnique
 */
export type SeasonFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonInclude<ExtArgs> | null
  /**
   * Filter, which Season to fetch.
   */
  where: Prisma.SeasonWhereUniqueInput
}

/**
 * Season findUniqueOrThrow
 */
export type SeasonFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonInclude<ExtArgs> | null
  /**
   * Filter, which Season to fetch.
   */
  where: Prisma.SeasonWhereUniqueInput
}

/**
 * Season findFirst
 */
export type SeasonFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonInclude<ExtArgs> | null
  /**
   * Filter, which Season to fetch.
   */
  where?: Prisma.SeasonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seasons to fetch.
   */
  orderBy?: Prisma.SeasonOrderByWithRelationInput | Prisma.SeasonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Seasons.
   */
  cursor?: Prisma.SeasonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seasons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seasons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seasons.
   */
  distinct?: Prisma.SeasonScalarFieldEnum | Prisma.SeasonScalarFieldEnum[]
}

/**
 * Season findFirstOrThrow
 */
export type SeasonFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonInclude<ExtArgs> | null
  /**
   * Filter, which Season to fetch.
   */
  where?: Prisma.SeasonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seasons to fetch.
   */
  orderBy?: Prisma.SeasonOrderByWithRelationInput | Prisma.SeasonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Seasons.
   */
  cursor?: Prisma.SeasonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seasons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seasons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seasons.
   */
  distinct?: Prisma.SeasonScalarFieldEnum | Prisma.SeasonScalarFieldEnum[]
}

/**
 * Season findMany
 */
export type SeasonFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonInclude<ExtArgs> | null
  /**
   * Filter, which Seasons to fetch.
   */
  where?: Prisma.SeasonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seasons to fetch.
   */
  orderBy?: Prisma.SeasonOrderByWithRelationInput | Prisma.SeasonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Seasons.
   */
  cursor?: Prisma.SeasonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seasons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seasons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seasons.
   */
  distinct?: Prisma.SeasonScalarFieldEnum | Prisma.SeasonScalarFieldEnum[]
}

/**
 * Season create
 */
export type SeasonCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonInclude<ExtArgs> | null
  /**
   * The data needed to create a Season.
   */
  data: Prisma.XOR<Prisma.SeasonCreateInput, Prisma.SeasonUncheckedCreateInput>
}

/**
 * Season createMany
 */
export type SeasonCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Seasons.
   */
  data: Prisma.SeasonCreateManyInput | Prisma.SeasonCreateManyInput[]
}

/**
 * Season createManyAndReturn
 */
export type SeasonCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * The data used to create many Seasons.
   */
  data: Prisma.SeasonCreateManyInput | Prisma.SeasonCreateManyInput[]
}

/**
 * Season update
 */
export type SeasonUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonInclude<ExtArgs> | null
  /**
   * The data needed to update a Season.
   */
  data: Prisma.XOR<Prisma.SeasonUpdateInput, Prisma.SeasonUncheckedUpdateInput>
  /**
   * Choose, which Season to update.
   */
  where: Prisma.SeasonWhereUniqueInput
}

/**
 * Season updateMany
 */
export type SeasonUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Seasons.
   */
  data: Prisma.XOR<Prisma.SeasonUpdateManyMutationInput, Prisma.SeasonUncheckedUpdateManyInput>
  /**
   * Filter which Seasons to update
   */
  where?: Prisma.SeasonWhereInput
  /**
   * Limit how many Seasons to update.
   */
  limit?: number
}

/**
 * Season updateManyAndReturn
 */
export type SeasonUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * The data used to update Seasons.
   */
  data: Prisma.XOR<Prisma.SeasonUpdateManyMutationInput, Prisma.SeasonUncheckedUpdateManyInput>
  /**
   * Filter which Seasons to update
   */
  where?: Prisma.SeasonWhereInput
  /**
   * Limit how many Seasons to update.
   */
  limit?: number
}

/**
 * Season upsert
 */
export type SeasonUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonInclude<ExtArgs> | null
  /**
   * The filter to search for the Season to update in case it exists.
   */
  where: Prisma.SeasonWhereUniqueInput
  /**
   * In case the Season found by the `where` argument doesn't exist, create a new Season with this data.
   */
  create: Prisma.XOR<Prisma.SeasonCreateInput, Prisma.SeasonUncheckedCreateInput>
  /**
   * In case the Season was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SeasonUpdateInput, Prisma.SeasonUncheckedUpdateInput>
}

/**
 * Season delete
 */
export type SeasonDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonInclude<ExtArgs> | null
  /**
   * Filter which Season to delete.
   */
  where: Prisma.SeasonWhereUniqueInput
}

/**
 * Season deleteMany
 */
export type SeasonDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Seasons to delete
   */
  where?: Prisma.SeasonWhereInput
  /**
   * Limit how many Seasons to delete.
   */
  limit?: number
}

/**
 * Season.teams
 */
export type Season$teamsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Team
   */
  select?: Prisma.TeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Team
   */
  omit?: Prisma.TeamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamInclude<ExtArgs> | null
  where?: Prisma.TeamWhereInput
  orderBy?: Prisma.TeamOrderByWithRelationInput | Prisma.TeamOrderByWithRelationInput[]
  cursor?: Prisma.TeamWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TeamScalarFieldEnum | Prisma.TeamScalarFieldEnum[]
}

/**
 * Season.appointments
 */
export type Season$appointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  where?: Prisma.AppointmentWhereInput
  orderBy?: Prisma.AppointmentOrderByWithRelationInput | Prisma.AppointmentOrderByWithRelationInput[]
  cursor?: Prisma.AppointmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentScalarFieldEnum | Prisma.AppointmentScalarFieldEnum[]
}

/**
 * Season without action
 */
export type SeasonDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Season
   */
  select?: Prisma.SeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Season
   */
  omit?: Prisma.SeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonInclude<ExtArgs> | null
}
