
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SeasonAgeGroupCount` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model SeasonAgeGroupCount
 * 
 */
export type SeasonAgeGroupCountModel = runtime.Types.Result.DefaultSelection<Prisma.$SeasonAgeGroupCountPayload>

export type AggregateSeasonAgeGroupCount = {
  _count: SeasonAgeGroupCountCountAggregateOutputType | null
  _avg: SeasonAgeGroupCountAvgAggregateOutputType | null
  _sum: SeasonAgeGroupCountSumAggregateOutputType | null
  _min: SeasonAgeGroupCountMinAggregateOutputType | null
  _max: SeasonAgeGroupCountMaxAggregateOutputType | null
}

export type SeasonAgeGroupCountAvgAggregateOutputType = {
  playerCount: number | null
}

export type SeasonAgeGroupCountSumAggregateOutputType = {
  playerCount: number | null
}

export type SeasonAgeGroupCountMinAggregateOutputType = {
  seasonId: string | null
  ageGroup: string | null
  playerCount: number | null
}

export type SeasonAgeGroupCountMaxAggregateOutputType = {
  seasonId: string | null
  ageGroup: string | null
  playerCount: number | null
}

export type SeasonAgeGroupCountCountAggregateOutputType = {
  seasonId: number
  ageGroup: number
  playerCount: number
  _all: number
}


export type SeasonAgeGroupCountAvgAggregateInputType = {
  playerCount?: true
}

export type SeasonAgeGroupCountSumAggregateInputType = {
  playerCount?: true
}

export type SeasonAgeGroupCountMinAggregateInputType = {
  seasonId?: true
  ageGroup?: true
  playerCount?: true
}

export type SeasonAgeGroupCountMaxAggregateInputType = {
  seasonId?: true
  ageGroup?: true
  playerCount?: true
}

export type SeasonAgeGroupCountCountAggregateInputType = {
  seasonId?: true
  ageGroup?: true
  playerCount?: true
  _all?: true
}

export type SeasonAgeGroupCountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SeasonAgeGroupCount to aggregate.
   */
  where?: Prisma.SeasonAgeGroupCountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeasonAgeGroupCounts to fetch.
   */
  orderBy?: Prisma.SeasonAgeGroupCountOrderByWithRelationInput | Prisma.SeasonAgeGroupCountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SeasonAgeGroupCountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeasonAgeGroupCounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeasonAgeGroupCounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SeasonAgeGroupCounts
  **/
  _count?: true | SeasonAgeGroupCountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SeasonAgeGroupCountAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SeasonAgeGroupCountSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SeasonAgeGroupCountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SeasonAgeGroupCountMaxAggregateInputType
}

export type GetSeasonAgeGroupCountAggregateType<T extends SeasonAgeGroupCountAggregateArgs> = {
      [P in keyof T & keyof AggregateSeasonAgeGroupCount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSeasonAgeGroupCount[P]>
    : Prisma.GetScalarType<T[P], AggregateSeasonAgeGroupCount[P]>
}




export type SeasonAgeGroupCountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SeasonAgeGroupCountWhereInput
  orderBy?: Prisma.SeasonAgeGroupCountOrderByWithAggregationInput | Prisma.SeasonAgeGroupCountOrderByWithAggregationInput[]
  by: Prisma.SeasonAgeGroupCountScalarFieldEnum[] | Prisma.SeasonAgeGroupCountScalarFieldEnum
  having?: Prisma.SeasonAgeGroupCountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SeasonAgeGroupCountCountAggregateInputType | true
  _avg?: SeasonAgeGroupCountAvgAggregateInputType
  _sum?: SeasonAgeGroupCountSumAggregateInputType
  _min?: SeasonAgeGroupCountMinAggregateInputType
  _max?: SeasonAgeGroupCountMaxAggregateInputType
}

export type SeasonAgeGroupCountGroupByOutputType = {
  seasonId: string
  ageGroup: string
  playerCount: number
  _count: SeasonAgeGroupCountCountAggregateOutputType | null
  _avg: SeasonAgeGroupCountAvgAggregateOutputType | null
  _sum: SeasonAgeGroupCountSumAggregateOutputType | null
  _min: SeasonAgeGroupCountMinAggregateOutputType | null
  _max: SeasonAgeGroupCountMaxAggregateOutputType | null
}

type GetSeasonAgeGroupCountGroupByPayload<T extends SeasonAgeGroupCountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SeasonAgeGroupCountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SeasonAgeGroupCountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SeasonAgeGroupCountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SeasonAgeGroupCountGroupByOutputType[P]>
      }
    >
  >



export type SeasonAgeGroupCountWhereInput = {
  AND?: Prisma.SeasonAgeGroupCountWhereInput | Prisma.SeasonAgeGroupCountWhereInput[]
  OR?: Prisma.SeasonAgeGroupCountWhereInput[]
  NOT?: Prisma.SeasonAgeGroupCountWhereInput | Prisma.SeasonAgeGroupCountWhereInput[]
  seasonId?: Prisma.StringFilter<"SeasonAgeGroupCount"> | string
  ageGroup?: Prisma.StringFilter<"SeasonAgeGroupCount"> | string
  playerCount?: Prisma.IntFilter<"SeasonAgeGroupCount"> | number
  season?: Prisma.XOR<Prisma.SeasonScalarRelationFilter, Prisma.SeasonWhereInput>
}

export type SeasonAgeGroupCountOrderByWithRelationInput = {
  seasonId?: Prisma.SortOrder
  ageGroup?: Prisma.SortOrder
  playerCount?: Prisma.SortOrder
  season?: Prisma.SeasonOrderByWithRelationInput
}

export type SeasonAgeGroupCountWhereUniqueInput = Prisma.AtLeast<{
  seasonId_ageGroup?: Prisma.SeasonAgeGroupCountSeasonIdAgeGroupCompoundUniqueInput
  AND?: Prisma.SeasonAgeGroupCountWhereInput | Prisma.SeasonAgeGroupCountWhereInput[]
  OR?: Prisma.SeasonAgeGroupCountWhereInput[]
  NOT?: Prisma.SeasonAgeGroupCountWhereInput | Prisma.SeasonAgeGroupCountWhereInput[]
  seasonId?: Prisma.StringFilter<"SeasonAgeGroupCount"> | string
  ageGroup?: Prisma.StringFilter<"SeasonAgeGroupCount"> | string
  playerCount?: Prisma.IntFilter<"SeasonAgeGroupCount"> | number
  season?: Prisma.XOR<Prisma.SeasonScalarRelationFilter, Prisma.SeasonWhereInput>
}, "seasonId_ageGroup">

export type SeasonAgeGroupCountOrderByWithAggregationInput = {
  seasonId?: Prisma.SortOrder
  ageGroup?: Prisma.SortOrder
  playerCount?: Prisma.SortOrder
  _count?: Prisma.SeasonAgeGroupCountCountOrderByAggregateInput
  _avg?: Prisma.SeasonAgeGroupCountAvgOrderByAggregateInput
  _max?: Prisma.SeasonAgeGroupCountMaxOrderByAggregateInput
  _min?: Prisma.SeasonAgeGroupCountMinOrderByAggregateInput
  _sum?: Prisma.SeasonAgeGroupCountSumOrderByAggregateInput
}

export type SeasonAgeGroupCountScalarWhereWithAggregatesInput = {
  AND?: Prisma.SeasonAgeGroupCountScalarWhereWithAggregatesInput | Prisma.SeasonAgeGroupCountScalarWhereWithAggregatesInput[]
  OR?: Prisma.SeasonAgeGroupCountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SeasonAgeGroupCountScalarWhereWithAggregatesInput | Prisma.SeasonAgeGroupCountScalarWhereWithAggregatesInput[]
  seasonId?: Prisma.StringWithAggregatesFilter<"SeasonAgeGroupCount"> | string
  ageGroup?: Prisma.StringWithAggregatesFilter<"SeasonAgeGroupCount"> | string
  playerCount?: Prisma.IntWithAggregatesFilter<"SeasonAgeGroupCount"> | number
}

export type SeasonAgeGroupCountCreateInput = {
  ageGroup: string
  playerCount?: number
  season: Prisma.SeasonCreateNestedOneWithoutAgeGroupCountsInput
}

export type SeasonAgeGroupCountUncheckedCreateInput = {
  seasonId: string
  ageGroup: string
  playerCount?: number
}

export type SeasonAgeGroupCountUpdateInput = {
  ageGroup?: Prisma.StringFieldUpdateOperationsInput | string
  playerCount?: Prisma.IntFieldUpdateOperationsInput | number
  season?: Prisma.SeasonUpdateOneRequiredWithoutAgeGroupCountsNestedInput
}

export type SeasonAgeGroupCountUncheckedUpdateInput = {
  seasonId?: Prisma.StringFieldUpdateOperationsInput | string
  ageGroup?: Prisma.StringFieldUpdateOperationsInput | string
  playerCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SeasonAgeGroupCountCreateManyInput = {
  seasonId: string
  ageGroup: string
  playerCount?: number
}

export type SeasonAgeGroupCountUpdateManyMutationInput = {
  ageGroup?: Prisma.StringFieldUpdateOperationsInput | string
  playerCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SeasonAgeGroupCountUncheckedUpdateManyInput = {
  seasonId?: Prisma.StringFieldUpdateOperationsInput | string
  ageGroup?: Prisma.StringFieldUpdateOperationsInput | string
  playerCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SeasonAgeGroupCountListRelationFilter = {
  every?: Prisma.SeasonAgeGroupCountWhereInput
  some?: Prisma.SeasonAgeGroupCountWhereInput
  none?: Prisma.SeasonAgeGroupCountWhereInput
}

export type SeasonAgeGroupCountOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SeasonAgeGroupCountSeasonIdAgeGroupCompoundUniqueInput = {
  seasonId: string
  ageGroup: string
}

export type SeasonAgeGroupCountCountOrderByAggregateInput = {
  seasonId?: Prisma.SortOrder
  ageGroup?: Prisma.SortOrder
  playerCount?: Prisma.SortOrder
}

export type SeasonAgeGroupCountAvgOrderByAggregateInput = {
  playerCount?: Prisma.SortOrder
}

export type SeasonAgeGroupCountMaxOrderByAggregateInput = {
  seasonId?: Prisma.SortOrder
  ageGroup?: Prisma.SortOrder
  playerCount?: Prisma.SortOrder
}

export type SeasonAgeGroupCountMinOrderByAggregateInput = {
  seasonId?: Prisma.SortOrder
  ageGroup?: Prisma.SortOrder
  playerCount?: Prisma.SortOrder
}

export type SeasonAgeGroupCountSumOrderByAggregateInput = {
  playerCount?: Prisma.SortOrder
}

export type SeasonAgeGroupCountCreateNestedManyWithoutSeasonInput = {
  create?: Prisma.XOR<Prisma.SeasonAgeGroupCountCreateWithoutSeasonInput, Prisma.SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput> | Prisma.SeasonAgeGroupCountCreateWithoutSeasonInput[] | Prisma.SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput[]
  connectOrCreate?: Prisma.SeasonAgeGroupCountCreateOrConnectWithoutSeasonInput | Prisma.SeasonAgeGroupCountCreateOrConnectWithoutSeasonInput[]
  createMany?: Prisma.SeasonAgeGroupCountCreateManySeasonInputEnvelope
  connect?: Prisma.SeasonAgeGroupCountWhereUniqueInput | Prisma.SeasonAgeGroupCountWhereUniqueInput[]
}

export type SeasonAgeGroupCountUncheckedCreateNestedManyWithoutSeasonInput = {
  create?: Prisma.XOR<Prisma.SeasonAgeGroupCountCreateWithoutSeasonInput, Prisma.SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput> | Prisma.SeasonAgeGroupCountCreateWithoutSeasonInput[] | Prisma.SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput[]
  connectOrCreate?: Prisma.SeasonAgeGroupCountCreateOrConnectWithoutSeasonInput | Prisma.SeasonAgeGroupCountCreateOrConnectWithoutSeasonInput[]
  createMany?: Prisma.SeasonAgeGroupCountCreateManySeasonInputEnvelope
  connect?: Prisma.SeasonAgeGroupCountWhereUniqueInput | Prisma.SeasonAgeGroupCountWhereUniqueInput[]
}

export type SeasonAgeGroupCountUpdateManyWithoutSeasonNestedInput = {
  create?: Prisma.XOR<Prisma.SeasonAgeGroupCountCreateWithoutSeasonInput, Prisma.SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput> | Prisma.SeasonAgeGroupCountCreateWithoutSeasonInput[] | Prisma.SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput[]
  connectOrCreate?: Prisma.SeasonAgeGroupCountCreateOrConnectWithoutSeasonInput | Prisma.SeasonAgeGroupCountCreateOrConnectWithoutSeasonInput[]
  upsert?: Prisma.SeasonAgeGroupCountUpsertWithWhereUniqueWithoutSeasonInput | Prisma.SeasonAgeGroupCountUpsertWithWhereUniqueWithoutSeasonInput[]
  createMany?: Prisma.SeasonAgeGroupCountCreateManySeasonInputEnvelope
  set?: Prisma.SeasonAgeGroupCountWhereUniqueInput | Prisma.SeasonAgeGroupCountWhereUniqueInput[]
  disconnect?: Prisma.SeasonAgeGroupCountWhereUniqueInput | Prisma.SeasonAgeGroupCountWhereUniqueInput[]
  delete?: Prisma.SeasonAgeGroupCountWhereUniqueInput | Prisma.SeasonAgeGroupCountWhereUniqueInput[]
  connect?: Prisma.SeasonAgeGroupCountWhereUniqueInput | Prisma.SeasonAgeGroupCountWhereUniqueInput[]
  update?: Prisma.SeasonAgeGroupCountUpdateWithWhereUniqueWithoutSeasonInput | Prisma.SeasonAgeGroupCountUpdateWithWhereUniqueWithoutSeasonInput[]
  updateMany?: Prisma.SeasonAgeGroupCountUpdateManyWithWhereWithoutSeasonInput | Prisma.SeasonAgeGroupCountUpdateManyWithWhereWithoutSeasonInput[]
  deleteMany?: Prisma.SeasonAgeGroupCountScalarWhereInput | Prisma.SeasonAgeGroupCountScalarWhereInput[]
}

export type SeasonAgeGroupCountUncheckedUpdateManyWithoutSeasonNestedInput = {
  create?: Prisma.XOR<Prisma.SeasonAgeGroupCountCreateWithoutSeasonInput, Prisma.SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput> | Prisma.SeasonAgeGroupCountCreateWithoutSeasonInput[] | Prisma.SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput[]
  connectOrCreate?: Prisma.SeasonAgeGroupCountCreateOrConnectWithoutSeasonInput | Prisma.SeasonAgeGroupCountCreateOrConnectWithoutSeasonInput[]
  upsert?: Prisma.SeasonAgeGroupCountUpsertWithWhereUniqueWithoutSeasonInput | Prisma.SeasonAgeGroupCountUpsertWithWhereUniqueWithoutSeasonInput[]
  createMany?: Prisma.SeasonAgeGroupCountCreateManySeasonInputEnvelope
  set?: Prisma.SeasonAgeGroupCountWhereUniqueInput | Prisma.SeasonAgeGroupCountWhereUniqueInput[]
  disconnect?: Prisma.SeasonAgeGroupCountWhereUniqueInput | Prisma.SeasonAgeGroupCountWhereUniqueInput[]
  delete?: Prisma.SeasonAgeGroupCountWhereUniqueInput | Prisma.SeasonAgeGroupCountWhereUniqueInput[]
  connect?: Prisma.SeasonAgeGroupCountWhereUniqueInput | Prisma.SeasonAgeGroupCountWhereUniqueInput[]
  update?: Prisma.SeasonAgeGroupCountUpdateWithWhereUniqueWithoutSeasonInput | Prisma.SeasonAgeGroupCountUpdateWithWhereUniqueWithoutSeasonInput[]
  updateMany?: Prisma.SeasonAgeGroupCountUpdateManyWithWhereWithoutSeasonInput | Prisma.SeasonAgeGroupCountUpdateManyWithWhereWithoutSeasonInput[]
  deleteMany?: Prisma.SeasonAgeGroupCountScalarWhereInput | Prisma.SeasonAgeGroupCountScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SeasonAgeGroupCountCreateWithoutSeasonInput = {
  ageGroup: string
  playerCount?: number
}

export type SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput = {
  ageGroup: string
  playerCount?: number
}

export type SeasonAgeGroupCountCreateOrConnectWithoutSeasonInput = {
  where: Prisma.SeasonAgeGroupCountWhereUniqueInput
  create: Prisma.XOR<Prisma.SeasonAgeGroupCountCreateWithoutSeasonInput, Prisma.SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput>
}

export type SeasonAgeGroupCountCreateManySeasonInputEnvelope = {
  data: Prisma.SeasonAgeGroupCountCreateManySeasonInput | Prisma.SeasonAgeGroupCountCreateManySeasonInput[]
}

export type SeasonAgeGroupCountUpsertWithWhereUniqueWithoutSeasonInput = {
  where: Prisma.SeasonAgeGroupCountWhereUniqueInput
  update: Prisma.XOR<Prisma.SeasonAgeGroupCountUpdateWithoutSeasonInput, Prisma.SeasonAgeGroupCountUncheckedUpdateWithoutSeasonInput>
  create: Prisma.XOR<Prisma.SeasonAgeGroupCountCreateWithoutSeasonInput, Prisma.SeasonAgeGroupCountUncheckedCreateWithoutSeasonInput>
}

export type SeasonAgeGroupCountUpdateWithWhereUniqueWithoutSeasonInput = {
  where: Prisma.SeasonAgeGroupCountWhereUniqueInput
  data: Prisma.XOR<Prisma.SeasonAgeGroupCountUpdateWithoutSeasonInput, Prisma.SeasonAgeGroupCountUncheckedUpdateWithoutSeasonInput>
}

export type SeasonAgeGroupCountUpdateManyWithWhereWithoutSeasonInput = {
  where: Prisma.SeasonAgeGroupCountScalarWhereInput
  data: Prisma.XOR<Prisma.SeasonAgeGroupCountUpdateManyMutationInput, Prisma.SeasonAgeGroupCountUncheckedUpdateManyWithoutSeasonInput>
}

export type SeasonAgeGroupCountScalarWhereInput = {
  AND?: Prisma.SeasonAgeGroupCountScalarWhereInput | Prisma.SeasonAgeGroupCountScalarWhereInput[]
  OR?: Prisma.SeasonAgeGroupCountScalarWhereInput[]
  NOT?: Prisma.SeasonAgeGroupCountScalarWhereInput | Prisma.SeasonAgeGroupCountScalarWhereInput[]
  seasonId?: Prisma.StringFilter<"SeasonAgeGroupCount"> | string
  ageGroup?: Prisma.StringFilter<"SeasonAgeGroupCount"> | string
  playerCount?: Prisma.IntFilter<"SeasonAgeGroupCount"> | number
}

export type SeasonAgeGroupCountCreateManySeasonInput = {
  ageGroup: string
  playerCount?: number
}

export type SeasonAgeGroupCountUpdateWithoutSeasonInput = {
  ageGroup?: Prisma.StringFieldUpdateOperationsInput | string
  playerCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SeasonAgeGroupCountUncheckedUpdateWithoutSeasonInput = {
  ageGroup?: Prisma.StringFieldUpdateOperationsInput | string
  playerCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SeasonAgeGroupCountUncheckedUpdateManyWithoutSeasonInput = {
  ageGroup?: Prisma.StringFieldUpdateOperationsInput | string
  playerCount?: Prisma.IntFieldUpdateOperationsInput | number
}



export type SeasonAgeGroupCountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  seasonId?: boolean
  ageGroup?: boolean
  playerCount?: boolean
  season?: boolean | Prisma.SeasonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["seasonAgeGroupCount"]>

export type SeasonAgeGroupCountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  seasonId?: boolean
  ageGroup?: boolean
  playerCount?: boolean
  season?: boolean | Prisma.SeasonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["seasonAgeGroupCount"]>

export type SeasonAgeGroupCountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  seasonId?: boolean
  ageGroup?: boolean
  playerCount?: boolean
  season?: boolean | Prisma.SeasonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["seasonAgeGroupCount"]>

export type SeasonAgeGroupCountSelectScalar = {
  seasonId?: boolean
  ageGroup?: boolean
  playerCount?: boolean
}

export type SeasonAgeGroupCountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"seasonId" | "ageGroup" | "playerCount", ExtArgs["result"]["seasonAgeGroupCount"]>
export type SeasonAgeGroupCountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  season?: boolean | Prisma.SeasonDefaultArgs<ExtArgs>
}
export type SeasonAgeGroupCountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  season?: boolean | Prisma.SeasonDefaultArgs<ExtArgs>
}
export type SeasonAgeGroupCountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  season?: boolean | Prisma.SeasonDefaultArgs<ExtArgs>
}

export type $SeasonAgeGroupCountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SeasonAgeGroupCount"
  objects: {
    season: Prisma.$SeasonPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    seasonId: string
    ageGroup: string
    playerCount: number
  }, ExtArgs["result"]["seasonAgeGroupCount"]>
  composites: {}
}

export type SeasonAgeGroupCountGetPayload<S extends boolean | null | undefined | SeasonAgeGroupCountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload, S>

export type SeasonAgeGroupCountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SeasonAgeGroupCountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SeasonAgeGroupCountCountAggregateInputType | true
  }

export interface SeasonAgeGroupCountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SeasonAgeGroupCount'], meta: { name: 'SeasonAgeGroupCount' } }
  /**
   * Find zero or one SeasonAgeGroupCount that matches the filter.
   * @param {SeasonAgeGroupCountFindUniqueArgs} args - Arguments to find a SeasonAgeGroupCount
   * @example
   * // Get one SeasonAgeGroupCount
   * const seasonAgeGroupCount = await prisma.seasonAgeGroupCount.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SeasonAgeGroupCountFindUniqueArgs>(args: Prisma.SelectSubset<T, SeasonAgeGroupCountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SeasonAgeGroupCountClient<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SeasonAgeGroupCount that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SeasonAgeGroupCountFindUniqueOrThrowArgs} args - Arguments to find a SeasonAgeGroupCount
   * @example
   * // Get one SeasonAgeGroupCount
   * const seasonAgeGroupCount = await prisma.seasonAgeGroupCount.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SeasonAgeGroupCountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SeasonAgeGroupCountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeasonAgeGroupCountClient<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SeasonAgeGroupCount that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonAgeGroupCountFindFirstArgs} args - Arguments to find a SeasonAgeGroupCount
   * @example
   * // Get one SeasonAgeGroupCount
   * const seasonAgeGroupCount = await prisma.seasonAgeGroupCount.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SeasonAgeGroupCountFindFirstArgs>(args?: Prisma.SelectSubset<T, SeasonAgeGroupCountFindFirstArgs<ExtArgs>>): Prisma.Prisma__SeasonAgeGroupCountClient<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SeasonAgeGroupCount that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonAgeGroupCountFindFirstOrThrowArgs} args - Arguments to find a SeasonAgeGroupCount
   * @example
   * // Get one SeasonAgeGroupCount
   * const seasonAgeGroupCount = await prisma.seasonAgeGroupCount.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SeasonAgeGroupCountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SeasonAgeGroupCountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeasonAgeGroupCountClient<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SeasonAgeGroupCounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonAgeGroupCountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SeasonAgeGroupCounts
   * const seasonAgeGroupCounts = await prisma.seasonAgeGroupCount.findMany()
   * 
   * // Get first 10 SeasonAgeGroupCounts
   * const seasonAgeGroupCounts = await prisma.seasonAgeGroupCount.findMany({ take: 10 })
   * 
   * // Only select the `seasonId`
   * const seasonAgeGroupCountWithSeasonIdOnly = await prisma.seasonAgeGroupCount.findMany({ select: { seasonId: true } })
   * 
   */
  findMany<T extends SeasonAgeGroupCountFindManyArgs>(args?: Prisma.SelectSubset<T, SeasonAgeGroupCountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SeasonAgeGroupCount.
   * @param {SeasonAgeGroupCountCreateArgs} args - Arguments to create a SeasonAgeGroupCount.
   * @example
   * // Create one SeasonAgeGroupCount
   * const SeasonAgeGroupCount = await prisma.seasonAgeGroupCount.create({
   *   data: {
   *     // ... data to create a SeasonAgeGroupCount
   *   }
   * })
   * 
   */
  create<T extends SeasonAgeGroupCountCreateArgs>(args: Prisma.SelectSubset<T, SeasonAgeGroupCountCreateArgs<ExtArgs>>): Prisma.Prisma__SeasonAgeGroupCountClient<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SeasonAgeGroupCounts.
   * @param {SeasonAgeGroupCountCreateManyArgs} args - Arguments to create many SeasonAgeGroupCounts.
   * @example
   * // Create many SeasonAgeGroupCounts
   * const seasonAgeGroupCount = await prisma.seasonAgeGroupCount.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SeasonAgeGroupCountCreateManyArgs>(args?: Prisma.SelectSubset<T, SeasonAgeGroupCountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SeasonAgeGroupCounts and returns the data saved in the database.
   * @param {SeasonAgeGroupCountCreateManyAndReturnArgs} args - Arguments to create many SeasonAgeGroupCounts.
   * @example
   * // Create many SeasonAgeGroupCounts
   * const seasonAgeGroupCount = await prisma.seasonAgeGroupCount.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SeasonAgeGroupCounts and only return the `seasonId`
   * const seasonAgeGroupCountWithSeasonIdOnly = await prisma.seasonAgeGroupCount.createManyAndReturn({
   *   select: { seasonId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SeasonAgeGroupCountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SeasonAgeGroupCountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SeasonAgeGroupCount.
   * @param {SeasonAgeGroupCountDeleteArgs} args - Arguments to delete one SeasonAgeGroupCount.
   * @example
   * // Delete one SeasonAgeGroupCount
   * const SeasonAgeGroupCount = await prisma.seasonAgeGroupCount.delete({
   *   where: {
   *     // ... filter to delete one SeasonAgeGroupCount
   *   }
   * })
   * 
   */
  delete<T extends SeasonAgeGroupCountDeleteArgs>(args: Prisma.SelectSubset<T, SeasonAgeGroupCountDeleteArgs<ExtArgs>>): Prisma.Prisma__SeasonAgeGroupCountClient<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SeasonAgeGroupCount.
   * @param {SeasonAgeGroupCountUpdateArgs} args - Arguments to update one SeasonAgeGroupCount.
   * @example
   * // Update one SeasonAgeGroupCount
   * const seasonAgeGroupCount = await prisma.seasonAgeGroupCount.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SeasonAgeGroupCountUpdateArgs>(args: Prisma.SelectSubset<T, SeasonAgeGroupCountUpdateArgs<ExtArgs>>): Prisma.Prisma__SeasonAgeGroupCountClient<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SeasonAgeGroupCounts.
   * @param {SeasonAgeGroupCountDeleteManyArgs} args - Arguments to filter SeasonAgeGroupCounts to delete.
   * @example
   * // Delete a few SeasonAgeGroupCounts
   * const { count } = await prisma.seasonAgeGroupCount.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SeasonAgeGroupCountDeleteManyArgs>(args?: Prisma.SelectSubset<T, SeasonAgeGroupCountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SeasonAgeGroupCounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonAgeGroupCountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SeasonAgeGroupCounts
   * const seasonAgeGroupCount = await prisma.seasonAgeGroupCount.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SeasonAgeGroupCountUpdateManyArgs>(args: Prisma.SelectSubset<T, SeasonAgeGroupCountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SeasonAgeGroupCounts and returns the data updated in the database.
   * @param {SeasonAgeGroupCountUpdateManyAndReturnArgs} args - Arguments to update many SeasonAgeGroupCounts.
   * @example
   * // Update many SeasonAgeGroupCounts
   * const seasonAgeGroupCount = await prisma.seasonAgeGroupCount.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SeasonAgeGroupCounts and only return the `seasonId`
   * const seasonAgeGroupCountWithSeasonIdOnly = await prisma.seasonAgeGroupCount.updateManyAndReturn({
   *   select: { seasonId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SeasonAgeGroupCountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SeasonAgeGroupCountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SeasonAgeGroupCount.
   * @param {SeasonAgeGroupCountUpsertArgs} args - Arguments to update or create a SeasonAgeGroupCount.
   * @example
   * // Update or create a SeasonAgeGroupCount
   * const seasonAgeGroupCount = await prisma.seasonAgeGroupCount.upsert({
   *   create: {
   *     // ... data to create a SeasonAgeGroupCount
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SeasonAgeGroupCount we want to update
   *   }
   * })
   */
  upsert<T extends SeasonAgeGroupCountUpsertArgs>(args: Prisma.SelectSubset<T, SeasonAgeGroupCountUpsertArgs<ExtArgs>>): Prisma.Prisma__SeasonAgeGroupCountClient<runtime.Types.Result.GetResult<Prisma.$SeasonAgeGroupCountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SeasonAgeGroupCounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonAgeGroupCountCountArgs} args - Arguments to filter SeasonAgeGroupCounts to count.
   * @example
   * // Count the number of SeasonAgeGroupCounts
   * const count = await prisma.seasonAgeGroupCount.count({
   *   where: {
   *     // ... the filter for the SeasonAgeGroupCounts we want to count
   *   }
   * })
  **/
  count<T extends SeasonAgeGroupCountCountArgs>(
    args?: Prisma.Subset<T, SeasonAgeGroupCountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SeasonAgeGroupCountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SeasonAgeGroupCount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonAgeGroupCountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SeasonAgeGroupCountAggregateArgs>(args: Prisma.Subset<T, SeasonAgeGroupCountAggregateArgs>): Prisma.PrismaPromise<GetSeasonAgeGroupCountAggregateType<T>>

  /**
   * Group by SeasonAgeGroupCount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeasonAgeGroupCountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SeasonAgeGroupCountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SeasonAgeGroupCountGroupByArgs['orderBy'] }
      : { orderBy?: SeasonAgeGroupCountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SeasonAgeGroupCountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSeasonAgeGroupCountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SeasonAgeGroupCount model
 */
readonly fields: SeasonAgeGroupCountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SeasonAgeGroupCount.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SeasonAgeGroupCountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  season<T extends Prisma.SeasonDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SeasonDefaultArgs<ExtArgs>>): Prisma.Prisma__SeasonClient<runtime.Types.Result.GetResult<Prisma.$SeasonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SeasonAgeGroupCount model
 */
export interface SeasonAgeGroupCountFieldRefs {
  readonly seasonId: Prisma.FieldRef<"SeasonAgeGroupCount", 'String'>
  readonly ageGroup: Prisma.FieldRef<"SeasonAgeGroupCount", 'String'>
  readonly playerCount: Prisma.FieldRef<"SeasonAgeGroupCount", 'Int'>
}
    

// Custom InputTypes
/**
 * SeasonAgeGroupCount findUnique
 */
export type SeasonAgeGroupCountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountInclude<ExtArgs> | null
  /**
   * Filter, which SeasonAgeGroupCount to fetch.
   */
  where: Prisma.SeasonAgeGroupCountWhereUniqueInput
}

/**
 * SeasonAgeGroupCount findUniqueOrThrow
 */
export type SeasonAgeGroupCountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountInclude<ExtArgs> | null
  /**
   * Filter, which SeasonAgeGroupCount to fetch.
   */
  where: Prisma.SeasonAgeGroupCountWhereUniqueInput
}

/**
 * SeasonAgeGroupCount findFirst
 */
export type SeasonAgeGroupCountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountInclude<ExtArgs> | null
  /**
   * Filter, which SeasonAgeGroupCount to fetch.
   */
  where?: Prisma.SeasonAgeGroupCountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeasonAgeGroupCounts to fetch.
   */
  orderBy?: Prisma.SeasonAgeGroupCountOrderByWithRelationInput | Prisma.SeasonAgeGroupCountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SeasonAgeGroupCounts.
   */
  cursor?: Prisma.SeasonAgeGroupCountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeasonAgeGroupCounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeasonAgeGroupCounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SeasonAgeGroupCounts.
   */
  distinct?: Prisma.SeasonAgeGroupCountScalarFieldEnum | Prisma.SeasonAgeGroupCountScalarFieldEnum[]
}

/**
 * SeasonAgeGroupCount findFirstOrThrow
 */
export type SeasonAgeGroupCountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountInclude<ExtArgs> | null
  /**
   * Filter, which SeasonAgeGroupCount to fetch.
   */
  where?: Prisma.SeasonAgeGroupCountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeasonAgeGroupCounts to fetch.
   */
  orderBy?: Prisma.SeasonAgeGroupCountOrderByWithRelationInput | Prisma.SeasonAgeGroupCountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SeasonAgeGroupCounts.
   */
  cursor?: Prisma.SeasonAgeGroupCountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeasonAgeGroupCounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeasonAgeGroupCounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SeasonAgeGroupCounts.
   */
  distinct?: Prisma.SeasonAgeGroupCountScalarFieldEnum | Prisma.SeasonAgeGroupCountScalarFieldEnum[]
}

/**
 * SeasonAgeGroupCount findMany
 */
export type SeasonAgeGroupCountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountInclude<ExtArgs> | null
  /**
   * Filter, which SeasonAgeGroupCounts to fetch.
   */
  where?: Prisma.SeasonAgeGroupCountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeasonAgeGroupCounts to fetch.
   */
  orderBy?: Prisma.SeasonAgeGroupCountOrderByWithRelationInput | Prisma.SeasonAgeGroupCountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SeasonAgeGroupCounts.
   */
  cursor?: Prisma.SeasonAgeGroupCountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeasonAgeGroupCounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeasonAgeGroupCounts.
   */
  skip?: number
  distinct?: Prisma.SeasonAgeGroupCountScalarFieldEnum | Prisma.SeasonAgeGroupCountScalarFieldEnum[]
}

/**
 * SeasonAgeGroupCount create
 */
export type SeasonAgeGroupCountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountInclude<ExtArgs> | null
  /**
   * The data needed to create a SeasonAgeGroupCount.
   */
  data: Prisma.XOR<Prisma.SeasonAgeGroupCountCreateInput, Prisma.SeasonAgeGroupCountUncheckedCreateInput>
}

/**
 * SeasonAgeGroupCount createMany
 */
export type SeasonAgeGroupCountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SeasonAgeGroupCounts.
   */
  data: Prisma.SeasonAgeGroupCountCreateManyInput | Prisma.SeasonAgeGroupCountCreateManyInput[]
}

/**
 * SeasonAgeGroupCount createManyAndReturn
 */
export type SeasonAgeGroupCountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * The data used to create many SeasonAgeGroupCounts.
   */
  data: Prisma.SeasonAgeGroupCountCreateManyInput | Prisma.SeasonAgeGroupCountCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SeasonAgeGroupCount update
 */
export type SeasonAgeGroupCountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountInclude<ExtArgs> | null
  /**
   * The data needed to update a SeasonAgeGroupCount.
   */
  data: Prisma.XOR<Prisma.SeasonAgeGroupCountUpdateInput, Prisma.SeasonAgeGroupCountUncheckedUpdateInput>
  /**
   * Choose, which SeasonAgeGroupCount to update.
   */
  where: Prisma.SeasonAgeGroupCountWhereUniqueInput
}

/**
 * SeasonAgeGroupCount updateMany
 */
export type SeasonAgeGroupCountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SeasonAgeGroupCounts.
   */
  data: Prisma.XOR<Prisma.SeasonAgeGroupCountUpdateManyMutationInput, Prisma.SeasonAgeGroupCountUncheckedUpdateManyInput>
  /**
   * Filter which SeasonAgeGroupCounts to update
   */
  where?: Prisma.SeasonAgeGroupCountWhereInput
  /**
   * Limit how many SeasonAgeGroupCounts to update.
   */
  limit?: number
}

/**
 * SeasonAgeGroupCount updateManyAndReturn
 */
export type SeasonAgeGroupCountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * The data used to update SeasonAgeGroupCounts.
   */
  data: Prisma.XOR<Prisma.SeasonAgeGroupCountUpdateManyMutationInput, Prisma.SeasonAgeGroupCountUncheckedUpdateManyInput>
  /**
   * Filter which SeasonAgeGroupCounts to update
   */
  where?: Prisma.SeasonAgeGroupCountWhereInput
  /**
   * Limit how many SeasonAgeGroupCounts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SeasonAgeGroupCount upsert
 */
export type SeasonAgeGroupCountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountInclude<ExtArgs> | null
  /**
   * The filter to search for the SeasonAgeGroupCount to update in case it exists.
   */
  where: Prisma.SeasonAgeGroupCountWhereUniqueInput
  /**
   * In case the SeasonAgeGroupCount found by the `where` argument doesn't exist, create a new SeasonAgeGroupCount with this data.
   */
  create: Prisma.XOR<Prisma.SeasonAgeGroupCountCreateInput, Prisma.SeasonAgeGroupCountUncheckedCreateInput>
  /**
   * In case the SeasonAgeGroupCount was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SeasonAgeGroupCountUpdateInput, Prisma.SeasonAgeGroupCountUncheckedUpdateInput>
}

/**
 * SeasonAgeGroupCount delete
 */
export type SeasonAgeGroupCountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountInclude<ExtArgs> | null
  /**
   * Filter which SeasonAgeGroupCount to delete.
   */
  where: Prisma.SeasonAgeGroupCountWhereUniqueInput
}

/**
 * SeasonAgeGroupCount deleteMany
 */
export type SeasonAgeGroupCountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SeasonAgeGroupCounts to delete
   */
  where?: Prisma.SeasonAgeGroupCountWhereInput
  /**
   * Limit how many SeasonAgeGroupCounts to delete.
   */
  limit?: number
}

/**
 * SeasonAgeGroupCount without action
 */
export type SeasonAgeGroupCountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeasonAgeGroupCount
   */
  select?: Prisma.SeasonAgeGroupCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeasonAgeGroupCount
   */
  omit?: Prisma.SeasonAgeGroupCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeasonAgeGroupCountInclude<ExtArgs> | null
}
