
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserMutedLabel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UserMutedLabel
 * 
 */
export type UserMutedLabelModel = runtime.Types.Result.DefaultSelection<Prisma.$UserMutedLabelPayload>

export type AggregateUserMutedLabel = {
  _count: UserMutedLabelCountAggregateOutputType | null
  _min: UserMutedLabelMinAggregateOutputType | null
  _max: UserMutedLabelMaxAggregateOutputType | null
}

export type UserMutedLabelMinAggregateOutputType = {
  userId: string | null
  labelId: string | null
}

export type UserMutedLabelMaxAggregateOutputType = {
  userId: string | null
  labelId: string | null
}

export type UserMutedLabelCountAggregateOutputType = {
  userId: number
  labelId: number
  _all: number
}


export type UserMutedLabelMinAggregateInputType = {
  userId?: true
  labelId?: true
}

export type UserMutedLabelMaxAggregateInputType = {
  userId?: true
  labelId?: true
}

export type UserMutedLabelCountAggregateInputType = {
  userId?: true
  labelId?: true
  _all?: true
}

export type UserMutedLabelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserMutedLabel to aggregate.
   */
  where?: Prisma.UserMutedLabelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserMutedLabels to fetch.
   */
  orderBy?: Prisma.UserMutedLabelOrderByWithRelationInput | Prisma.UserMutedLabelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserMutedLabelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserMutedLabels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserMutedLabels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserMutedLabels
  **/
  _count?: true | UserMutedLabelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMutedLabelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMutedLabelMaxAggregateInputType
}

export type GetUserMutedLabelAggregateType<T extends UserMutedLabelAggregateArgs> = {
      [P in keyof T & keyof AggregateUserMutedLabel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserMutedLabel[P]>
    : Prisma.GetScalarType<T[P], AggregateUserMutedLabel[P]>
}




export type UserMutedLabelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserMutedLabelWhereInput
  orderBy?: Prisma.UserMutedLabelOrderByWithAggregationInput | Prisma.UserMutedLabelOrderByWithAggregationInput[]
  by: Prisma.UserMutedLabelScalarFieldEnum[] | Prisma.UserMutedLabelScalarFieldEnum
  having?: Prisma.UserMutedLabelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserMutedLabelCountAggregateInputType | true
  _min?: UserMutedLabelMinAggregateInputType
  _max?: UserMutedLabelMaxAggregateInputType
}

export type UserMutedLabelGroupByOutputType = {
  userId: string
  labelId: string
  _count: UserMutedLabelCountAggregateOutputType | null
  _min: UserMutedLabelMinAggregateOutputType | null
  _max: UserMutedLabelMaxAggregateOutputType | null
}

export type GetUserMutedLabelGroupByPayload<T extends UserMutedLabelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserMutedLabelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserMutedLabelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserMutedLabelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserMutedLabelGroupByOutputType[P]>
      }
    >
  >



export type UserMutedLabelWhereInput = {
  AND?: Prisma.UserMutedLabelWhereInput | Prisma.UserMutedLabelWhereInput[]
  OR?: Prisma.UserMutedLabelWhereInput[]
  NOT?: Prisma.UserMutedLabelWhereInput | Prisma.UserMutedLabelWhereInput[]
  userId?: Prisma.StringFilter<"UserMutedLabel"> | string
  labelId?: Prisma.StringFilter<"UserMutedLabel"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  label?: Prisma.XOR<Prisma.LabelScalarRelationFilter, Prisma.LabelWhereInput>
}

export type UserMutedLabelOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  labelId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  label?: Prisma.LabelOrderByWithRelationInput
}

export type UserMutedLabelWhereUniqueInput = Prisma.AtLeast<{
  userId_labelId?: Prisma.UserMutedLabelUserIdLabelIdCompoundUniqueInput
  AND?: Prisma.UserMutedLabelWhereInput | Prisma.UserMutedLabelWhereInput[]
  OR?: Prisma.UserMutedLabelWhereInput[]
  NOT?: Prisma.UserMutedLabelWhereInput | Prisma.UserMutedLabelWhereInput[]
  userId?: Prisma.StringFilter<"UserMutedLabel"> | string
  labelId?: Prisma.StringFilter<"UserMutedLabel"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  label?: Prisma.XOR<Prisma.LabelScalarRelationFilter, Prisma.LabelWhereInput>
}, "userId_labelId">

export type UserMutedLabelOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  labelId?: Prisma.SortOrder
  _count?: Prisma.UserMutedLabelCountOrderByAggregateInput
  _max?: Prisma.UserMutedLabelMaxOrderByAggregateInput
  _min?: Prisma.UserMutedLabelMinOrderByAggregateInput
}

export type UserMutedLabelScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserMutedLabelScalarWhereWithAggregatesInput | Prisma.UserMutedLabelScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserMutedLabelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserMutedLabelScalarWhereWithAggregatesInput | Prisma.UserMutedLabelScalarWhereWithAggregatesInput[]
  userId?: Prisma.StringWithAggregatesFilter<"UserMutedLabel"> | string
  labelId?: Prisma.StringWithAggregatesFilter<"UserMutedLabel"> | string
}

export type UserMutedLabelCreateInput = {
  user: Prisma.UserCreateNestedOneWithoutMutedLabelsInput
  label: Prisma.LabelCreateNestedOneWithoutMutedByInput
}

export type UserMutedLabelUncheckedCreateInput = {
  userId: string
  labelId: string
}

export type UserMutedLabelUpdateInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutMutedLabelsNestedInput
  label?: Prisma.LabelUpdateOneRequiredWithoutMutedByNestedInput
}

export type UserMutedLabelUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  labelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserMutedLabelCreateManyInput = {
  userId: string
  labelId: string
}

export type UserMutedLabelUpdateManyMutationInput = {

}

export type UserMutedLabelUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  labelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserMutedLabelListRelationFilter = {
  every?: Prisma.UserMutedLabelWhereInput
  some?: Prisma.UserMutedLabelWhereInput
  none?: Prisma.UserMutedLabelWhereInput
}

export type UserMutedLabelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserMutedLabelUserIdLabelIdCompoundUniqueInput = {
  userId: string
  labelId: string
}

export type UserMutedLabelCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  labelId?: Prisma.SortOrder
}

export type UserMutedLabelMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  labelId?: Prisma.SortOrder
}

export type UserMutedLabelMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  labelId?: Prisma.SortOrder
}

export type UserMutedLabelCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutUserInput, Prisma.UserMutedLabelUncheckedCreateWithoutUserInput> | Prisma.UserMutedLabelCreateWithoutUserInput[] | Prisma.UserMutedLabelUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserMutedLabelCreateOrConnectWithoutUserInput | Prisma.UserMutedLabelCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserMutedLabelCreateManyUserInputEnvelope
  connect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
}

export type UserMutedLabelUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutUserInput, Prisma.UserMutedLabelUncheckedCreateWithoutUserInput> | Prisma.UserMutedLabelCreateWithoutUserInput[] | Prisma.UserMutedLabelUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserMutedLabelCreateOrConnectWithoutUserInput | Prisma.UserMutedLabelCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserMutedLabelCreateManyUserInputEnvelope
  connect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
}

export type UserMutedLabelUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutUserInput, Prisma.UserMutedLabelUncheckedCreateWithoutUserInput> | Prisma.UserMutedLabelCreateWithoutUserInput[] | Prisma.UserMutedLabelUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserMutedLabelCreateOrConnectWithoutUserInput | Prisma.UserMutedLabelCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserMutedLabelUpsertWithWhereUniqueWithoutUserInput | Prisma.UserMutedLabelUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserMutedLabelCreateManyUserInputEnvelope
  set?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  disconnect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  delete?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  connect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  update?: Prisma.UserMutedLabelUpdateWithWhereUniqueWithoutUserInput | Prisma.UserMutedLabelUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserMutedLabelUpdateManyWithWhereWithoutUserInput | Prisma.UserMutedLabelUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserMutedLabelScalarWhereInput | Prisma.UserMutedLabelScalarWhereInput[]
}

export type UserMutedLabelUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutUserInput, Prisma.UserMutedLabelUncheckedCreateWithoutUserInput> | Prisma.UserMutedLabelCreateWithoutUserInput[] | Prisma.UserMutedLabelUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserMutedLabelCreateOrConnectWithoutUserInput | Prisma.UserMutedLabelCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserMutedLabelUpsertWithWhereUniqueWithoutUserInput | Prisma.UserMutedLabelUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserMutedLabelCreateManyUserInputEnvelope
  set?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  disconnect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  delete?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  connect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  update?: Prisma.UserMutedLabelUpdateWithWhereUniqueWithoutUserInput | Prisma.UserMutedLabelUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserMutedLabelUpdateManyWithWhereWithoutUserInput | Prisma.UserMutedLabelUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserMutedLabelScalarWhereInput | Prisma.UserMutedLabelScalarWhereInput[]
}

export type UserMutedLabelCreateNestedManyWithoutLabelInput = {
  create?: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutLabelInput, Prisma.UserMutedLabelUncheckedCreateWithoutLabelInput> | Prisma.UserMutedLabelCreateWithoutLabelInput[] | Prisma.UserMutedLabelUncheckedCreateWithoutLabelInput[]
  connectOrCreate?: Prisma.UserMutedLabelCreateOrConnectWithoutLabelInput | Prisma.UserMutedLabelCreateOrConnectWithoutLabelInput[]
  createMany?: Prisma.UserMutedLabelCreateManyLabelInputEnvelope
  connect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
}

export type UserMutedLabelUncheckedCreateNestedManyWithoutLabelInput = {
  create?: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutLabelInput, Prisma.UserMutedLabelUncheckedCreateWithoutLabelInput> | Prisma.UserMutedLabelCreateWithoutLabelInput[] | Prisma.UserMutedLabelUncheckedCreateWithoutLabelInput[]
  connectOrCreate?: Prisma.UserMutedLabelCreateOrConnectWithoutLabelInput | Prisma.UserMutedLabelCreateOrConnectWithoutLabelInput[]
  createMany?: Prisma.UserMutedLabelCreateManyLabelInputEnvelope
  connect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
}

export type UserMutedLabelUpdateManyWithoutLabelNestedInput = {
  create?: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutLabelInput, Prisma.UserMutedLabelUncheckedCreateWithoutLabelInput> | Prisma.UserMutedLabelCreateWithoutLabelInput[] | Prisma.UserMutedLabelUncheckedCreateWithoutLabelInput[]
  connectOrCreate?: Prisma.UserMutedLabelCreateOrConnectWithoutLabelInput | Prisma.UserMutedLabelCreateOrConnectWithoutLabelInput[]
  upsert?: Prisma.UserMutedLabelUpsertWithWhereUniqueWithoutLabelInput | Prisma.UserMutedLabelUpsertWithWhereUniqueWithoutLabelInput[]
  createMany?: Prisma.UserMutedLabelCreateManyLabelInputEnvelope
  set?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  disconnect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  delete?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  connect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  update?: Prisma.UserMutedLabelUpdateWithWhereUniqueWithoutLabelInput | Prisma.UserMutedLabelUpdateWithWhereUniqueWithoutLabelInput[]
  updateMany?: Prisma.UserMutedLabelUpdateManyWithWhereWithoutLabelInput | Prisma.UserMutedLabelUpdateManyWithWhereWithoutLabelInput[]
  deleteMany?: Prisma.UserMutedLabelScalarWhereInput | Prisma.UserMutedLabelScalarWhereInput[]
}

export type UserMutedLabelUncheckedUpdateManyWithoutLabelNestedInput = {
  create?: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutLabelInput, Prisma.UserMutedLabelUncheckedCreateWithoutLabelInput> | Prisma.UserMutedLabelCreateWithoutLabelInput[] | Prisma.UserMutedLabelUncheckedCreateWithoutLabelInput[]
  connectOrCreate?: Prisma.UserMutedLabelCreateOrConnectWithoutLabelInput | Prisma.UserMutedLabelCreateOrConnectWithoutLabelInput[]
  upsert?: Prisma.UserMutedLabelUpsertWithWhereUniqueWithoutLabelInput | Prisma.UserMutedLabelUpsertWithWhereUniqueWithoutLabelInput[]
  createMany?: Prisma.UserMutedLabelCreateManyLabelInputEnvelope
  set?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  disconnect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  delete?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  connect?: Prisma.UserMutedLabelWhereUniqueInput | Prisma.UserMutedLabelWhereUniqueInput[]
  update?: Prisma.UserMutedLabelUpdateWithWhereUniqueWithoutLabelInput | Prisma.UserMutedLabelUpdateWithWhereUniqueWithoutLabelInput[]
  updateMany?: Prisma.UserMutedLabelUpdateManyWithWhereWithoutLabelInput | Prisma.UserMutedLabelUpdateManyWithWhereWithoutLabelInput[]
  deleteMany?: Prisma.UserMutedLabelScalarWhereInput | Prisma.UserMutedLabelScalarWhereInput[]
}

export type UserMutedLabelCreateWithoutUserInput = {
  label: Prisma.LabelCreateNestedOneWithoutMutedByInput
}

export type UserMutedLabelUncheckedCreateWithoutUserInput = {
  labelId: string
}

export type UserMutedLabelCreateOrConnectWithoutUserInput = {
  where: Prisma.UserMutedLabelWhereUniqueInput
  create: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutUserInput, Prisma.UserMutedLabelUncheckedCreateWithoutUserInput>
}

export type UserMutedLabelCreateManyUserInputEnvelope = {
  data: Prisma.UserMutedLabelCreateManyUserInput | Prisma.UserMutedLabelCreateManyUserInput[]
}

export type UserMutedLabelUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserMutedLabelWhereUniqueInput
  update: Prisma.XOR<Prisma.UserMutedLabelUpdateWithoutUserInput, Prisma.UserMutedLabelUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutUserInput, Prisma.UserMutedLabelUncheckedCreateWithoutUserInput>
}

export type UserMutedLabelUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserMutedLabelWhereUniqueInput
  data: Prisma.XOR<Prisma.UserMutedLabelUpdateWithoutUserInput, Prisma.UserMutedLabelUncheckedUpdateWithoutUserInput>
}

export type UserMutedLabelUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserMutedLabelScalarWhereInput
  data: Prisma.XOR<Prisma.UserMutedLabelUpdateManyMutationInput, Prisma.UserMutedLabelUncheckedUpdateManyWithoutUserInput>
}

export type UserMutedLabelScalarWhereInput = {
  AND?: Prisma.UserMutedLabelScalarWhereInput | Prisma.UserMutedLabelScalarWhereInput[]
  OR?: Prisma.UserMutedLabelScalarWhereInput[]
  NOT?: Prisma.UserMutedLabelScalarWhereInput | Prisma.UserMutedLabelScalarWhereInput[]
  userId?: Prisma.StringFilter<"UserMutedLabel"> | string
  labelId?: Prisma.StringFilter<"UserMutedLabel"> | string
}

export type UserMutedLabelCreateWithoutLabelInput = {
  user: Prisma.UserCreateNestedOneWithoutMutedLabelsInput
}

export type UserMutedLabelUncheckedCreateWithoutLabelInput = {
  userId: string
}

export type UserMutedLabelCreateOrConnectWithoutLabelInput = {
  where: Prisma.UserMutedLabelWhereUniqueInput
  create: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutLabelInput, Prisma.UserMutedLabelUncheckedCreateWithoutLabelInput>
}

export type UserMutedLabelCreateManyLabelInputEnvelope = {
  data: Prisma.UserMutedLabelCreateManyLabelInput | Prisma.UserMutedLabelCreateManyLabelInput[]
}

export type UserMutedLabelUpsertWithWhereUniqueWithoutLabelInput = {
  where: Prisma.UserMutedLabelWhereUniqueInput
  update: Prisma.XOR<Prisma.UserMutedLabelUpdateWithoutLabelInput, Prisma.UserMutedLabelUncheckedUpdateWithoutLabelInput>
  create: Prisma.XOR<Prisma.UserMutedLabelCreateWithoutLabelInput, Prisma.UserMutedLabelUncheckedCreateWithoutLabelInput>
}

export type UserMutedLabelUpdateWithWhereUniqueWithoutLabelInput = {
  where: Prisma.UserMutedLabelWhereUniqueInput
  data: Prisma.XOR<Prisma.UserMutedLabelUpdateWithoutLabelInput, Prisma.UserMutedLabelUncheckedUpdateWithoutLabelInput>
}

export type UserMutedLabelUpdateManyWithWhereWithoutLabelInput = {
  where: Prisma.UserMutedLabelScalarWhereInput
  data: Prisma.XOR<Prisma.UserMutedLabelUpdateManyMutationInput, Prisma.UserMutedLabelUncheckedUpdateManyWithoutLabelInput>
}

export type UserMutedLabelCreateManyUserInput = {
  labelId: string
}

export type UserMutedLabelUpdateWithoutUserInput = {
  label?: Prisma.LabelUpdateOneRequiredWithoutMutedByNestedInput
}

export type UserMutedLabelUncheckedUpdateWithoutUserInput = {
  labelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserMutedLabelUncheckedUpdateManyWithoutUserInput = {
  labelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserMutedLabelCreateManyLabelInput = {
  userId: string
}

export type UserMutedLabelUpdateWithoutLabelInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutMutedLabelsNestedInput
}

export type UserMutedLabelUncheckedUpdateWithoutLabelInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserMutedLabelUncheckedUpdateManyWithoutLabelInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type UserMutedLabelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  labelId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  label?: boolean | Prisma.LabelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userMutedLabel"]>

export type UserMutedLabelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  labelId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  label?: boolean | Prisma.LabelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userMutedLabel"]>

export type UserMutedLabelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  labelId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  label?: boolean | Prisma.LabelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userMutedLabel"]>

export type UserMutedLabelSelectScalar = {
  userId?: boolean
  labelId?: boolean
}

export type UserMutedLabelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "labelId", ExtArgs["result"]["userMutedLabel"]>
export type UserMutedLabelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  label?: boolean | Prisma.LabelDefaultArgs<ExtArgs>
}
export type UserMutedLabelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  label?: boolean | Prisma.LabelDefaultArgs<ExtArgs>
}
export type UserMutedLabelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  label?: boolean | Prisma.LabelDefaultArgs<ExtArgs>
}

export type $UserMutedLabelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserMutedLabel"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    label: Prisma.$LabelPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: string
    labelId: string
  }, ExtArgs["result"]["userMutedLabel"]>
  composites: {}
}

export type UserMutedLabelGetPayload<S extends boolean | null | undefined | UserMutedLabelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload, S>

export type UserMutedLabelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserMutedLabelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserMutedLabelCountAggregateInputType | true
  }

export interface UserMutedLabelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserMutedLabel'], meta: { name: 'UserMutedLabel' } }
  /**
   * Find zero or one UserMutedLabel that matches the filter.
   * @param {UserMutedLabelFindUniqueArgs} args - Arguments to find a UserMutedLabel
   * @example
   * // Get one UserMutedLabel
   * const userMutedLabel = await prisma.userMutedLabel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserMutedLabelFindUniqueArgs>(args: Prisma.SelectSubset<T, UserMutedLabelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserMutedLabelClient<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserMutedLabel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserMutedLabelFindUniqueOrThrowArgs} args - Arguments to find a UserMutedLabel
   * @example
   * // Get one UserMutedLabel
   * const userMutedLabel = await prisma.userMutedLabel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserMutedLabelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserMutedLabelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserMutedLabelClient<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserMutedLabel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMutedLabelFindFirstArgs} args - Arguments to find a UserMutedLabel
   * @example
   * // Get one UserMutedLabel
   * const userMutedLabel = await prisma.userMutedLabel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserMutedLabelFindFirstArgs>(args?: Prisma.SelectSubset<T, UserMutedLabelFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserMutedLabelClient<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserMutedLabel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMutedLabelFindFirstOrThrowArgs} args - Arguments to find a UserMutedLabel
   * @example
   * // Get one UserMutedLabel
   * const userMutedLabel = await prisma.userMutedLabel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserMutedLabelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserMutedLabelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserMutedLabelClient<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserMutedLabels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMutedLabelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserMutedLabels
   * const userMutedLabels = await prisma.userMutedLabel.findMany()
   * 
   * // Get first 10 UserMutedLabels
   * const userMutedLabels = await prisma.userMutedLabel.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const userMutedLabelWithUserIdOnly = await prisma.userMutedLabel.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends UserMutedLabelFindManyArgs>(args?: Prisma.SelectSubset<T, UserMutedLabelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserMutedLabel.
   * @param {UserMutedLabelCreateArgs} args - Arguments to create a UserMutedLabel.
   * @example
   * // Create one UserMutedLabel
   * const UserMutedLabel = await prisma.userMutedLabel.create({
   *   data: {
   *     // ... data to create a UserMutedLabel
   *   }
   * })
   * 
   */
  create<T extends UserMutedLabelCreateArgs>(args: Prisma.SelectSubset<T, UserMutedLabelCreateArgs<ExtArgs>>): Prisma.Prisma__UserMutedLabelClient<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserMutedLabels.
   * @param {UserMutedLabelCreateManyArgs} args - Arguments to create many UserMutedLabels.
   * @example
   * // Create many UserMutedLabels
   * const userMutedLabel = await prisma.userMutedLabel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserMutedLabelCreateManyArgs>(args?: Prisma.SelectSubset<T, UserMutedLabelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserMutedLabels and returns the data saved in the database.
   * @param {UserMutedLabelCreateManyAndReturnArgs} args - Arguments to create many UserMutedLabels.
   * @example
   * // Create many UserMutedLabels
   * const userMutedLabel = await prisma.userMutedLabel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserMutedLabels and only return the `userId`
   * const userMutedLabelWithUserIdOnly = await prisma.userMutedLabel.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserMutedLabelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserMutedLabelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserMutedLabel.
   * @param {UserMutedLabelDeleteArgs} args - Arguments to delete one UserMutedLabel.
   * @example
   * // Delete one UserMutedLabel
   * const UserMutedLabel = await prisma.userMutedLabel.delete({
   *   where: {
   *     // ... filter to delete one UserMutedLabel
   *   }
   * })
   * 
   */
  delete<T extends UserMutedLabelDeleteArgs>(args: Prisma.SelectSubset<T, UserMutedLabelDeleteArgs<ExtArgs>>): Prisma.Prisma__UserMutedLabelClient<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserMutedLabel.
   * @param {UserMutedLabelUpdateArgs} args - Arguments to update one UserMutedLabel.
   * @example
   * // Update one UserMutedLabel
   * const userMutedLabel = await prisma.userMutedLabel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserMutedLabelUpdateArgs>(args: Prisma.SelectSubset<T, UserMutedLabelUpdateArgs<ExtArgs>>): Prisma.Prisma__UserMutedLabelClient<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserMutedLabels.
   * @param {UserMutedLabelDeleteManyArgs} args - Arguments to filter UserMutedLabels to delete.
   * @example
   * // Delete a few UserMutedLabels
   * const { count } = await prisma.userMutedLabel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserMutedLabelDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserMutedLabelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserMutedLabels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMutedLabelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserMutedLabels
   * const userMutedLabel = await prisma.userMutedLabel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserMutedLabelUpdateManyArgs>(args: Prisma.SelectSubset<T, UserMutedLabelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserMutedLabels and returns the data updated in the database.
   * @param {UserMutedLabelUpdateManyAndReturnArgs} args - Arguments to update many UserMutedLabels.
   * @example
   * // Update many UserMutedLabels
   * const userMutedLabel = await prisma.userMutedLabel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserMutedLabels and only return the `userId`
   * const userMutedLabelWithUserIdOnly = await prisma.userMutedLabel.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserMutedLabelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserMutedLabelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserMutedLabel.
   * @param {UserMutedLabelUpsertArgs} args - Arguments to update or create a UserMutedLabel.
   * @example
   * // Update or create a UserMutedLabel
   * const userMutedLabel = await prisma.userMutedLabel.upsert({
   *   create: {
   *     // ... data to create a UserMutedLabel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserMutedLabel we want to update
   *   }
   * })
   */
  upsert<T extends UserMutedLabelUpsertArgs>(args: Prisma.SelectSubset<T, UserMutedLabelUpsertArgs<ExtArgs>>): Prisma.Prisma__UserMutedLabelClient<runtime.Types.Result.GetResult<Prisma.$UserMutedLabelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserMutedLabels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMutedLabelCountArgs} args - Arguments to filter UserMutedLabels to count.
   * @example
   * // Count the number of UserMutedLabels
   * const count = await prisma.userMutedLabel.count({
   *   where: {
   *     // ... the filter for the UserMutedLabels we want to count
   *   }
   * })
  **/
  count<T extends UserMutedLabelCountArgs>(
    args?: Prisma.Subset<T, UserMutedLabelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserMutedLabelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserMutedLabel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMutedLabelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserMutedLabelAggregateArgs>(args: Prisma.Subset<T, UserMutedLabelAggregateArgs>): Prisma.PrismaPromise<GetUserMutedLabelAggregateType<T>>

  /**
   * Group by UserMutedLabel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMutedLabelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserMutedLabelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserMutedLabelGroupByArgs['orderBy'] }
      : { orderBy?: UserMutedLabelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserMutedLabelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserMutedLabelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserMutedLabel model
 */
readonly fields: UserMutedLabelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserMutedLabel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserMutedLabelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  label<T extends Prisma.LabelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LabelDefaultArgs<ExtArgs>>): Prisma.Prisma__LabelClient<runtime.Types.Result.GetResult<Prisma.$LabelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserMutedLabel model
 */
export interface UserMutedLabelFieldRefs {
  readonly userId: Prisma.FieldRef<"UserMutedLabel", 'String'>
  readonly labelId: Prisma.FieldRef<"UserMutedLabel", 'String'>
}
    

// Custom InputTypes
/**
 * UserMutedLabel findUnique
 */
export type UserMutedLabelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelInclude<ExtArgs> | null
  /**
   * Filter, which UserMutedLabel to fetch.
   */
  where: Prisma.UserMutedLabelWhereUniqueInput
}

/**
 * UserMutedLabel findUniqueOrThrow
 */
export type UserMutedLabelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelInclude<ExtArgs> | null
  /**
   * Filter, which UserMutedLabel to fetch.
   */
  where: Prisma.UserMutedLabelWhereUniqueInput
}

/**
 * UserMutedLabel findFirst
 */
export type UserMutedLabelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelInclude<ExtArgs> | null
  /**
   * Filter, which UserMutedLabel to fetch.
   */
  where?: Prisma.UserMutedLabelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserMutedLabels to fetch.
   */
  orderBy?: Prisma.UserMutedLabelOrderByWithRelationInput | Prisma.UserMutedLabelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserMutedLabels.
   */
  cursor?: Prisma.UserMutedLabelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserMutedLabels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserMutedLabels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserMutedLabels.
   */
  distinct?: Prisma.UserMutedLabelScalarFieldEnum | Prisma.UserMutedLabelScalarFieldEnum[]
}

/**
 * UserMutedLabel findFirstOrThrow
 */
export type UserMutedLabelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelInclude<ExtArgs> | null
  /**
   * Filter, which UserMutedLabel to fetch.
   */
  where?: Prisma.UserMutedLabelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserMutedLabels to fetch.
   */
  orderBy?: Prisma.UserMutedLabelOrderByWithRelationInput | Prisma.UserMutedLabelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserMutedLabels.
   */
  cursor?: Prisma.UserMutedLabelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserMutedLabels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserMutedLabels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserMutedLabels.
   */
  distinct?: Prisma.UserMutedLabelScalarFieldEnum | Prisma.UserMutedLabelScalarFieldEnum[]
}

/**
 * UserMutedLabel findMany
 */
export type UserMutedLabelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelInclude<ExtArgs> | null
  /**
   * Filter, which UserMutedLabels to fetch.
   */
  where?: Prisma.UserMutedLabelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserMutedLabels to fetch.
   */
  orderBy?: Prisma.UserMutedLabelOrderByWithRelationInput | Prisma.UserMutedLabelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserMutedLabels.
   */
  cursor?: Prisma.UserMutedLabelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserMutedLabels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserMutedLabels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserMutedLabels.
   */
  distinct?: Prisma.UserMutedLabelScalarFieldEnum | Prisma.UserMutedLabelScalarFieldEnum[]
}

/**
 * UserMutedLabel create
 */
export type UserMutedLabelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelInclude<ExtArgs> | null
  /**
   * The data needed to create a UserMutedLabel.
   */
  data: Prisma.XOR<Prisma.UserMutedLabelCreateInput, Prisma.UserMutedLabelUncheckedCreateInput>
}

/**
 * UserMutedLabel createMany
 */
export type UserMutedLabelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserMutedLabels.
   */
  data: Prisma.UserMutedLabelCreateManyInput | Prisma.UserMutedLabelCreateManyInput[]
}

/**
 * UserMutedLabel createManyAndReturn
 */
export type UserMutedLabelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * The data used to create many UserMutedLabels.
   */
  data: Prisma.UserMutedLabelCreateManyInput | Prisma.UserMutedLabelCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserMutedLabel update
 */
export type UserMutedLabelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelInclude<ExtArgs> | null
  /**
   * The data needed to update a UserMutedLabel.
   */
  data: Prisma.XOR<Prisma.UserMutedLabelUpdateInput, Prisma.UserMutedLabelUncheckedUpdateInput>
  /**
   * Choose, which UserMutedLabel to update.
   */
  where: Prisma.UserMutedLabelWhereUniqueInput
}

/**
 * UserMutedLabel updateMany
 */
export type UserMutedLabelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserMutedLabels.
   */
  data: Prisma.XOR<Prisma.UserMutedLabelUpdateManyMutationInput, Prisma.UserMutedLabelUncheckedUpdateManyInput>
  /**
   * Filter which UserMutedLabels to update
   */
  where?: Prisma.UserMutedLabelWhereInput
  /**
   * Limit how many UserMutedLabels to update.
   */
  limit?: number
}

/**
 * UserMutedLabel updateManyAndReturn
 */
export type UserMutedLabelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * The data used to update UserMutedLabels.
   */
  data: Prisma.XOR<Prisma.UserMutedLabelUpdateManyMutationInput, Prisma.UserMutedLabelUncheckedUpdateManyInput>
  /**
   * Filter which UserMutedLabels to update
   */
  where?: Prisma.UserMutedLabelWhereInput
  /**
   * Limit how many UserMutedLabels to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserMutedLabel upsert
 */
export type UserMutedLabelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelInclude<ExtArgs> | null
  /**
   * The filter to search for the UserMutedLabel to update in case it exists.
   */
  where: Prisma.UserMutedLabelWhereUniqueInput
  /**
   * In case the UserMutedLabel found by the `where` argument doesn't exist, create a new UserMutedLabel with this data.
   */
  create: Prisma.XOR<Prisma.UserMutedLabelCreateInput, Prisma.UserMutedLabelUncheckedCreateInput>
  /**
   * In case the UserMutedLabel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserMutedLabelUpdateInput, Prisma.UserMutedLabelUncheckedUpdateInput>
}

/**
 * UserMutedLabel delete
 */
export type UserMutedLabelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelInclude<ExtArgs> | null
  /**
   * Filter which UserMutedLabel to delete.
   */
  where: Prisma.UserMutedLabelWhereUniqueInput
}

/**
 * UserMutedLabel deleteMany
 */
export type UserMutedLabelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserMutedLabels to delete
   */
  where?: Prisma.UserMutedLabelWhereInput
  /**
   * Limit how many UserMutedLabels to delete.
   */
  limit?: number
}

/**
 * UserMutedLabel without action
 */
export type UserMutedLabelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMutedLabel
   */
  select?: Prisma.UserMutedLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMutedLabel
   */
  omit?: Prisma.UserMutedLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMutedLabelInclude<ExtArgs> | null
}
