
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  userName: string | null
  password: string | null
  name: string | null
  role: $Enums.Role | null
  feedId: string | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  userName: string | null
  password: string | null
  name: string | null
  role: $Enums.Role | null
  feedId: string | null
}

export type UserCountAggregateOutputType = {
  id: number
  userName: number
  password: number
  name: number
  role: number
  feedId: number
  _all: number
}


export type UserMinAggregateInputType = {
  id?: true
  userName?: true
  password?: true
  name?: true
  role?: true
  feedId?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  userName?: true
  password?: true
  name?: true
  role?: true
  feedId?: true
}

export type UserCountAggregateInputType = {
  id?: true
  userName?: true
  password?: true
  name?: true
  role?: true
  feedId?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  userName: string
  password: string | null
  name: string
  role: $Enums.Role
  feedId: string
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  userName?: Prisma.StringFilter<"User"> | string
  password?: Prisma.StringNullableFilter<"User"> | string | null
  name?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  feedId?: Prisma.StringFilter<"User"> | string
  invitation?: Prisma.XOR<Prisma.UserInvitationNullableScalarRelationFilter, Prisma.UserInvitationWhereInput> | null
  responses?: Prisma.ResponseListRelationFilter
  subscriptions?: Prisma.SubscriptionListRelationFilter
  notificationSettings?: Prisma.NotificationSettingsListRelationFilter
  passwordReset?: Prisma.XOR<Prisma.PasswordResetNullableScalarRelationFilter, Prisma.PasswordResetWhereInput> | null
  feedConfig?: Prisma.XOR<Prisma.FeedConfigNullableScalarRelationFilter, Prisma.FeedConfigWhereInput> | null
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  role?: Prisma.SortOrder
  feedId?: Prisma.SortOrder
  invitation?: Prisma.UserInvitationOrderByWithRelationInput
  responses?: Prisma.ResponseOrderByRelationAggregateInput
  subscriptions?: Prisma.SubscriptionOrderByRelationAggregateInput
  notificationSettings?: Prisma.NotificationSettingsOrderByRelationAggregateInput
  passwordReset?: Prisma.PasswordResetOrderByWithRelationInput
  feedConfig?: Prisma.FeedConfigOrderByWithRelationInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userName?: string
  feedId?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  password?: Prisma.StringNullableFilter<"User"> | string | null
  name?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  invitation?: Prisma.XOR<Prisma.UserInvitationNullableScalarRelationFilter, Prisma.UserInvitationWhereInput> | null
  responses?: Prisma.ResponseListRelationFilter
  subscriptions?: Prisma.SubscriptionListRelationFilter
  notificationSettings?: Prisma.NotificationSettingsListRelationFilter
  passwordReset?: Prisma.XOR<Prisma.PasswordResetNullableScalarRelationFilter, Prisma.PasswordResetWhereInput> | null
  feedConfig?: Prisma.XOR<Prisma.FeedConfigNullableScalarRelationFilter, Prisma.FeedConfigWhereInput> | null
}, "id" | "userName" | "feedId">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  role?: Prisma.SortOrder
  feedId?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  userName?: Prisma.StringWithAggregatesFilter<"User"> | string
  password?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  name?: Prisma.StringWithAggregatesFilter<"User"> | string
  role?: Prisma.EnumRoleWithAggregatesFilter<"User"> | $Enums.Role
  feedId?: Prisma.StringWithAggregatesFilter<"User"> | string
}

export type UserCreateInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationCreateNestedOneWithoutUserInput
  responses?: Prisma.ResponseCreateNestedManyWithoutUserInput
  subscriptions?: Prisma.SubscriptionCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetCreateNestedOneWithoutUserInput
  feedConfig?: Prisma.FeedConfigCreateNestedOneWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationUncheckedCreateNestedOneWithoutUserInput
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutUserInput
  subscriptions?: Prisma.SubscriptionUncheckedCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetUncheckedCreateNestedOneWithoutUserInput
  feedConfig?: Prisma.FeedConfigUncheckedCreateNestedOneWithoutUserInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUpdateOneWithoutUserNestedInput
  responses?: Prisma.ResponseUpdateManyWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUpdateOneWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUpdateOneWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUncheckedUpdateOneWithoutUserNestedInput
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUncheckedUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUncheckedUpdateOneWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUncheckedUpdateOneWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  password?: Prisma.SortOrder
  name?: Prisma.SortOrder
  role?: Prisma.SortOrder
  feedId?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  password?: Prisma.SortOrder
  name?: Prisma.SortOrder
  role?: Prisma.SortOrder
  feedId?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  password?: Prisma.SortOrder
  name?: Prisma.SortOrder
  role?: Prisma.SortOrder
  feedId?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type EnumRoleFieldUpdateOperationsInput = {
  set?: $Enums.Role
}

export type UserCreateNestedOneWithoutFeedConfigInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFeedConfigInput, Prisma.UserUncheckedCreateWithoutFeedConfigInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFeedConfigInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutFeedConfigNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFeedConfigInput, Prisma.UserUncheckedCreateWithoutFeedConfigInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFeedConfigInput
  upsert?: Prisma.UserUpsertWithoutFeedConfigInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutFeedConfigInput, Prisma.UserUpdateWithoutFeedConfigInput>, Prisma.UserUncheckedUpdateWithoutFeedConfigInput>
}

export type UserCreateNestedOneWithoutInvitationInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutInvitationInput, Prisma.UserUncheckedCreateWithoutInvitationInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutInvitationInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutInvitationNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutInvitationInput, Prisma.UserUncheckedCreateWithoutInvitationInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutInvitationInput
  upsert?: Prisma.UserUpsertWithoutInvitationInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutInvitationInput, Prisma.UserUpdateWithoutInvitationInput>, Prisma.UserUncheckedUpdateWithoutInvitationInput>
}

export type UserCreateNestedOneWithoutPasswordResetInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPasswordResetInput, Prisma.UserUncheckedCreateWithoutPasswordResetInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPasswordResetInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutPasswordResetNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPasswordResetInput, Prisma.UserUncheckedCreateWithoutPasswordResetInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPasswordResetInput
  upsert?: Prisma.UserUpsertWithoutPasswordResetInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutPasswordResetInput, Prisma.UserUpdateWithoutPasswordResetInput>, Prisma.UserUncheckedUpdateWithoutPasswordResetInput>
}

export type UserCreateNestedOneWithoutResponsesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutResponsesInput, Prisma.UserUncheckedCreateWithoutResponsesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutResponsesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutResponsesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutResponsesInput, Prisma.UserUncheckedCreateWithoutResponsesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutResponsesInput
  upsert?: Prisma.UserUpsertWithoutResponsesInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutResponsesInput, Prisma.UserUpdateWithoutResponsesInput>, Prisma.UserUncheckedUpdateWithoutResponsesInput>
}

export type UserCreateNestedOneWithoutSubscriptionsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSubscriptionsInput, Prisma.UserUncheckedCreateWithoutSubscriptionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSubscriptionsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutSubscriptionsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSubscriptionsInput, Prisma.UserUncheckedCreateWithoutSubscriptionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSubscriptionsInput
  upsert?: Prisma.UserUpsertWithoutSubscriptionsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutSubscriptionsInput, Prisma.UserUpdateWithoutSubscriptionsInput>, Prisma.UserUncheckedUpdateWithoutSubscriptionsInput>
}

export type UserCreateNestedOneWithoutNotificationSettingsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutNotificationSettingsInput, Prisma.UserUncheckedCreateWithoutNotificationSettingsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutNotificationSettingsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutNotificationSettingsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutNotificationSettingsInput, Prisma.UserUncheckedCreateWithoutNotificationSettingsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutNotificationSettingsInput
  upsert?: Prisma.UserUpsertWithoutNotificationSettingsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutNotificationSettingsInput, Prisma.UserUpdateWithoutNotificationSettingsInput>, Prisma.UserUncheckedUpdateWithoutNotificationSettingsInput>
}

export type UserCreateWithoutFeedConfigInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationCreateNestedOneWithoutUserInput
  responses?: Prisma.ResponseCreateNestedManyWithoutUserInput
  subscriptions?: Prisma.SubscriptionCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetCreateNestedOneWithoutUserInput
}

export type UserUncheckedCreateWithoutFeedConfigInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationUncheckedCreateNestedOneWithoutUserInput
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutUserInput
  subscriptions?: Prisma.SubscriptionUncheckedCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetUncheckedCreateNestedOneWithoutUserInput
}

export type UserCreateOrConnectWithoutFeedConfigInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutFeedConfigInput, Prisma.UserUncheckedCreateWithoutFeedConfigInput>
}

export type UserUpsertWithoutFeedConfigInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutFeedConfigInput, Prisma.UserUncheckedUpdateWithoutFeedConfigInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutFeedConfigInput, Prisma.UserUncheckedCreateWithoutFeedConfigInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutFeedConfigInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutFeedConfigInput, Prisma.UserUncheckedUpdateWithoutFeedConfigInput>
}

export type UserUpdateWithoutFeedConfigInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUpdateOneWithoutUserNestedInput
  responses?: Prisma.ResponseUpdateManyWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUpdateOneWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutFeedConfigInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUncheckedUpdateOneWithoutUserNestedInput
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUncheckedUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUncheckedUpdateOneWithoutUserNestedInput
}

export type UserCreateWithoutInvitationInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  responses?: Prisma.ResponseCreateNestedManyWithoutUserInput
  subscriptions?: Prisma.SubscriptionCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetCreateNestedOneWithoutUserInput
  feedConfig?: Prisma.FeedConfigCreateNestedOneWithoutUserInput
}

export type UserUncheckedCreateWithoutInvitationInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutUserInput
  subscriptions?: Prisma.SubscriptionUncheckedCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetUncheckedCreateNestedOneWithoutUserInput
  feedConfig?: Prisma.FeedConfigUncheckedCreateNestedOneWithoutUserInput
}

export type UserCreateOrConnectWithoutInvitationInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutInvitationInput, Prisma.UserUncheckedCreateWithoutInvitationInput>
}

export type UserUpsertWithoutInvitationInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutInvitationInput, Prisma.UserUncheckedUpdateWithoutInvitationInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutInvitationInput, Prisma.UserUncheckedCreateWithoutInvitationInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutInvitationInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutInvitationInput, Prisma.UserUncheckedUpdateWithoutInvitationInput>
}

export type UserUpdateWithoutInvitationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  responses?: Prisma.ResponseUpdateManyWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUpdateOneWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUpdateOneWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutInvitationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUncheckedUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUncheckedUpdateOneWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUncheckedUpdateOneWithoutUserNestedInput
}

export type UserCreateWithoutPasswordResetInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationCreateNestedOneWithoutUserInput
  responses?: Prisma.ResponseCreateNestedManyWithoutUserInput
  subscriptions?: Prisma.SubscriptionCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsCreateNestedManyWithoutUserInput
  feedConfig?: Prisma.FeedConfigCreateNestedOneWithoutUserInput
}

export type UserUncheckedCreateWithoutPasswordResetInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationUncheckedCreateNestedOneWithoutUserInput
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutUserInput
  subscriptions?: Prisma.SubscriptionUncheckedCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedCreateNestedManyWithoutUserInput
  feedConfig?: Prisma.FeedConfigUncheckedCreateNestedOneWithoutUserInput
}

export type UserCreateOrConnectWithoutPasswordResetInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutPasswordResetInput, Prisma.UserUncheckedCreateWithoutPasswordResetInput>
}

export type UserUpsertWithoutPasswordResetInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutPasswordResetInput, Prisma.UserUncheckedUpdateWithoutPasswordResetInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutPasswordResetInput, Prisma.UserUncheckedCreateWithoutPasswordResetInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutPasswordResetInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutPasswordResetInput, Prisma.UserUncheckedUpdateWithoutPasswordResetInput>
}

export type UserUpdateWithoutPasswordResetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUpdateOneWithoutUserNestedInput
  responses?: Prisma.ResponseUpdateManyWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUpdateManyWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUpdateOneWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutPasswordResetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUncheckedUpdateOneWithoutUserNestedInput
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUncheckedUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedUpdateManyWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUncheckedUpdateOneWithoutUserNestedInput
}

export type UserCreateWithoutResponsesInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationCreateNestedOneWithoutUserInput
  subscriptions?: Prisma.SubscriptionCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetCreateNestedOneWithoutUserInput
  feedConfig?: Prisma.FeedConfigCreateNestedOneWithoutUserInput
}

export type UserUncheckedCreateWithoutResponsesInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationUncheckedCreateNestedOneWithoutUserInput
  subscriptions?: Prisma.SubscriptionUncheckedCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetUncheckedCreateNestedOneWithoutUserInput
  feedConfig?: Prisma.FeedConfigUncheckedCreateNestedOneWithoutUserInput
}

export type UserCreateOrConnectWithoutResponsesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutResponsesInput, Prisma.UserUncheckedCreateWithoutResponsesInput>
}

export type UserUpsertWithoutResponsesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutResponsesInput, Prisma.UserUncheckedUpdateWithoutResponsesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutResponsesInput, Prisma.UserUncheckedCreateWithoutResponsesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutResponsesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutResponsesInput, Prisma.UserUncheckedUpdateWithoutResponsesInput>
}

export type UserUpdateWithoutResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUpdateOneWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUpdateOneWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUpdateOneWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUncheckedUpdateOneWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUncheckedUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUncheckedUpdateOneWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUncheckedUpdateOneWithoutUserNestedInput
}

export type UserCreateWithoutSubscriptionsInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationCreateNestedOneWithoutUserInput
  responses?: Prisma.ResponseCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetCreateNestedOneWithoutUserInput
  feedConfig?: Prisma.FeedConfigCreateNestedOneWithoutUserInput
}

export type UserUncheckedCreateWithoutSubscriptionsInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationUncheckedCreateNestedOneWithoutUserInput
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutUserInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetUncheckedCreateNestedOneWithoutUserInput
  feedConfig?: Prisma.FeedConfigUncheckedCreateNestedOneWithoutUserInput
}

export type UserCreateOrConnectWithoutSubscriptionsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutSubscriptionsInput, Prisma.UserUncheckedCreateWithoutSubscriptionsInput>
}

export type UserUpsertWithoutSubscriptionsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutSubscriptionsInput, Prisma.UserUncheckedUpdateWithoutSubscriptionsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutSubscriptionsInput, Prisma.UserUncheckedCreateWithoutSubscriptionsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutSubscriptionsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutSubscriptionsInput, Prisma.UserUncheckedUpdateWithoutSubscriptionsInput>
}

export type UserUpdateWithoutSubscriptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUpdateOneWithoutUserNestedInput
  responses?: Prisma.ResponseUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUpdateOneWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUpdateOneWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutSubscriptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUncheckedUpdateOneWithoutUserNestedInput
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutUserNestedInput
  notificationSettings?: Prisma.NotificationSettingsUncheckedUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUncheckedUpdateOneWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUncheckedUpdateOneWithoutUserNestedInput
}

export type UserCreateWithoutNotificationSettingsInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationCreateNestedOneWithoutUserInput
  responses?: Prisma.ResponseCreateNestedManyWithoutUserInput
  subscriptions?: Prisma.SubscriptionCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetCreateNestedOneWithoutUserInput
  feedConfig?: Prisma.FeedConfigCreateNestedOneWithoutUserInput
}

export type UserUncheckedCreateWithoutNotificationSettingsInput = {
  id?: string
  userName: string
  password?: string | null
  name: string
  role?: $Enums.Role
  feedId?: string
  invitation?: Prisma.UserInvitationUncheckedCreateNestedOneWithoutUserInput
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutUserInput
  subscriptions?: Prisma.SubscriptionUncheckedCreateNestedManyWithoutUserInput
  passwordReset?: Prisma.PasswordResetUncheckedCreateNestedOneWithoutUserInput
  feedConfig?: Prisma.FeedConfigUncheckedCreateNestedOneWithoutUserInput
}

export type UserCreateOrConnectWithoutNotificationSettingsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutNotificationSettingsInput, Prisma.UserUncheckedCreateWithoutNotificationSettingsInput>
}

export type UserUpsertWithoutNotificationSettingsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutNotificationSettingsInput, Prisma.UserUncheckedUpdateWithoutNotificationSettingsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutNotificationSettingsInput, Prisma.UserUncheckedCreateWithoutNotificationSettingsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutNotificationSettingsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutNotificationSettingsInput, Prisma.UserUncheckedUpdateWithoutNotificationSettingsInput>
}

export type UserUpdateWithoutNotificationSettingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUpdateOneWithoutUserNestedInput
  responses?: Prisma.ResponseUpdateManyWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUpdateOneWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUpdateOneWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutNotificationSettingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  feedId?: Prisma.StringFieldUpdateOperationsInput | string
  invitation?: Prisma.UserInvitationUncheckedUpdateOneWithoutUserNestedInput
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutUserNestedInput
  subscriptions?: Prisma.SubscriptionUncheckedUpdateManyWithoutUserNestedInput
  passwordReset?: Prisma.PasswordResetUncheckedUpdateOneWithoutUserNestedInput
  feedConfig?: Prisma.FeedConfigUncheckedUpdateOneWithoutUserNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  responses: number
  subscriptions: number
  notificationSettings: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  responses?: boolean | UserCountOutputTypeCountResponsesArgs
  subscriptions?: boolean | UserCountOutputTypeCountSubscriptionsArgs
  notificationSettings?: boolean | UserCountOutputTypeCountNotificationSettingsArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountResponsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ResponseWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountSubscriptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubscriptionWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountNotificationSettingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotificationSettingsWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userName?: boolean
  password?: boolean
  name?: boolean
  role?: boolean
  feedId?: boolean
  invitation?: boolean | Prisma.User$invitationArgs<ExtArgs>
  responses?: boolean | Prisma.User$responsesArgs<ExtArgs>
  subscriptions?: boolean | Prisma.User$subscriptionsArgs<ExtArgs>
  notificationSettings?: boolean | Prisma.User$notificationSettingsArgs<ExtArgs>
  passwordReset?: boolean | Prisma.User$passwordResetArgs<ExtArgs>
  feedConfig?: boolean | Prisma.User$feedConfigArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userName?: boolean
  password?: boolean
  name?: boolean
  role?: boolean
  feedId?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userName?: boolean
  password?: boolean
  name?: boolean
  role?: boolean
  feedId?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  userName?: boolean
  password?: boolean
  name?: boolean
  role?: boolean
  feedId?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userName" | "password" | "name" | "role" | "feedId", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  invitation?: boolean | Prisma.User$invitationArgs<ExtArgs>
  responses?: boolean | Prisma.User$responsesArgs<ExtArgs>
  subscriptions?: boolean | Prisma.User$subscriptionsArgs<ExtArgs>
  notificationSettings?: boolean | Prisma.User$notificationSettingsArgs<ExtArgs>
  passwordReset?: boolean | Prisma.User$passwordResetArgs<ExtArgs>
  feedConfig?: boolean | Prisma.User$feedConfigArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    invitation: Prisma.$UserInvitationPayload<ExtArgs> | null
    responses: Prisma.$ResponsePayload<ExtArgs>[]
    subscriptions: Prisma.$SubscriptionPayload<ExtArgs>[]
    notificationSettings: Prisma.$NotificationSettingsPayload<ExtArgs>[]
    passwordReset: Prisma.$PasswordResetPayload<ExtArgs> | null
    feedConfig: Prisma.$FeedConfigPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userName: string
    password: string | null
    name: string
    role: $Enums.Role
    feedId: string
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  invitation<T extends Prisma.User$invitationArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$invitationArgs<ExtArgs>>): Prisma.Prisma__UserInvitationClient<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  responses<T extends Prisma.User$responsesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$responsesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  subscriptions<T extends Prisma.User$subscriptionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$subscriptionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubscriptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  notificationSettings<T extends Prisma.User$notificationSettingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$notificationSettingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationSettingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  passwordReset<T extends Prisma.User$passwordResetArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$passwordResetArgs<ExtArgs>>): Prisma.Prisma__PasswordResetClient<runtime.Types.Result.GetResult<Prisma.$PasswordResetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  feedConfig<T extends Prisma.User$feedConfigArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$feedConfigArgs<ExtArgs>>): Prisma.Prisma__FeedConfigClient<runtime.Types.Result.GetResult<Prisma.$FeedConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly userName: Prisma.FieldRef<"User", 'String'>
  readonly password: Prisma.FieldRef<"User", 'String'>
  readonly name: Prisma.FieldRef<"User", 'String'>
  readonly role: Prisma.FieldRef<"User", 'Role'>
  readonly feedId: Prisma.FieldRef<"User", 'String'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.invitation
 */
export type User$invitationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
  where?: Prisma.UserInvitationWhereInput
}

/**
 * User.responses
 */
export type User$responsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Response
   */
  select?: Prisma.ResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Response
   */
  omit?: Prisma.ResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponseInclude<ExtArgs> | null
  where?: Prisma.ResponseWhereInput
  orderBy?: Prisma.ResponseOrderByWithRelationInput | Prisma.ResponseOrderByWithRelationInput[]
  cursor?: Prisma.ResponseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ResponseScalarFieldEnum | Prisma.ResponseScalarFieldEnum[]
}

/**
 * User.subscriptions
 */
export type User$subscriptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscription
   */
  select?: Prisma.SubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscription
   */
  omit?: Prisma.SubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionInclude<ExtArgs> | null
  where?: Prisma.SubscriptionWhereInput
  orderBy?: Prisma.SubscriptionOrderByWithRelationInput | Prisma.SubscriptionOrderByWithRelationInput[]
  cursor?: Prisma.SubscriptionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SubscriptionScalarFieldEnum | Prisma.SubscriptionScalarFieldEnum[]
}

/**
 * User.notificationSettings
 */
export type User$notificationSettingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationSettings
   */
  select?: Prisma.NotificationSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationSettings
   */
  omit?: Prisma.NotificationSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationSettingsInclude<ExtArgs> | null
  where?: Prisma.NotificationSettingsWhereInput
  orderBy?: Prisma.NotificationSettingsOrderByWithRelationInput | Prisma.NotificationSettingsOrderByWithRelationInput[]
  cursor?: Prisma.NotificationSettingsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NotificationSettingsScalarFieldEnum | Prisma.NotificationSettingsScalarFieldEnum[]
}

/**
 * User.passwordReset
 */
export type User$passwordResetArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PasswordReset
   */
  select?: Prisma.PasswordResetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PasswordReset
   */
  omit?: Prisma.PasswordResetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PasswordResetInclude<ExtArgs> | null
  where?: Prisma.PasswordResetWhereInput
}

/**
 * User.feedConfig
 */
export type User$feedConfigArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedConfig
   */
  select?: Prisma.FeedConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedConfig
   */
  omit?: Prisma.FeedConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedConfigInclude<ExtArgs> | null
  where?: Prisma.FeedConfigWhereInput
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
