
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserInvitation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UserInvitation
 * 
 */
export type UserInvitationModel = runtime.Types.Result.DefaultSelection<Prisma.$UserInvitationPayload>

export type AggregateUserInvitation = {
  _count: UserInvitationCountAggregateOutputType | null
  _min: UserInvitationMinAggregateOutputType | null
  _max: UserInvitationMaxAggregateOutputType | null
}

export type UserInvitationMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  userId: string | null
}

export type UserInvitationMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  userId: string | null
}

export type UserInvitationCountAggregateOutputType = {
  id: number
  createdAt: number
  userId: number
  _all: number
}


export type UserInvitationMinAggregateInputType = {
  id?: true
  createdAt?: true
  userId?: true
}

export type UserInvitationMaxAggregateInputType = {
  id?: true
  createdAt?: true
  userId?: true
}

export type UserInvitationCountAggregateInputType = {
  id?: true
  createdAt?: true
  userId?: true
  _all?: true
}

export type UserInvitationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserInvitation to aggregate.
   */
  where?: Prisma.UserInvitationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserInvitations to fetch.
   */
  orderBy?: Prisma.UserInvitationOrderByWithRelationInput | Prisma.UserInvitationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserInvitationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserInvitations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserInvitations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserInvitations
  **/
  _count?: true | UserInvitationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserInvitationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserInvitationMaxAggregateInputType
}

export type GetUserInvitationAggregateType<T extends UserInvitationAggregateArgs> = {
      [P in keyof T & keyof AggregateUserInvitation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserInvitation[P]>
    : Prisma.GetScalarType<T[P], AggregateUserInvitation[P]>
}




export type UserInvitationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserInvitationWhereInput
  orderBy?: Prisma.UserInvitationOrderByWithAggregationInput | Prisma.UserInvitationOrderByWithAggregationInput[]
  by: Prisma.UserInvitationScalarFieldEnum[] | Prisma.UserInvitationScalarFieldEnum
  having?: Prisma.UserInvitationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserInvitationCountAggregateInputType | true
  _min?: UserInvitationMinAggregateInputType
  _max?: UserInvitationMaxAggregateInputType
}

export type UserInvitationGroupByOutputType = {
  id: string
  createdAt: Date
  userId: string
  _count: UserInvitationCountAggregateOutputType | null
  _min: UserInvitationMinAggregateOutputType | null
  _max: UserInvitationMaxAggregateOutputType | null
}

type GetUserInvitationGroupByPayload<T extends UserInvitationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserInvitationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserInvitationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserInvitationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserInvitationGroupByOutputType[P]>
      }
    >
  >



export type UserInvitationWhereInput = {
  AND?: Prisma.UserInvitationWhereInput | Prisma.UserInvitationWhereInput[]
  OR?: Prisma.UserInvitationWhereInput[]
  NOT?: Prisma.UserInvitationWhereInput | Prisma.UserInvitationWhereInput[]
  id?: Prisma.StringFilter<"UserInvitation"> | string
  createdAt?: Prisma.DateTimeFilter<"UserInvitation"> | Date | string
  userId?: Prisma.StringFilter<"UserInvitation"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserInvitationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserInvitationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.UserInvitationWhereInput | Prisma.UserInvitationWhereInput[]
  OR?: Prisma.UserInvitationWhereInput[]
  NOT?: Prisma.UserInvitationWhereInput | Prisma.UserInvitationWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"UserInvitation"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId">

export type UserInvitationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.UserInvitationCountOrderByAggregateInput
  _max?: Prisma.UserInvitationMaxOrderByAggregateInput
  _min?: Prisma.UserInvitationMinOrderByAggregateInput
}

export type UserInvitationScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserInvitationScalarWhereWithAggregatesInput | Prisma.UserInvitationScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserInvitationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserInvitationScalarWhereWithAggregatesInput | Prisma.UserInvitationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserInvitation"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserInvitation"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"UserInvitation"> | string
}

export type UserInvitationCreateInput = {
  id?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutInvitationInput
}

export type UserInvitationUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  userId: string
}

export type UserInvitationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutInvitationNestedInput
}

export type UserInvitationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserInvitationCreateManyInput = {
  id?: string
  createdAt?: Date | string
  userId: string
}

export type UserInvitationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserInvitationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserInvitationNullableScalarRelationFilter = {
  is?: Prisma.UserInvitationWhereInput | null
  isNot?: Prisma.UserInvitationWhereInput | null
}

export type UserInvitationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type UserInvitationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type UserInvitationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type UserInvitationCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserInvitationCreateWithoutUserInput, Prisma.UserInvitationUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.UserInvitationCreateOrConnectWithoutUserInput
  connect?: Prisma.UserInvitationWhereUniqueInput
}

export type UserInvitationUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserInvitationCreateWithoutUserInput, Prisma.UserInvitationUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.UserInvitationCreateOrConnectWithoutUserInput
  connect?: Prisma.UserInvitationWhereUniqueInput
}

export type UserInvitationUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserInvitationCreateWithoutUserInput, Prisma.UserInvitationUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.UserInvitationCreateOrConnectWithoutUserInput
  upsert?: Prisma.UserInvitationUpsertWithoutUserInput
  disconnect?: Prisma.UserInvitationWhereInput | boolean
  delete?: Prisma.UserInvitationWhereInput | boolean
  connect?: Prisma.UserInvitationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserInvitationUpdateToOneWithWhereWithoutUserInput, Prisma.UserInvitationUpdateWithoutUserInput>, Prisma.UserInvitationUncheckedUpdateWithoutUserInput>
}

export type UserInvitationUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserInvitationCreateWithoutUserInput, Prisma.UserInvitationUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.UserInvitationCreateOrConnectWithoutUserInput
  upsert?: Prisma.UserInvitationUpsertWithoutUserInput
  disconnect?: Prisma.UserInvitationWhereInput | boolean
  delete?: Prisma.UserInvitationWhereInput | boolean
  connect?: Prisma.UserInvitationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserInvitationUpdateToOneWithWhereWithoutUserInput, Prisma.UserInvitationUpdateWithoutUserInput>, Prisma.UserInvitationUncheckedUpdateWithoutUserInput>
}

export type UserInvitationCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
}

export type UserInvitationUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
}

export type UserInvitationCreateOrConnectWithoutUserInput = {
  where: Prisma.UserInvitationWhereUniqueInput
  create: Prisma.XOR<Prisma.UserInvitationCreateWithoutUserInput, Prisma.UserInvitationUncheckedCreateWithoutUserInput>
}

export type UserInvitationUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.UserInvitationUpdateWithoutUserInput, Prisma.UserInvitationUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserInvitationCreateWithoutUserInput, Prisma.UserInvitationUncheckedCreateWithoutUserInput>
  where?: Prisma.UserInvitationWhereInput
}

export type UserInvitationUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.UserInvitationWhereInput
  data: Prisma.XOR<Prisma.UserInvitationUpdateWithoutUserInput, Prisma.UserInvitationUncheckedUpdateWithoutUserInput>
}

export type UserInvitationUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserInvitationUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserInvitationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userInvitation"]>

export type UserInvitationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userInvitation"]>

export type UserInvitationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userInvitation"]>

export type UserInvitationSelectScalar = {
  id?: boolean
  createdAt?: boolean
  userId?: boolean
}

export type UserInvitationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "userId", ExtArgs["result"]["userInvitation"]>
export type UserInvitationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserInvitationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserInvitationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserInvitationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserInvitation"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    userId: string
  }, ExtArgs["result"]["userInvitation"]>
  composites: {}
}

export type UserInvitationGetPayload<S extends boolean | null | undefined | UserInvitationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload, S>

export type UserInvitationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserInvitationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserInvitationCountAggregateInputType | true
  }

export interface UserInvitationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserInvitation'], meta: { name: 'UserInvitation' } }
  /**
   * Find zero or one UserInvitation that matches the filter.
   * @param {UserInvitationFindUniqueArgs} args - Arguments to find a UserInvitation
   * @example
   * // Get one UserInvitation
   * const userInvitation = await prisma.userInvitation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserInvitationFindUniqueArgs>(args: Prisma.SelectSubset<T, UserInvitationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserInvitationClient<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserInvitation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserInvitationFindUniqueOrThrowArgs} args - Arguments to find a UserInvitation
   * @example
   * // Get one UserInvitation
   * const userInvitation = await prisma.userInvitation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserInvitationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserInvitationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserInvitationClient<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserInvitation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserInvitationFindFirstArgs} args - Arguments to find a UserInvitation
   * @example
   * // Get one UserInvitation
   * const userInvitation = await prisma.userInvitation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserInvitationFindFirstArgs>(args?: Prisma.SelectSubset<T, UserInvitationFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserInvitationClient<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserInvitation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserInvitationFindFirstOrThrowArgs} args - Arguments to find a UserInvitation
   * @example
   * // Get one UserInvitation
   * const userInvitation = await prisma.userInvitation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserInvitationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserInvitationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserInvitationClient<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserInvitations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserInvitationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserInvitations
   * const userInvitations = await prisma.userInvitation.findMany()
   * 
   * // Get first 10 UserInvitations
   * const userInvitations = await prisma.userInvitation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userInvitationWithIdOnly = await prisma.userInvitation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserInvitationFindManyArgs>(args?: Prisma.SelectSubset<T, UserInvitationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserInvitation.
   * @param {UserInvitationCreateArgs} args - Arguments to create a UserInvitation.
   * @example
   * // Create one UserInvitation
   * const UserInvitation = await prisma.userInvitation.create({
   *   data: {
   *     // ... data to create a UserInvitation
   *   }
   * })
   * 
   */
  create<T extends UserInvitationCreateArgs>(args: Prisma.SelectSubset<T, UserInvitationCreateArgs<ExtArgs>>): Prisma.Prisma__UserInvitationClient<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserInvitations.
   * @param {UserInvitationCreateManyArgs} args - Arguments to create many UserInvitations.
   * @example
   * // Create many UserInvitations
   * const userInvitation = await prisma.userInvitation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserInvitationCreateManyArgs>(args?: Prisma.SelectSubset<T, UserInvitationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserInvitations and returns the data saved in the database.
   * @param {UserInvitationCreateManyAndReturnArgs} args - Arguments to create many UserInvitations.
   * @example
   * // Create many UserInvitations
   * const userInvitation = await prisma.userInvitation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserInvitations and only return the `id`
   * const userInvitationWithIdOnly = await prisma.userInvitation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserInvitationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserInvitationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserInvitation.
   * @param {UserInvitationDeleteArgs} args - Arguments to delete one UserInvitation.
   * @example
   * // Delete one UserInvitation
   * const UserInvitation = await prisma.userInvitation.delete({
   *   where: {
   *     // ... filter to delete one UserInvitation
   *   }
   * })
   * 
   */
  delete<T extends UserInvitationDeleteArgs>(args: Prisma.SelectSubset<T, UserInvitationDeleteArgs<ExtArgs>>): Prisma.Prisma__UserInvitationClient<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserInvitation.
   * @param {UserInvitationUpdateArgs} args - Arguments to update one UserInvitation.
   * @example
   * // Update one UserInvitation
   * const userInvitation = await prisma.userInvitation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserInvitationUpdateArgs>(args: Prisma.SelectSubset<T, UserInvitationUpdateArgs<ExtArgs>>): Prisma.Prisma__UserInvitationClient<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserInvitations.
   * @param {UserInvitationDeleteManyArgs} args - Arguments to filter UserInvitations to delete.
   * @example
   * // Delete a few UserInvitations
   * const { count } = await prisma.userInvitation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserInvitationDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserInvitationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserInvitations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserInvitationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserInvitations
   * const userInvitation = await prisma.userInvitation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserInvitationUpdateManyArgs>(args: Prisma.SelectSubset<T, UserInvitationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserInvitations and returns the data updated in the database.
   * @param {UserInvitationUpdateManyAndReturnArgs} args - Arguments to update many UserInvitations.
   * @example
   * // Update many UserInvitations
   * const userInvitation = await prisma.userInvitation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserInvitations and only return the `id`
   * const userInvitationWithIdOnly = await prisma.userInvitation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserInvitationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserInvitationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserInvitation.
   * @param {UserInvitationUpsertArgs} args - Arguments to update or create a UserInvitation.
   * @example
   * // Update or create a UserInvitation
   * const userInvitation = await prisma.userInvitation.upsert({
   *   create: {
   *     // ... data to create a UserInvitation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserInvitation we want to update
   *   }
   * })
   */
  upsert<T extends UserInvitationUpsertArgs>(args: Prisma.SelectSubset<T, UserInvitationUpsertArgs<ExtArgs>>): Prisma.Prisma__UserInvitationClient<runtime.Types.Result.GetResult<Prisma.$UserInvitationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserInvitations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserInvitationCountArgs} args - Arguments to filter UserInvitations to count.
   * @example
   * // Count the number of UserInvitations
   * const count = await prisma.userInvitation.count({
   *   where: {
   *     // ... the filter for the UserInvitations we want to count
   *   }
   * })
  **/
  count<T extends UserInvitationCountArgs>(
    args?: Prisma.Subset<T, UserInvitationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserInvitationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserInvitation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserInvitationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserInvitationAggregateArgs>(args: Prisma.Subset<T, UserInvitationAggregateArgs>): Prisma.PrismaPromise<GetUserInvitationAggregateType<T>>

  /**
   * Group by UserInvitation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserInvitationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserInvitationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserInvitationGroupByArgs['orderBy'] }
      : { orderBy?: UserInvitationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserInvitationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserInvitationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserInvitation model
 */
readonly fields: UserInvitationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserInvitation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserInvitationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserInvitation model
 */
export interface UserInvitationFieldRefs {
  readonly id: Prisma.FieldRef<"UserInvitation", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserInvitation", 'DateTime'>
  readonly userId: Prisma.FieldRef<"UserInvitation", 'String'>
}
    

// Custom InputTypes
/**
 * UserInvitation findUnique
 */
export type UserInvitationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
  /**
   * Filter, which UserInvitation to fetch.
   */
  where: Prisma.UserInvitationWhereUniqueInput
}

/**
 * UserInvitation findUniqueOrThrow
 */
export type UserInvitationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
  /**
   * Filter, which UserInvitation to fetch.
   */
  where: Prisma.UserInvitationWhereUniqueInput
}

/**
 * UserInvitation findFirst
 */
export type UserInvitationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
  /**
   * Filter, which UserInvitation to fetch.
   */
  where?: Prisma.UserInvitationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserInvitations to fetch.
   */
  orderBy?: Prisma.UserInvitationOrderByWithRelationInput | Prisma.UserInvitationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserInvitations.
   */
  cursor?: Prisma.UserInvitationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserInvitations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserInvitations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserInvitations.
   */
  distinct?: Prisma.UserInvitationScalarFieldEnum | Prisma.UserInvitationScalarFieldEnum[]
}

/**
 * UserInvitation findFirstOrThrow
 */
export type UserInvitationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
  /**
   * Filter, which UserInvitation to fetch.
   */
  where?: Prisma.UserInvitationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserInvitations to fetch.
   */
  orderBy?: Prisma.UserInvitationOrderByWithRelationInput | Prisma.UserInvitationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserInvitations.
   */
  cursor?: Prisma.UserInvitationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserInvitations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserInvitations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserInvitations.
   */
  distinct?: Prisma.UserInvitationScalarFieldEnum | Prisma.UserInvitationScalarFieldEnum[]
}

/**
 * UserInvitation findMany
 */
export type UserInvitationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
  /**
   * Filter, which UserInvitations to fetch.
   */
  where?: Prisma.UserInvitationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserInvitations to fetch.
   */
  orderBy?: Prisma.UserInvitationOrderByWithRelationInput | Prisma.UserInvitationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserInvitations.
   */
  cursor?: Prisma.UserInvitationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserInvitations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserInvitations.
   */
  skip?: number
  distinct?: Prisma.UserInvitationScalarFieldEnum | Prisma.UserInvitationScalarFieldEnum[]
}

/**
 * UserInvitation create
 */
export type UserInvitationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
  /**
   * The data needed to create a UserInvitation.
   */
  data: Prisma.XOR<Prisma.UserInvitationCreateInput, Prisma.UserInvitationUncheckedCreateInput>
}

/**
 * UserInvitation createMany
 */
export type UserInvitationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserInvitations.
   */
  data: Prisma.UserInvitationCreateManyInput | Prisma.UserInvitationCreateManyInput[]
}

/**
 * UserInvitation createManyAndReturn
 */
export type UserInvitationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * The data used to create many UserInvitations.
   */
  data: Prisma.UserInvitationCreateManyInput | Prisma.UserInvitationCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserInvitation update
 */
export type UserInvitationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
  /**
   * The data needed to update a UserInvitation.
   */
  data: Prisma.XOR<Prisma.UserInvitationUpdateInput, Prisma.UserInvitationUncheckedUpdateInput>
  /**
   * Choose, which UserInvitation to update.
   */
  where: Prisma.UserInvitationWhereUniqueInput
}

/**
 * UserInvitation updateMany
 */
export type UserInvitationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserInvitations.
   */
  data: Prisma.XOR<Prisma.UserInvitationUpdateManyMutationInput, Prisma.UserInvitationUncheckedUpdateManyInput>
  /**
   * Filter which UserInvitations to update
   */
  where?: Prisma.UserInvitationWhereInput
  /**
   * Limit how many UserInvitations to update.
   */
  limit?: number
}

/**
 * UserInvitation updateManyAndReturn
 */
export type UserInvitationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * The data used to update UserInvitations.
   */
  data: Prisma.XOR<Prisma.UserInvitationUpdateManyMutationInput, Prisma.UserInvitationUncheckedUpdateManyInput>
  /**
   * Filter which UserInvitations to update
   */
  where?: Prisma.UserInvitationWhereInput
  /**
   * Limit how many UserInvitations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserInvitation upsert
 */
export type UserInvitationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
  /**
   * The filter to search for the UserInvitation to update in case it exists.
   */
  where: Prisma.UserInvitationWhereUniqueInput
  /**
   * In case the UserInvitation found by the `where` argument doesn't exist, create a new UserInvitation with this data.
   */
  create: Prisma.XOR<Prisma.UserInvitationCreateInput, Prisma.UserInvitationUncheckedCreateInput>
  /**
   * In case the UserInvitation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserInvitationUpdateInput, Prisma.UserInvitationUncheckedUpdateInput>
}

/**
 * UserInvitation delete
 */
export type UserInvitationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
  /**
   * Filter which UserInvitation to delete.
   */
  where: Prisma.UserInvitationWhereUniqueInput
}

/**
 * UserInvitation deleteMany
 */
export type UserInvitationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserInvitations to delete
   */
  where?: Prisma.UserInvitationWhereInput
  /**
   * Limit how many UserInvitations to delete.
   */
  limit?: number
}

/**
 * UserInvitation without action
 */
export type UserInvitationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserInvitation
   */
  select?: Prisma.UserInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserInvitation
   */
  omit?: Prisma.UserInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInvitationInclude<ExtArgs> | null
}
