/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentryTunnelRouteImport } from './routes/sentry-tunnel'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as InviteInviteIdRouteImport } from './routes/invite/$inviteId'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'

const SentryTunnelRoute = SentryTunnelRouteImport.update({
  id: '/sentry-tunnel',
  path: '/sentry-tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const InviteInviteIdRoute = InviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sentry-tunnel': typeof SentryTunnelRoute
  '/settings': typeof AuthedSettingsRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesByTo {
  '/sentry-tunnel': typeof SentryTunnelRoute
  '/settings': typeof AuthedSettingsRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sentry-tunnel': typeof SentryTunnelRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sentry-tunnel' | '/settings' | '/invite/$inviteId' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sentry-tunnel' | '/settings' | '/invite/$inviteId' | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/sentry-tunnel'
    | '/_authed/settings'
    | '/invite/$inviteId'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SentryTunnelRoute: typeof SentryTunnelRoute
  InviteInviteIdRoute: typeof InviteInviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentry-tunnel': {
      id: '/sentry-tunnel'
      path: '/sentry-tunnel'
      fullPath: '/sentry-tunnel'
      preLoaderRoute: typeof SentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/invite/$inviteId': {
      id: '/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof InviteInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SentryTunnelRoute: SentryTunnelRoute,
  InviteInviteIdRoute: InviteInviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
