/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentryTunnelRouteImport } from './routes/sentry-tunnel'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as InviteInviteIdRouteImport } from './routes/invite/$inviteId'
import { Route as AuthedCreateRouteImport } from './routes/_authed/create'
import { Route as AuthedSettingsUsersRouteImport } from './routes/_authed/settings/users'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed/settings/profile'
import { Route as AuthedApptApptIdRouteImport } from './routes/_authed/appt/$apptId'

const SentryTunnelRoute = SentryTunnelRouteImport.update({
  id: '/sentry-tunnel',
  path: '/sentry-tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const InviteInviteIdRoute = InviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCreateRoute = AuthedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsUsersRoute = AuthedSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApptApptIdRoute = AuthedApptApptIdRouteImport.update({
  id: '/appt/$apptId',
  path: '/appt/$apptId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sentry-tunnel': typeof SentryTunnelRoute
  '/create': typeof AuthedCreateRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/': typeof AuthedIndexRoute
  '/appt/$apptId': typeof AuthedApptApptIdRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/users': typeof AuthedSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/sentry-tunnel': typeof SentryTunnelRoute
  '/create': typeof AuthedCreateRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/': typeof AuthedIndexRoute
  '/appt/$apptId': typeof AuthedApptApptIdRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/users': typeof AuthedSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sentry-tunnel': typeof SentryTunnelRoute
  '/_authed/create': typeof AuthedCreateRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/appt/$apptId': typeof AuthedApptApptIdRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/_authed/settings/users': typeof AuthedSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sentry-tunnel'
    | '/create'
    | '/invite/$inviteId'
    | '/'
    | '/appt/$apptId'
    | '/settings/profile'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sentry-tunnel'
    | '/create'
    | '/invite/$inviteId'
    | '/'
    | '/appt/$apptId'
    | '/settings/profile'
    | '/settings/users'
  id:
    | '__root__'
    | '/_authed'
    | '/sentry-tunnel'
    | '/_authed/create'
    | '/invite/$inviteId'
    | '/_authed/'
    | '/_authed/appt/$apptId'
    | '/_authed/settings/profile'
    | '/_authed/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SentryTunnelRoute: typeof SentryTunnelRoute
  InviteInviteIdRoute: typeof InviteInviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentry-tunnel': {
      id: '/sentry-tunnel'
      path: '/sentry-tunnel'
      fullPath: '/sentry-tunnel'
      preLoaderRoute: typeof SentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/invite/$inviteId': {
      id: '/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof InviteInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/create': {
      id: '/_authed/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthedCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/users': {
      id: '/_authed/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthedSettingsUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/appt/$apptId': {
      id: '/_authed/appt/$apptId'
      path: '/appt/$apptId'
      fullPath: '/appt/$apptId'
      preLoaderRoute: typeof AuthedApptApptIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCreateRoute: typeof AuthedCreateRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedApptApptIdRoute: typeof AuthedApptApptIdRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
  AuthedSettingsUsersRoute: typeof AuthedSettingsUsersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCreateRoute: AuthedCreateRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedApptApptIdRoute: AuthedApptApptIdRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
  AuthedSettingsUsersRoute: AuthedSettingsUsersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SentryTunnelRoute: SentryTunnelRoute,
  InviteInviteIdRoute: InviteInviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
