/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentryTunnelRouteImport } from './routes/sentry-tunnel'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as PasswordResetResetIdRouteImport } from './routes/password-reset/$resetId'
import { Route as InviteInviteIdRouteImport } from './routes/invite/$inviteId'
import { Route as AuthedCreateRouteImport } from './routes/_authed/create'
import { Route as AuthedTeamsIndexRouteImport } from './routes/_authed/teams/index'
import { Route as AuthedPlayersIndexRouteImport } from './routes/_authed/players/index'
import { Route as AuthedApptsIndexRouteImport } from './routes/_authed/appts/index'
import { Route as AuthedTeamsTeamIdRouteImport } from './routes/_authed/teams/$teamId'
import { Route as AuthedSettingsUsersRouteImport } from './routes/_authed/settings/users'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed/settings/profile'
import { Route as AuthedSettingsImportsRouteImport } from './routes/_authed/settings/imports'
import { Route as AuthedPlayersPlayerIdRouteImport } from './routes/_authed/players/$playerId'
import { Route as AuthedApptsCalendarRouteImport } from './routes/_authed/appts/calendar'
import { Route as AuthedApptsApptIdRouteImport } from './routes/_authed/appts/$apptId'

const SentryTunnelRoute = SentryTunnelRouteImport.update({
  id: '/sentry-tunnel',
  path: '/sentry-tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const PasswordResetResetIdRoute = PasswordResetResetIdRouteImport.update({
  id: '/password-reset/$resetId',
  path: '/password-reset/$resetId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInviteIdRoute = InviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCreateRoute = AuthedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeamsIndexRoute = AuthedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlayersIndexRoute = AuthedPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApptsIndexRoute = AuthedApptsIndexRouteImport.update({
  id: '/appts/',
  path: '/appts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeamsTeamIdRoute = AuthedTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsUsersRoute = AuthedSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsImportsRoute = AuthedSettingsImportsRouteImport.update({
  id: '/settings/imports',
  path: '/settings/imports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlayersPlayerIdRoute = AuthedPlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApptsCalendarRoute = AuthedApptsCalendarRouteImport.update({
  id: '/appts/calendar',
  path: '/appts/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApptsApptIdRoute = AuthedApptsApptIdRouteImport.update({
  id: '/appts/$apptId',
  path: '/appts/$apptId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/logout': typeof LogoutRoute
  '/sentry-tunnel': typeof SentryTunnelRoute
  '/create': typeof AuthedCreateRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/password-reset/$resetId': typeof PasswordResetResetIdRoute
  '/': typeof AuthedIndexRoute
  '/appts/$apptId': typeof AuthedApptsApptIdRoute
  '/appts/calendar': typeof AuthedApptsCalendarRoute
  '/players/$playerId': typeof AuthedPlayersPlayerIdRoute
  '/settings/imports': typeof AuthedSettingsImportsRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/users': typeof AuthedSettingsUsersRoute
  '/teams/$teamId': typeof AuthedTeamsTeamIdRoute
  '/appts': typeof AuthedApptsIndexRoute
  '/players': typeof AuthedPlayersIndexRoute
  '/teams': typeof AuthedTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/logout': typeof LogoutRoute
  '/sentry-tunnel': typeof SentryTunnelRoute
  '/create': typeof AuthedCreateRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/password-reset/$resetId': typeof PasswordResetResetIdRoute
  '/': typeof AuthedIndexRoute
  '/appts/$apptId': typeof AuthedApptsApptIdRoute
  '/appts/calendar': typeof AuthedApptsCalendarRoute
  '/players/$playerId': typeof AuthedPlayersPlayerIdRoute
  '/settings/imports': typeof AuthedSettingsImportsRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/users': typeof AuthedSettingsUsersRoute
  '/teams/$teamId': typeof AuthedTeamsTeamIdRoute
  '/appts': typeof AuthedApptsIndexRoute
  '/players': typeof AuthedPlayersIndexRoute
  '/teams': typeof AuthedTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/sentry-tunnel': typeof SentryTunnelRoute
  '/_authed/create': typeof AuthedCreateRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/password-reset/$resetId': typeof PasswordResetResetIdRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/appts/$apptId': typeof AuthedApptsApptIdRoute
  '/_authed/appts/calendar': typeof AuthedApptsCalendarRoute
  '/_authed/players/$playerId': typeof AuthedPlayersPlayerIdRoute
  '/_authed/settings/imports': typeof AuthedSettingsImportsRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/_authed/settings/users': typeof AuthedSettingsUsersRoute
  '/_authed/teams/$teamId': typeof AuthedTeamsTeamIdRoute
  '/_authed/appts/': typeof AuthedApptsIndexRoute
  '/_authed/players/': typeof AuthedPlayersIndexRoute
  '/_authed/teams/': typeof AuthedTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/logout'
    | '/sentry-tunnel'
    | '/create'
    | '/invite/$inviteId'
    | '/password-reset/$resetId'
    | '/'
    | '/appts/$apptId'
    | '/appts/calendar'
    | '/players/$playerId'
    | '/settings/imports'
    | '/settings/profile'
    | '/settings/users'
    | '/teams/$teamId'
    | '/appts'
    | '/players'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logout'
    | '/sentry-tunnel'
    | '/create'
    | '/invite/$inviteId'
    | '/password-reset/$resetId'
    | '/'
    | '/appts/$apptId'
    | '/appts/calendar'
    | '/players/$playerId'
    | '/settings/imports'
    | '/settings/profile'
    | '/settings/users'
    | '/teams/$teamId'
    | '/appts'
    | '/players'
    | '/teams'
  id:
    | '__root__'
    | '/_authed'
    | '/logout'
    | '/sentry-tunnel'
    | '/_authed/create'
    | '/invite/$inviteId'
    | '/password-reset/$resetId'
    | '/_authed/'
    | '/_authed/appts/$apptId'
    | '/_authed/appts/calendar'
    | '/_authed/players/$playerId'
    | '/_authed/settings/imports'
    | '/_authed/settings/profile'
    | '/_authed/settings/users'
    | '/_authed/teams/$teamId'
    | '/_authed/appts/'
    | '/_authed/players/'
    | '/_authed/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  SentryTunnelRoute: typeof SentryTunnelRoute
  InviteInviteIdRoute: typeof InviteInviteIdRoute
  PasswordResetResetIdRoute: typeof PasswordResetResetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentry-tunnel': {
      id: '/sentry-tunnel'
      path: '/sentry-tunnel'
      fullPath: '/sentry-tunnel'
      preLoaderRoute: typeof SentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/password-reset/$resetId': {
      id: '/password-reset/$resetId'
      path: '/password-reset/$resetId'
      fullPath: '/password-reset/$resetId'
      preLoaderRoute: typeof PasswordResetResetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$inviteId': {
      id: '/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof InviteInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/create': {
      id: '/_authed/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthedCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/': {
      id: '/_authed/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthedTeamsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/players/': {
      id: '/_authed/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthedPlayersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/appts/': {
      id: '/_authed/appts/'
      path: '/appts'
      fullPath: '/appts'
      preLoaderRoute: typeof AuthedApptsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/$teamId': {
      id: '/_authed/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthedTeamsTeamIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/users': {
      id: '/_authed/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthedSettingsUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/imports': {
      id: '/_authed/settings/imports'
      path: '/settings/imports'
      fullPath: '/settings/imports'
      preLoaderRoute: typeof AuthedSettingsImportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/players/$playerId': {
      id: '/_authed/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/appts/calendar': {
      id: '/_authed/appts/calendar'
      path: '/appts/calendar'
      fullPath: '/appts/calendar'
      preLoaderRoute: typeof AuthedApptsCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/appts/$apptId': {
      id: '/_authed/appts/$apptId'
      path: '/appts/$apptId'
      fullPath: '/appts/$apptId'
      preLoaderRoute: typeof AuthedApptsApptIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCreateRoute: typeof AuthedCreateRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedApptsApptIdRoute: typeof AuthedApptsApptIdRoute
  AuthedApptsCalendarRoute: typeof AuthedApptsCalendarRoute
  AuthedPlayersPlayerIdRoute: typeof AuthedPlayersPlayerIdRoute
  AuthedSettingsImportsRoute: typeof AuthedSettingsImportsRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
  AuthedSettingsUsersRoute: typeof AuthedSettingsUsersRoute
  AuthedTeamsTeamIdRoute: typeof AuthedTeamsTeamIdRoute
  AuthedApptsIndexRoute: typeof AuthedApptsIndexRoute
  AuthedPlayersIndexRoute: typeof AuthedPlayersIndexRoute
  AuthedTeamsIndexRoute: typeof AuthedTeamsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCreateRoute: AuthedCreateRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedApptsApptIdRoute: AuthedApptsApptIdRoute,
  AuthedApptsCalendarRoute: AuthedApptsCalendarRoute,
  AuthedPlayersPlayerIdRoute: AuthedPlayersPlayerIdRoute,
  AuthedSettingsImportsRoute: AuthedSettingsImportsRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
  AuthedSettingsUsersRoute: AuthedSettingsUsersRoute,
  AuthedTeamsTeamIdRoute: AuthedTeamsTeamIdRoute,
  AuthedApptsIndexRoute: AuthedApptsIndexRoute,
  AuthedPlayersIndexRoute: AuthedPlayersIndexRoute,
  AuthedTeamsIndexRoute: AuthedTeamsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  SentryTunnelRoute: SentryTunnelRoute,
  InviteInviteIdRoute: InviteInviteIdRoute,
  PasswordResetResetIdRoute: PasswordResetResetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
